# Notebook to check the ETL data

In [15]:
import pandas as pd
import os

In [16]:
## We load datasets

data_folder_path = os.path.join(os.getcwd(), '..', 'data')
files_in_data_folder = os.listdir(data_folder_path)

for file_name in files_in_data_folder:
    if file_name.endswith('.parquet'):
        df_name = file_name.replace('.parquet', '')
        file_path = os.path.join(data_folder_path, file_name)
        globals()[df_name] = pd.read_parquet(file_path)
        print(df_name)

bmo_vertical
odis_rel_formations
referentiels
odis_communes
associations_vertical
referentiels copy
odis_bassins_de_vie
pois
odis_rel_metiers
structures_inclusion_ccas

In [17]:
odis_communes.inc_socle_admin_score.describe()

count    35014.000000
mean         0.115668
std          0.254436
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: inc_socle_admin_score, dtype: float64

In [22]:
len(structures_inclusion_ccas.codgeo.unique())

12416

In [23]:
structures_inclusion_ccas.head()

,id,nom,codgeo,courriel,telephone,site_web,adresse,commune
113,dora--0e0f583b-d2f3-4834-bb49-83550f6f37fe,CTRE COM ACTION SOCIALE VILLEFRANCHE CCAS,12300,ccas@villefranchederouergue.fr,+33565651641,https://villefranche-de-rouergue.fr/centre-com...,Place Bernard Lhez,Villefranche-de-Rouergue
179,dora--3d5738b2-d320-4150-85fb-cb88c00bedc3,CENTRE COMMUNAL D ACTION SOCIALE,94054,ccas@mairie-orly.fr,+33148902000,https://www.mairie-orly.fr/transitions/solidar...,7 Avenue Adrien Raynal,Orly
180,dora--3d6e9018-7ddb-43e1-867d-a380f365afe2,CCAS de Chartres de Bretagne,35238,direction@ccaschartres35.fr,None,None,1 RUE SAINT-ANTHEME,Rennes
201,dora--4de7ce47-0c48-4c73-a7b0-f7f36f135b6d,CCAS (CTRE COM ACTION SOCIALE DE SARRIANS),84122,ccas@ville-sarrians.fr,+33490122103,None,Place du 1er Août 1944,Sarrians
321,dora--9cdc7ca2-615f-4378-895d-25656b8efdeb,COMMUNAUTE DE COMMUNES DE LA GRANDE VALLEE DE ...,51030,transports@ccgvm.com,+33326547630,None,Place Henri Martin,Aÿ-Champagne

In [24]:
structures_inclusion_ccas[structures_inclusion_ccas['codgeo'] == '13103']

,id,nom,codgeo,courriel,telephone,site_web,adresse,commune
53067,ma-boussole-aidants--10004226,Centre communal d'action sociale (CCAS) - Salo...,13103,info.ccas@salon-de-provence.org,+33490170193,https://www.salondeprovence.fr/vivre-ensemble/...,65 Avenue Michelet,Salon-de-Provence

In [25]:
structures_inclusion_ccas[structures_inclusion_ccas['commune'] == 'Libourne']

,id,nom,codgeo,courriel,telephone,site_web,adresse,commune
50345,ma-boussole-aidants--10004464,Centre communal d'action sociale (CCAS) - Libo...,33243,ccas@mairie-libourne.fr,+33557553370,https://www.libourne.fr/utile/social,146 Rue du Président Doumer,Libourne