# Notebook to check the ETL data

In [1]:
import pandas as pd
import os

In [2]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [3]:
## We load datasets

data_folder_path = os.path.join(os.getcwd(), '..', 'data')
files_in_data_folder = os.listdir(data_folder_path)

for file_name in files_in_data_folder:
    if file_name.endswith('.parquet'):
        df_name = file_name.replace('.parquet', '')
        file_path = os.path.join(data_folder_path, file_name)
        globals()[df_name] = pd.read_parquet(file_path)
        print(df_name)

odis_ccas
odis_communes
odis_ft_jobs_agg
odis_formations_agg
odis_inclusion_jobs
odis_referentiels
odis_communes_pre
odis_associations_agg
odis_bassins_de_vie
odis_refugee_associations
odis_pois

In [95]:
iml_cols = [x for x in odis_communes.columns.tolist() if 'iml' in x]
odis_communes[iml_cols].describe()

       heb_loc_iml_count  heb_loc_iml_density  heb_loc_iml_scaled
count       35013.000000         3.501300e+04        35013.000000
mean            0.000057         3.687551e-07            0.000004
std             0.007558         6.900058e-05            0.000690
min             0.000000         0.000000e+00            0.000000
25%             0.000000         0.000000e+00            0.000000
50%             0.000000         0.000000e+00            0.000000
75%             0.000000         0.000000e+00            0.000000
max             1.000000         1.291122e-02            0.129112

## Communes

In [18]:
odis_communes[['codgeo'] + [col for col in odis_communes.columns if col.startswith('log_')]].head()

,codgeo,log_priv_vacant_plus_2ans,log_soc_inoc_ratio,log_pp_occup,log_vac_struct_ratio,log_loyer_moyen_appt_all_scaled,log_loyer_moyen_appt_t1_t2_scaled,log_loyer_moyen_appt_t3_p_scaled,log_loyer_moyen_house_all_scaled,log_vac_scaled,log_occup_scaled,log_soc_inoc_scaled
0,01001,0.0,0.031250,0.937500,0.000000,NaN,NaN,NaN,NaN,0.000000,0.837763,0.312500
1,01002,0.0,0.000000,0.958333,0.000000,NaN,NaN,NaN,NaN,0.000000,0.891842,0.000000
2,01004,207.0,0.042050,0.770498,0.034796,0.693323,0.754089,0.710634,0.717108,0.347958,0.404260,0.420499
3,01005,13.0,0.026549,0.873685,0.016069,NaN,NaN,NaN,NaN,0.160692,0.672113,0.265487
4,01006,0.0,0.000000,0.909091,0.000000,NaN,NaN,NaN,NaN,0.000000,0.764019,0.000000

In [6]:
odis_communes[odis_communes.plm == True].head()

,codgeo,dep_code,reg_code,commune,plm,epci_code,population,pop_active,pop_employes,pop_chomeurs,log_priv_vacant_plus_2ans,edu_pe_tx_couverture,edu_maternelle_ct,edu_elementaire_ct,edu_college_ct,edu_lycee_ct,pol_num,total_eleves,ecoles_count,risky_schools_count,bpe_creches_count,gare_count,nb_stops_bus,nb_stops_tram,nb_stops_metro,nb_stops_train,nb_stops_total,commune_sk,loyer_m2_moy_appt_all,loyer_m2_moy_appt_t1_t2,loyer_m2_moy_appt_t3_p,loyer_m2_moy_house_all,loyer_app_m2,lien_social_count,inc_asso_refug_count,count_hopital,count_psy,count_maternite,epci_nom,bassin_de_vie,polygon,log_soc_inoc_ratio,log_pp_occup,pop_chomage_ratio,log_vac_struct_ratio,lien_social_density,inc_asso_refug_density,risque_fermeture_ratio,bpe_creches_density,log_loyer_moyen_appt_all_scaled,log_loyer_moyen_appt_t1_t2_scaled,log_loyer_moyen_appt_t3_p_scaled,log_loyer_moyen_house_all_scaled,log_vac_scaled,inc_asso_core_scaled,inc_asso_refug_scaled,inc_population_scaled,inc_pol_scaled,log_occup_scaled,youth_growth_rate,workclass_growth_rate,youth_decline_scaled,workclass_decline_scaled,log_soc_inoc_scaled,edu_classes_ferm_scaled,edu_creches_scaled,edu_petite_enfance_scaled,mob_gare_scaled,edu_maternelle_scaled,edu_elementaire_scaled,edu_college_scaled,edu_lycee_scaled,sante_hopital_scaled,sante_maternite_scaled,sante_psy_scaled,inc_services_core_scaled,socle_match_count
4338,13055,13,93,None,1.0,200054807,855393.0,0,0,0,17915.0,0.0,209.0,295.0,102.0,70.0,0.5,89080.0,496.0,203.0,191.0,NaN,1287.0,33.0,29.0,11.0,1360.0,a995b410d5e76ed56523533b47e3786a,NaN,NaN,NaN,NaN,NaN,30805.0,78.0,14.0,56.0,5.0,200054807,13055,"b'\x01\x06\x00\x00\x00\x05\x00\x00\x00\x01\x03\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00\x8eC\xff\xedB\x10+A\x9a8E3]\xd1WA\x8f(\x85\xf5O\x0b+A\n\xad\\\x93\xcd\xd0WA\x10\xe0\x9a#n\x07+A\xfcncb\x1d\xd1WA\x8d\xb5\x9db\xac\r+A>\xf7\x88e\x92\xd1WAZt\xd7*\x92\x12+A[\xadq\x96Y\xd2WA\x8eC\xff\xedB\x10+A\x9a8E3]\xd1WA\x01\x03\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00Zt\xd7*\x92\x12+A[\xadq\x96Y\xd2WA\xe67\x81\x0b \x11+A k\xa2\xdc\x1a\xd3WA\xb2\xb0\xb4\xcd\xa8\x18+A\xfd\xfc\'Ru\xd3WAZt\xd7*\x92\x12+A[\xadq\x96Y\xd2WA\x01\x03\x00\x00\x00\x01\x00\x00\x00""\x00\x00\x00l\x0c\x1bYDV+A\xbf\x18\xed=\xae\xddWAH\xaa\x91\xe2}\\+A\x1b+\xff\x8e#\xdeWA\xb4\x89\xc9\xf9\xf1j+A=\x93\x83\x0b\xa1\xdeWA\xbf\x81\xf4Vpv+A:\x16\xd8\xce\xbd\xdbWA"";\x1e\xda\xc0p+A\xbb\xf3\xcc\xd9\x1c\xd9WA\x98OG\x91\xb5x+A\xd9Y\xe4U\xbb\xd7WA\x8b\x07K7\xff}+A\xcfF\x7f2\xe2\xd6WAL\xee8\x0cA\x9c+An\x04\x9e\xad\xa7\xd7WA\x8fw\xba2-\xa3+A\xb4D\x0e\xddf\xd5WA\x96\xa5\xb0\xc3\xff\x99+A(\xda\x16\xcd\x0f\xd4WA\xe0\x01\xea\xf9\x03\x98+A\x0f\x12\xa9\xa9\xe1\xd1WA\x9dn\x81\xf5\x84\x97+A\xcfF\x8c V\xd1WA""\xf1\xcb\x95|\x9c+A\x1dh\xf8\xdfJ\xcfWA\xd6_<\x9d\xb4\x94+A\x889\xa3;j\xcdWARr\x16\x10i\x97+A\xab\xca\xc1\x93F\xcaWA_\x92K\xff\xaav+A\xf6\xba5\x17\x8f\xcbWA\x06\xa7\xdeXU_+A\xa0h~*\xd1\xcaWA.a\xe7\xcf\xccE+A\x86\x97wUC\xcbWA\xd4zP\xca\x06++A\xad\xaaa\xee\x98\xcbWA:\x99\t\x04\xc1?+A\xc4\xe5\x99MB\xcfWA\xeeepCf;+A\xac\xef\xd6\x03\x86\xd1WA\xb0T\xb4\x96\xa6<+A\xb4a\xd6Q>\xd4WA\xbaE\xb35\x80>+A\x0c\x08\xeb\xb4w\xd4WA\xde\x8c\xac""\x0e++AC\x08a\n\xd9\xd8WA\xb5iYV\x84&+A\xfa$v\xf1C\xd9WA\x9a\xf0\x15\\\\\x19+AG\x0c\xf5\xc4G\xdbWA\x80D\xc8\'\xaf\x02+A\x80\xea5\x9e\xa7\xdaWA\xb8.1\xdc!\x00+A\xf4\x19\xff\x17x\xddWA\xd3x\xd6\x8d\x84\x0e+A\x89\x07\xf0\x0eH\xdeWAW\xcd\xd2\xa1\xeb!+A\xa0\xb2vu\x9d\xdcWA\xbe\xc4|\xdf\x08-+A\x8e7P\xd3\xd9\xddWA\xbcm\xde\x0e\xae<+A\xc7\xe4\xeak\xab\xdeWA2\xdfq\x85\xe3G+A\x18-\x97\x9d\xdd\xdcWAl\x0c\x1bYDV+A\xbf\x18\xed=\xae\xddWA\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00"">^JW(+AQ\xbb\xed\x85\xa4\xd8WA\xd7_\xccy\x92(+A\x11\xde\xab\x13\x9f\xd8WA\x10\\\xfa\xfd33+A6\x82\xa2\xf1\x98\xd6WAtF\xd9\xf1\xe45+A$\x87\x91\xb2\xf4\xd5WA"">^JW(+AQ\xbb\xed\x85\xa4\xd8WA\x01\x03\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00&\xc2w\xae\x08$+A\xb4\xac\xa4\xfc\t\xd9WAKP)\xac\xe9\'+A*\xda\xfd@\xba\xd8WA"">^JW(+AQ\xbb\xed\x85\xa4\xd8WA&\xc2w\xae\x08$+A\xb4\xac\xa4\xfc\t\xd9WA'",0.017362,0.616825,0.0,0.044771,36.012688,0.091186,203.0,0.223289,NaN,NaN,NaN,NaN,0.447712,0.256286,0.157442,1.0,0.5,0.005358,-0.028996,0.014528,0.644981,0.427360,0.173616,1.0,0.152087,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3
27054,69123,69,84,None,1.0,200046977,500715.0,0,0,0,6658.0,0.0,64.0,141.0,52.0,62.0,0.5,43446.0,196.0,44.0,178.0,NaN,444.0,48.0,29.0,6.0,527.0,3dd8d2d749b7b1856a095830e996bcc6,NaN,NaN,NaN,NaN,NaN,24027.0,81.0,7.0,50.0,3.0,200046977,69123,"b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x18\x00\x00\x00\xc9v5XC\xd7)A\x8dN\x94\xe7\x15\xdbXAc\xf9\xb5\xc8\xed\xc0)A\x0b\xdd\x80\x98B\xdaXA\\\xb0\x1b@R\xc0)A\xed\t\xe8#B\xdaXA\xd1\xd3\x98\xef\xae\xbb)A\x8es\xa42\r\xd9XA\x9a8vJO\xaf)Al%\xc8|5\xdaXA\xb6.\x19K\xef\xad)A\xfb\xf4^\xa2\x12\xdbXA[\xda\xb8J\xe3\xac)A~q\x12\xcet\xddXA\xe2\xf0\x0f#\xdf\xa9)A\x7fx\xba\xd0V\xddXAi\xad\xd2:\xa3\x94)A\x8a\x9e\x95\x97+\xddXA8\xd5\x95\x8b\xea\x90)A\xf5\xcbc\xfe\x97\xddXA\xdc\xb0\xde\xe8\xc4\x99)Anl\xd5b\x07\xdfXA\x9b\x0b5\x99\xa0\x9c)A""\xf4:c\x03\xe0XA\xff\xa7Z\x92\xdd\x99)AM\xc1|x\xd9\xe1XAX*;%R\xa2)A(\x93\x80)\x17\xe2XA@u\xbc\xa2\xe3\xab)A\xc1\xbbO\x92\xe0\xe2XA+\x8a+\x05<\xb7)A6O\xfb\xe7\xe2\xe3XA\xd4\x8d\xdc\xdd\xbd\xb9)A3\xf6\xbf\xb1u\xe3XAV\x8c7\xfd\xac\xac)A\xf2\x1b\x968\xe7\xe1XA\xb4\t\xc0\nv\xbb)A\xae[\xf9\xb8\xc0\xe0XA\x1d\xb8\xc7d\x9d\xc5)A\x18\x10M\x81\xa6\xe1XA\xa5\x0e~\xc6\'\xcc)A\x9e\r\xbc\xba,\xdfXA\\\x8f\xde\xd8a\xdd)A\xd85lh\x08\xdeXA\xd7\xd9\x9c\xba\x07\xda)A\x15 \x03\x0b\x81\xdcXA\xc9v5XC\xd7)A\x8dN\x94\xe7\x15\xdbXA'",0.013051,0.606272,0.0,0.025397,47.985382,0.161769,44.0,0.355492,NaN,NaN,NaN,NaN,0.253973,0.341490,0.279310,1.0,0.5,0.000000,-0.026718,0.017617,0.633588,0.411913,0.130506,1.0,0.242132,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3
29218,75056,75,11,None,1.0,200054781,2229621.0,0,0,0,36205.0,0.0,316.0,488.0,215.0,178.0,0.5,138459.0,727.0,272.0,805.0,NaN,896.0,60.0,245.0,33.0,1234.0,2fc10af7411f347306ae1ace568e8a6e,NaN,NaN,NaN,NaN,NaN,112179.0,428.0,54.0,115.0,15.0,200054781,75056,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00#\x00\x00\x00b/\x98\xba\x9d\xe9#A7\x1f\xc5\x17\x072ZA\xfc\x1e6)\xa4\xf1#A\x88\xff\x15\xcf 2ZA\x9c&\xe4\x9e\xee\xf3#A\xb7\xaf\xe08 2ZA\x95\x05&\x96\xce\xfe#An+\xd0\xaf\x012ZA\x0e\x9e\xe1%v\x04$A\xcaT\xf3}\xce0ZA\xfc,I\x08B\x0b$A\xf3\xc2\x18@\x7f/ZA\xab\xa0\xe8!_\x0c$A\xfe\x04)\xfc\xf3.ZAG\x0c\xce\xdef\r$A\x88\xf3|X\xff,ZAbc\xf0\xbf\xef\r$A6\xaf/lX,ZA\xf1\x99\xd3u\xec\r$A\xbdN\xb9\xd3 ,ZApH\x10\xa7\xc5\x14$Av\xf4\x14:\x94+ZA\xe2\x92\xa1\x03B $A\xf3\xbd\x1f\x02\xe5+ZA\xea\xb4\xbf\xc3\x1d+$A\x91d\xa6\xd3;+ZA\xf0\x85\x88kw*$A(M@\x95\xd2)ZA\t\xd7\xf3\x1f\x8d'$A\x81w\x1d\xd4\xf4(ZAm\xce\xff\xf8\x11\x10$A\x97\xa8\xb4\xf1\xa0)ZA\xa0+\xcbZ\xe0\xfe#A\xd3\xd7\t\xb0\xdc)ZA8\xba\xfa\xe2\xe4\xef#A\xa3\x0f\xa9{\xca(ZA\xe18\xd5\x07N\xeb#A\r\xd2a\xac\xcb(ZA\xbd\x80\x94\xbfk\xe4#A\xb8?\x9b|\xcd(ZA\x19G\x80Y\x8b\xdd#A\xfc5_!\xeb(ZA\x8c\xf7\xf4\xa4A\xd3#A\xf3\xc4\x7f\xf2x)ZA\x8f\x9b\xb0\xa3\xd2\xcb#A\xda\xcb3n\xce)ZA\xed\xe4\xd2\xad\xf6\xc4#AC\xec\x9e\xc9#*ZA\xa3\xd2\xa7\xc3\x19\xb6#A\xe0\xc3\xbb\xf1\xce*ZA+\xad(\x1a\xe8\x9f#A0\xc1.\xbe\x01-ZA\x88\xd88\x7f\x18\xa1#A\x0e>\xb1^\x8c-ZAi\x10t\x87\x9e\xa4#A\x9b\x7f\x84E\xa1.ZA\xb4\x7fHF\xb3\xac#A\x9bg\xe4aa/ZA\x1a\x81\x8f\xb24\xc0#A\xa2\x928\xf5\xae/ZA9\xe5\xda\x86\x8d\xc2#A\xcb\xc9\xfb\xe0p0ZAr\xdb\x99b\x12\xce#A\xfb2\x1b\xfdK1ZA\xb39\xcb\x0fH\xd7#A\x8a[\xcd9\xf01ZA\xa8\xe2\xcd%\x04\xdd#A\x9c\xad9u\n2ZAb/\x98\xba\x9d\xe9#A7\x1f\xc5\x17\x072ZA""",0.012759,0.525126,0.0,0.032158,50.313034,0.191961,272.0,0.361048,NaN,NaN,NaN,NaN,0.321575,0.358055,0.331439,1.0,0.5,0.000000,-0.107170,-0.052628,1.000000,0.763138,0.127593,1.0,0.245917,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3

In [4]:
odis_communes.head(1)

,codgeo,dep_code,reg_code,commune,plm,epci_code,population,pop_active,pop_employes,pop_chomeurs,log_priv_vacant_plus_2ans,edu_pe_tx_couverture,edu_maternelle_ct,edu_elementaire_ct,edu_college_ct,edu_lycee_ct,pol_num,total_eleves,ecoles_count,risky_schools_count,bpe_creches_count,heb_centres_heb_cap,heb_foyers_count,heb_loc_iml_count,heb_habitant_count,gare_count,nb_stops_bus,nb_stops_tram,nb_stops_metro,nb_stops_train,nb_stops_total,inc_rna_Culturelle_count,inc_rna_Emploi/IAE_count,inc_rna_FLE/Alpha_count,inc_rna_Juridique_count,inc_rna_Logement_count,inc_rna_Numérique_count,inc_rna_Santé/Psy_count,heb_asso_refug_count,lien_social_count,commune_sk,loyer_m2_moy_appt_all,loyer_m2_moy_appt_t1_t2,loyer_m2_moy_appt_t3_p,loyer_m2_moy_house_all,loyer_app_m2,count_hopital,count_psy,count_maternite,epci_nom,bassin_de_vie,polygon,log_soc_inoc_ratio,log_pp_occup,pop_chomage_ratio,log_vac_struct_ratio,lien_social_density,inc_siae_density,risque_fermeture_ratio,bpe_creches_density,heb_centres_heb_density,heb_asso_refug_density,heb_foyers_density,heb_loc_iml_density,heb_habitant_density,log_loyer_moyen_appt_all_scaled,log_loyer_moyen_appt_t1_t2_scaled,log_loyer_moyen_appt_t3_p_scaled,log_loyer_moyen_house_all_scaled,log_vac_scaled,inc_asso_core_scaled,heb_asso_refug_scaled,inc_siae_density_scaled,inc_population_scaled,inc_pol_scaled,log_occup_scaled,heb_centres_heb_scaled,heb_foyers_scaled,heb_loc_iml_scaled,heb_asso_habitant_scaled,youth_growth_rate,workclass_growth_rate,youth_decline_scaled,workclass_decline_scaled,log_soc_inoc_scaled,edu_classes_ferm_scaled,edu_creches_scaled,edu_petite_enfance_scaled,mob_gare_scaled,edu_maternelle_scaled,edu_elementaire_scaled,edu_college_scaled,edu_lycee_scaled,sante_hopital_scaled,sante_maternite_scaled,sante_psy_scaled,inc_services_core_scaled,socle_match_count
0,01001,01,84,None,NaN,200069193,767.0,452,442,10,0.0,0.0,0.0,1.0,0.0,0.0,0.5,85.0,1.0,0.0,0.0,0.0,0.0,0,0,NaN,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0,0,0,0,1,1e685a8cce29c9bfbf747b9c5021e9c7,NaN,NaN,NaN,NaN,11.924962,0.0,0.0,0.0,200069193,01093,"b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x08\x00\x00\x00\xb6d\xe005\xf9)A\x17\xccZ\x84\x82\tYA[\xe8\xfb\x0f\x9e\xe6)A+i\x89o\xdf\x05YA\x89Q\xa4\xe4,\xdc)Aw\xa2\x0bB\xd1\x06YA\xe8\x10\x8ai\xf3\xd7)A\xe9\xe3FY\xf3\tYA|<\xa1\xee\x17\xd9)A\xdd\\\x0c\x8bG\nYAu\xc2\xba`\x80\xe9)A\x81w\xa1D\xb7\x0cYA|\x19\xcf a\xec)A\xd0re\x8fV\nYA\xb6d\xe005\xf9)A\x17\xccZ\x84\x82\tYA'",0.03125,0.9375,0.022124,0.0,1.303781,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.151239,0.0,0.0,0.0,0.5,0.837763,0.0,0.0,0.0,0.0,0.006211,0.09699,0.468944,0.01505,0.3125,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.666667,2

## POIS

In [52]:
odis_pois.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275393 entries, 0 to 275392
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        275393 non-null  object
 1   name      275393 non-null  object
 2   type      275393 non-null  category
 3   category  275393 non-null  category
 4   lat       275097 non-null  float32
 5   lon       275097 non-null  float32
 6   codgeo    275393 non-null  category
dtypes: category(3), float32(2), object(2)
memory usage: 7.7+ MB

In [14]:
odis_pois.category.unique()

['education', 'sante', 'incl_services']
Categories (3, object): ['education', 'incl_services', 'sante']

In [16]:
odis_pois[
    (odis_pois.category == "incl_services") &
    (odis_pois.type == "logement-hebergement--rechercher-une-solution-dhebergement-temporaire") &
    (odis_pois.codgeo == "33063")
]

,id,name,type,category,lat,lon,codgeo
38865,9028c6962d965a66c766f5cb66a50ebf,L'AVANCE LOCA-PASS®,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
44199,69473a6afafd7cd1753fd5b52b2a1b55,Logement temporaire,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
50701,82feec617449cee11401242262dd1afe,Louer pour l'Emploi,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
54137,50138e3aa57706d80c29f3ee6288af2d,L’AIDE MOBILI-JEUNE®,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
57468,881b33ad7dd424967193f72b6f530ce9,Prêt AGRI-TRAVAUX,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
79434,1f8d9af20566e85f16ed3c8f41664869,Le service accompagnement social,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
82854,b2d0e4a4b3591a3e67d369d53cb37cd4,Le Prêt travaux d'amélioration,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
94437,5cb1f23f10a9a4f9b56b00c2817afe05,Prêt AGRI-AGRANDISSEMENT,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
120951,dc01b1a813adfa3c1c47d159a5b2d22f,Le Prêt travaux d'amélioration de la performance énergétique,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
127808,f61f5a64fdb29c204ffce3267edfd5f4,Le prêt travaux d'adaptation du logement au handicap,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
139397,02a5e80f4fd607c118af7957bbd772e6,Logement intermédiaire,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
164253,1ba0e88f3cf6279ebce78d9345c013bf,Action Coeur de Ville\r,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
169773,b19671ebe481ae497b08a279fe0970f0,Le prêt Accession,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
176028,ed608e6d566d1fc19b01df134b724597,AVANCE AGRI-LOCA-PASS,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
180386,6aa4c8a215c73d959d0f6a5121ddda12,Aide AGRI-MOBILI-JEUNE,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
195273,2831d4a7aa2bbfe8cb2db4db0dad11e8,Logement privé,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
209607,d2d2978c5fcaf69ff3f139733d5e068c,Garantie Visale,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
212941,202bdd11e3314cbdeb20d6871c6f722f,Prêt AGRI-ACCESSION,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
234010,74d4107b30bed7ef9f274fd8059196dc,Le Conseil en financement et en accession,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
253034,fd00d44f3fce26a6f870e22afe35dc17,Logement social,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
255509,205df4ceac2c1b11cc6be4cf31e89499,Aide aux saisonniers agricoles,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063
260528,e868c2e3eaeece25074f3979b14680b5,Le prêt travaux copropriétés dégradées,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,incl_services,44.821709,-0.547361,33063

In [32]:
old_odis = pd.read_parquet('../data/odis_june_2025_jacques.parquet')

## Referentiels

In [5]:
odis_referentiels.key.unique()

array(['formation_codes', 'inclusion_services', 'waldec_codes',
       'communes', 'bassins_de_vie', 'regions', 'departements',
       'rome_codes'], dtype=object)

In [60]:
# odis_referentiels[(odis_referentiels.key == "inclusion_services")].code.unique()
# odis_referentiels[(odis_referentiels.key == "waldec_codes") & (odis_referentiels.code.str.contains("9000"))]
# odis_referentiels[(odis_referentiels.key == "waldec_codes") & (odis_referentiels.label.str.contains("action"))]
odis_referentiels[(odis_referentiels.key == "waldec_codes")]

,key,code,label,reg_code
161,waldec_codes,18010,établissements et services pour adolescents en difficulté,None
162,waldec_codes,18015,"établissements et services pour enfants handicapés, établissements et services pour adultes handicapés, y compris les CAT (centres d'aide par le travail).",None
163,waldec_codes,11400,activités de plein air (dont saut à l'élastique),None
164,waldec_codes,34240,"syndicats d'initiative, offices de tourisme, salons du tourisme",None
165,waldec_codes,9030,comités des fêtes,None
...,...,...,...,...
453,waldec_codes,11045,"danse sportive (danse sportive, hip hop, claquettes)",None
454,waldec_codes,11065,basket-ball,None
455,waldec_codes,11105,"gymnastique (gymnastique, gymnastique d.entretien, éducation physique, yoga), aérobic",None
456,waldec_codes,11145,"sports de combat (boxe, kick box, boxe thaï, lutte)",None
457,waldec_codes,11160,"sports mécaniques (sport automobile, moto, trial)",None

In [34]:
odis_refugee_associations[odis_refugee_associations.codgeo.str.contains("11069", na=False)].head()

NameError: name 'odis_refugee_associations' is not defined

In [ ]:
odis_finess[(odis_finess['Departement'] == '13') & (odis_finess['Commune'] == '103')][['LibelleCategorie','nofinesset']].groupby('LibelleCategorie').count().sort_values(by='nofinesset', ascending=False)

                                                              nofinesset
LibelleCategorie
Pharmacie d'Officine                                                  14
Service autonomie aide (SAA)                                          10
Laboratoire de Biologie Médicale                                       6
Etablissement d'hébergement pour personnes âgées dépendantes           5
Institut Médico-Educatif (I.M.E.)                                      4
Service de Soins Infirmiers A Domicile (S.S.I.A.D)                     3
Centre Hospitalier Spécialisé lutte Maladies Mentales                  3
Centre Hébergement & Réinsertion Sociale (C.H.R.S.)                    3
Autre Résidence Sociale (hors Maison Relais, Pension de Fami           3
Service d'Éducation Spéciale et de Soins à Domicile                    2
Etablissement Consultation Protection Infantile                        2
Etab.Accueil Non Médicalisé pour personnes handicapées                 2
Ecoles Formant aux Professions Sanitaires                              2
Etablissement et Service d'Aide par le Travail (E.S.A.T.)              2
Centre de Santé                                                        2
Structure Dispensatrice à domicile d'Oxygène à usage médical           2
Maison de santé (L.6223-3)                                             1
Maison d'Enfants à Caractère Social                                    1
Résidences autonomie                                                   1
Service d'accompagnement médico-social adultes handicapés              1
Foyer de l'Enfance                                                     1
Foyer de Jeunes Travailleurs (résidence sociale ou non)                1
Foyer d'Action Educative (F.A.E.)                                      1
Foyer Hébergement Enfants et Adolescents Handicapés                    1
Autre Centre d'Accueil                                                 1
Etablissement de santé privé autorisé en SSR                           1
Etablissement de Soins Longue Durée                                    1
Etablissement de Soins Chirurgicaux                                    1
Autre Etablissement Loi Hospitalière                                   1
Etab.Acc.Médicalisé en tout ou partie personnes handicapées            1
Entreprise adaptée                                                     1
Ecoles Formant aux Professions Sociales                                1
Communautés professionnelles territoriales de santé (CPTS)             1
Centre de vaccination internationale                                   1
Centre de dialyse                                                      1
Centre d'Accueil Thérapeutique à temps partiel (C.A.T.T.P.)            1
Centre Médico-Psychologique (C.M.P.)                                   1
Centre Hospitalier (C.H.)                                              1
Centre Action Médico-Sociale Précoce (C.A.M.S.P.)                      1
Centre Accueil Demandeurs Asile (C.A.D.A.)                             1
Structure d'Alternative à la dialyse en centre                         1

## Asso Mini

In [53]:
WALDEC_CORE_INCLUSION = [
    # --- SOCIAL & ENTRAIDE ---
    # "009",    # ACTION SOCIOCULTURELLE (Tout le niveau 1 : Centres sociaux, MJC...)
    "015070", # Apprentissage de langues, alphabétisation (CRITIQUE)
    # "015095", # Soutien scolaire
    # "019016", # Aide à l'insertion des jeunes
    # "019020", # Aide aux chômeurs
    "019025", # Aide aux réfugiés et aux immigrés (CRITIQUE)
    "020",    # ASSOCIATIONS CARITATIVES, HUMANITAIRES (Tout le niveau 1 : Secours, Alimentaire...)
    "024",    # Entraide et solidarité
    # "021",    # SERVICES FAMILIAUX (Crèches, Halte-garderie...)
    # "014030", # Associations de parents d'élèves (Indicateur de vie scolaire)
    # "014040", # Associations de locataires (Indicateur de vie de quartier)
    # "024020", # Garde d'enfants, crèches parentales
]

In [55]:
odis_asso_mini.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153186 entries, 0 to 153185
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id           153186 non-null  object
 1   codgeo       153186 non-null  object
 2   waldec_code  153186 non-null  object
 3   name         153135 non-null  object
 4   description  153186 non-null  object
dtypes: object(5)
memory usage: 5.8+ MB

In [26]:
odis_asso_mini.head()

,id,codgeo,waldec_code,name,description
0,W431000057,43132,020015,LARBRE A COEURS,"organisation des manifestations caritatives comme le telethon, la marche adot43, adapei"
1,W431000067,43264,019040,LES TAMAYAS,"louverture et la gestion dun lieu de vie, sis a villeneuve dallier, accueillant des adolescents et pre-adolescents filles et garcons en difficultes, confies par decision de justice ou par les organismes departementaux."
2,W431000184,43040,020020,ROTARY CLUB BRIOUDE-LAFAYETTE,"encourager et cultiver lideal de servir, le developpement des relations personnelles damour entre ses membres en vue de leur fournir des occasions de servir linteret general, lobservation des regles de probite et de delicatesse dans lexercice de leur"
3,W431000217,43040,019020,REAGIR 43,favoriser linsertion sociales et professionnelle des personnes en difficulte par lexercice dune activite professionnelle
4,W431000240,43118,020015,INIMA,projets humanitaires.

In [28]:
odis_asso_mini[odis_asso_mini['waldec_code'] == 'W442024754']

Empty DataFrame
Columns: [id, codgeo, waldec_code, name, description]
Index: []

## RNA Full

In [29]:
asso_full = pd.read_parquet("../pipeline/cache/raw/associations.parquet")

In [62]:
asso_full[asso_full.position == 'A'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1903423 entries, 0 to 2215246
Data columns (total 39 columns):
 #   Column           Dtype
---  ------           -----
 0   id               object
 1   id_ex            object
 2   siret            object
 3   rup_mi           object
 4   gestion          object
 5   date_creat       object
 6   date_decla       object
 7   date_publi       object
 8   date_disso       object
 9   nature           object
 10  groupement       object
 11  titre            object
 12  titre_court      object
 13  objet            object
 14  objet_social1    object
 15  objet_social2    object
 16  adrs_complement  object
 17  adrs_numvoie     object
 18  adrs_repetition  object
 19  adrs_typevoie    object
 20  adrs_libvoie     object
 21  adrs_distrib     object
 22  adrs_codeinsee   object
 23  adrs_codepostal  object
 24  adrs_libcommune  object
 25  adrg_declarant   object
 26  adrg_complemid   object
 27  adrg_complemgeo  object
 28  adrg_libvoie     object
 29  adrg_distrib     object
 30  adrg_codepostal  object
 31  adrg_achemine    object
 32  adrg_pays        object
 33  dir_civilite     object
 34  siteweb          object
 35  publiweb         object
 36  observation      object
 37  position         object
 38  maj_time         object
dtypes: object(39)
memory usage: 580.9+ MB

In [53]:
asso_full[asso_full['id'] == 'W751267275']

,id,id_ex,siret,rup_mi,gestion,date_creat,date_decla,date_publi,date_disso,nature,groupement,titre,titre_court,objet,objet_social1,objet_social2,adrs_complement,adrs_numvoie,adrs_repetition,adrs_typevoie,adrs_libvoie,adrs_distrib,adrs_codeinsee,adrs_codepostal,adrs_libcommune,adrg_declarant,adrg_complemid,adrg_complemgeo,adrg_libvoie,adrg_distrib,adrg_codepostal,adrg_achemine,adrg_pays,dir_civilite,siteweb,publiweb,observation,position,maj_time
1390456,W751267275,None,None,None,751P,2022-10-17,2023-10-10,2022-10-25,0001-01-01,D,S,JACCUEILLE,JACCUEILLE,"promouvoir laccueil chez les particuliers et la cohabitation entre citoyen ne s du monde entier au sein des foyers, et toutes les solutions de logement innovantes permettant la rencontre et lechange interculturel faire emerger, dans les pays ou lassociation agit, une culture de laccueil chez lhabitant creer des espaces et des moments de vivre-ensemble, deconstruire les prejuges sur la migration et lasile, favoriser lepanouissement des nouveaux et nouvelles arrivant e s dans leur societe daccueil et construire, chez les foyers accueillants et leur reseau social, ouverture et empathie, pour faire advenir une societe plus inclusive",009000,000000,None,50,None,RUE,de Montreuil,None,75111,75011,Paris,None,None,None,50 RUE DE MONTREUIL,None,75011,PARIS 11,FRANCE,PM,http:www.jaccueille.fr,0,None,A,2024-04-10 18:05:38

In [64]:
# Cat Prioritaire
# 3000	DÉFENSE DE DROITS FONDAMENTAUX, ACTIVITÉS CIVIQUES
# 9000	ACTION SOCIOCULTURELLE
# 18000	SERVICES ET ÉTABLISSEMENTS MÉDICO-SOCIAUX
# 19000	INTERVENTIONS SOCIALES
# 20000	ASSOCIATIONS CARITATIVES, HUMANITAIRES, AIDE AU DÉVELOPPEMENT, DÉVELOPPEMENT DU BÉNÉVOLAT
# 21000	SERVICES FAMILIAUX, SERVICES AUX PERSONNES ÂGÉES
# 32000	LOGEMENT

# Cat Secondaire
# 6000	CULTURE, PRATIQUES D'ACTIVITÉS ARTISTIQUES, PRATIQUES CULTURELLES
# 7000	CLUBS DE LOISIRS, RELATIONS
# 10000	PRÉSERVATION DU PATRIMOINE
# 11000	SPORTS, ACTIVITÉS DE PLEIN AIR
# 13000	CHASSE PÊCHE
# 14000	AMICALES, GROUPEMENTS AFFINITAIRES, GROUPEMENTS D'ENTRAIDE (HORS DÉFENSE DE DROITS FONDAMENTAUX)
# 30000	AIDE À L'EMPLOI, DÉVELOPPEMENT LOCAL, PROMOTION DE SOLIDARITÉS ÉCONOMIQUES, VIE LOCALE
# 40000	ACTIVITÉS RELIGIEUSES, SPIRITUELLES OU PHILOSOPHIQUES
# 50000	DOMAINES DIVERS, DOMAINES DE NOMENCLATURE SITADELE À RECLASSER


waldec_prefixes_prio = ["003", "009", "018", "019", "020", "032", "009"]
waldec_prefixes_sec = ["006", "007", "010", "011", "013", "014", "030", "040","050"]

prefix_counts = {
    prefix: len(asso_full[
        asso_full["objet_social1"].str.startswith(prefix, na=False) | 
        asso_full["objet_social2"].str.startswith(prefix, na=False)
    ])
    for prefix in waldec_prefixes_sec
}
result_sec = pd.Series(prefix_counts)

In [69]:
result_prio.head(10)

003     30300
009    144049
018     17257
019     60547
020     94484
032     17717
dtype: int64

In [46]:
waldec_prefixes = ["003", "018", "019", "020"] #, "032"]
asso_full[
    (asso_full['objet_social1'] == '032000')
    & (asso_full['objet_social2'].str[:3].isin(waldec_prefixes)) 
    # & (asso_full['adrs_codeinsee'] == '33063')
    ].head(20)

,id,id_ex,siret,rup_mi,gestion,date_creat,date_decla,date_publi,date_disso,nature,groupement,titre,titre_court,objet,objet_social1,objet_social2,adrs_complement,adrs_numvoie,adrs_repetition,adrs_typevoie,adrs_libvoie,adrs_distrib,adrs_codeinsee,adrs_codepostal,adrs_libcommune,adrg_declarant,adrg_complemid,adrg_complemgeo,adrg_libvoie,adrg_distrib,adrg_codepostal,adrg_achemine,adrg_pays,dir_civilite,siteweb,publiweb,observation,position,maj_time
82437,W012014984,None,None,None,012P,2020-06-04,2020-06-04,2020-10-24,0001-01-01,D,S,LES GITES DE SAINT EXUPERY,LES GITES DE SAINT EXUPERY,"Organiser au profit de ses membres des activites de logement meuble, ainsi que tous moyens susceptibles de concourir a la realisation de son objet social comme le prevoit larticle L.442-7 du Code du Commerce il est egalement prevu de loger a titre gratuit, ou a titre peu onereux, des personnes defavorisees, handicapees voire sans logement.",032000,019004,None,46,None,RUE,de lEglise,None,01027,01360,Balan,None,None,None,46 rue de lEglise,None,01360,Balan,FRANCE,PF,None,0,None,A,2020-10-24 12:45:07
90684,W9C1002169,None,None,None,9C1P,2011-07-11,2011-07-11,2011-08-20,0001-01-01,D,S,FEDERATION DROIT AU LOGEMENT GUYANE BLOUBLOU FINI DAL GUYANE,DAL GUYANE,"dunir, organiser et soutenir les associations et les collectifs membres de lassociation et leurs membres agissant pour la defense du droit au logement et a la terre des familles et personnes, confrontees a des difficultes notamment economiques, a toutes formes de discrimination, y compris des discriminations fondees sur lorigine ou la situation sociale, ou leur maintien dans un logement ou habitat decent, durable et choisi partout en Guyane, de lutter contre les marchands de sommeil les speculateurs immobiliers ou fonciers et les profiteurs du logement, dagir en faveur des locataires, des occupants sans titres, des proprietaires occupants des sans logis, des mal loges ou de toute personne menacee de perdre son logement, et de les federer dans des collectifs ou des associations ou des sections. Aucun bailleur prive ne peut-etre defendue par lassociation, dagir contre la marchandisationprivatisation du logement social et pour la defense de ses locataires, de representer ses adherents aupres des instances et institutions guyanaises, politiques, sociales, administratives et judiciaires, tout en menant des actions de solidarites nationale ou internationale, delaborer, defendre et faire appliquer des propositions pour ameliorer les politiques du logement, ou a un logement accessible, decent, choisi et durable, du developpement durable et de la sante de ses occupantes soit mis en oeuvre, pour toutes et tous, federer toutes associations ou collectifs, ayant pour objet principal ou annexe la defense du droit au logement et a la terre des familles et personnes confrontees a des difficultes ou a des discriminations, ainsi que toute action citoyenne : culturelle, sportive, sociale ou solidaire",032000,019004,None,599,None,None,Cogneau Lamirande,None,97307,97351,Matoury,None,None,None,599 Cogneau Lamirande,None,97351,Matoury,FRANCE,PM,None,0,None,A,2011-08-22 19:12:08
92857,W9C1004446,None,None,None,9C1P,2017-12-06,2017-12-06,2017-12-23,0001-01-01,D,S,LA MAILLE,LA MAILLE,"proposer une ingenierie sociale, administrative et financiere aux proprietaires prives, dans le cadre de lamelioration des conditions dhabitat r Organiser des campagnes dinformations sur les aides a lhabitat mobilisables aupres des financeurs publics r Offrir des missions de mediation, conciliation aupres des familles en situation precaires r Realiser pour le compte de tiers, levaluation des besoins des personnes agees, en cessation dactivites ou en situation de handicap, pour le maintien a domicile, dans le cadre du bien-etre et bien vieillir r Proposer un accompagnement social et professionnel, des familles en voix dintegration, dans le cadre de la lutte contre lexclusion r Realiser pour le compte de tiers, a letranger, un accompagnement social et professionnel, des familles beneficiaires de lAide au Retour Volontaire ARV",032000,019004,None,19,None,RUEL1,DU CANAL DE L EST,None,97302,97300,Cayenne,None,None,None,19 RUELLE DU CANAL DE L ES,None,97300,CAYENNE,France,RE,None,0,None,A,2017-12-23 12:45:10
201269,W594003671,None,None,None,594S,2008-05-26,2015-10-16,2008-06-07,0001-01-01,D,S,LESPOIR,LESPOIR,"aider les gens dans le besoin fournitures diverses assister les gens dans leurs demarches administratives, emploi, etc... organisation dun repas de Noel pour les plus demunis",032000,003000,appartement 46,20,,RUE,de la Verrerie,None,59183,59140,Dunkerque,None,APPARTEMENT 46,None,20 RUE DE LA VERRERIE,None,59140,DUNKERQUE,FRANCE,PM,None,1,None,A,2015-10-26 07:55:23
260474,W401001871,0401001554,None,None,401S,1974-02-27,2024-11-15,1974-03-18,0001-01-01,D,S,LES PEUPLIERS,LES PEUPLIERS,oeuvrer pour les residents et le personnel de lehpad et de la residence des luys en accord avec la direction promouvoir lanimation et le developpement favoriser la rencontre et la preservation de la socialisation ameliorer la qualite de vie au travail elle est egalement a destination des personnes du pole de proximite,032000,019000,EHPAD Les Peupliers,170,None,IMP,des Peupliers,None,40002,40330,Amou,None,None,None,170 IMPASSE DES PEUPLIERS,None,40330,AMOU,FRANCE,PF,None,0,reprise auto => date publication creation au JO a verifier,A,2024-11-19 10:08:42
307319,W171000397,None,None,None,171S,2006-07-27,2006-07-27,0001-01-01,0001-01-01,D,S,LA CHARENTAISE A PETANQUE,LA CHARENTAISE A PETANQUE,"Le developpement culturel, la promotion agricole, artisanale et industrielle du canton de Mirambeau et du Port de Vitrezay",032000,019000,None,None,,None,Mairie,None,17236,17150,Mirambeau,None,None,None,Mairie,None,17150,MIRAMBEAU,FRANCE,PM,None,0,None,A,2008-08-11 18:04:30
325146,W173010818,None,None,None,173P,2024-11-20,2024-11-20,2024-11-26,0001-01-01,D,S,LARBRE DE VIE 17,LARBRE DE VIE 17,"gerer un lieu de vie et daccueil pour des jeunes en difficultes, un chantier dinsertion et dautres lieux daccueils et dhebergements",032000,019000,None,2,None,IMP,des Ajoncs,None,17291,17138,Puilboreau,None,None,None,2 impasse des Ajoncs,None,17138,Puilboreau,FRANCE,PF,None,0,None,A,2024-11-26 10:11:06
325338,W173011012,None,None,None,173P,2025-06-16,2025-06-16,2025-06-24,0001-01-01,D,S,UN PETIT TOIT,UN PETIT TOIT,"fournir un toit durable dans un eco-lieu a des personnes sans domicile ou ne habitat precaire, insalubre, permettre en autre et prioritairement a des personnes momentanement en difficulte davoir acces a une alimentation variee et de qualite en achetant des denrees alimentaires et des produits locaux etou du quotidien a des prix preferentiels, proposer un camping atypique et solidaire, mettre en oeuvre un potager collaboratif et eventuellement quelques animaux delevages, rendre toutes les installations le plus autonome possible en energie chauffage, electricite proposer et mettre en oeuvre du tri selectif et du compostage, favoriser et accompagner des projets collaboratifs a destination dinsertion ou de reinsertion sociale ou professionnelle, proposer et presenter des activites mettant exemplaires visant le respect ou lentretien de lenvironnement du vivant de lartisanat de lautonomie ou meme de leveil par lart de lechange, proposer une ressourcerie visant a rehabiliter",032000,019000,None,None,None,RTE,du Pont de Pierre,La petite ecurie,17010,17690,Angoulins,None,None,None,route du Pont de Pierre,La petite ecurie,17690,Angoulins,FRANCE,PM,None,0,None,A,2025-06-25 10:05:18
386132,W793005425,None,None,None,793S,2025-05-16,2025-05-16,2025-05-20,0001-01-01,D,S,CENT POUR UN EN GATINE,CENT POUR UN EN GATINE,"Lassociation a pour objet toute forme daction de solidarite contribuant au logement provisoire de personnes sans abri, en cas dinsuffisance de places disponibles ou de carence dans les dispositifs publics dhebergement.r Lassociation contribue egalement, avec tous les partenaires necessaires, a laccompagnement de ces personnes dans les demarches administratives et dans la vie quotidienne, en attendant leur autonomie.Lassociation recherche les offres dhebergement a titre gratuit, onereux ou dinitiatives des collectivites locales et prends a sa charge tout ou partie du coup des logements loyer, charges et assurances afferentes pour une periode determinee en accord avec le proprietaire et chaque beneficiaire. Pour ce faire, lassociation assure la collecte des fonds necessaires et la relation avec les proprietaires. Lassociation peut aussi etre amenee a aider financierement ces personnes. Lassociation ne poursuit aucun but lucratif, religieux ou politique.",032000,019000,CCAS Parthenay,10,None,RUE,de la citadelle,None,79202,79200,Parthenay,None,CCAS Parthenay,None,10 rue de la citadelle,None,79200,Parthenay,FRANCE,PF,None,0,None,A,2025-05-20 18:05:33
478436,W332034809,None,None,None,332P,2024-05-17,2024-05-17,2024-05-28,0001-01-01,D,S,MEDITERRANEE,MEDITERRANEE,porter une action en faveur de lhebergement des personnes defavorisees par le biais notamment dun mecanisme dintermediation locative,032000,020005,None,18,None,AV,de la Somme,None,33281,33700,Merignac,None,None,None,18 avenue de la Somme,None,33700,Merignac,FRANCE,PM,None,0,None,A,2024-05-28 10:08:21
513636,W9G2009212,9712002766,None,None,9G2S,1989-09-14,2019-08-09,1989-12-13,0001-01-01,D,S,ASSOCIATION DES JEUNES ACTIFS DE FFRENCH,ASSOCIATION DES JEUNES ACTIFS DE FF...,"assurer le bien-etre des proprietaires en organisant la defense de leurs interets sur toutes les questions relatives aux proble- mes de lhidbitat et de lurbanisme : defense, sante publique, activites culturelles, artistiques, sportives, education",032000,020000,None,None,None,None,None,None,97128,97180,Sainte-Anne,None,None,None,None,None,97180,STE ANNE,FRANCE,PM,None,0,Reprise => date ag=0000-00-00 derniere date publication enregistree :1989-12-13,A,2019-08-09 18:01:53
725434,W9R1000620,None,None,None,9R3S,2005-08-16,2016-05-18,2005-09-10,0001-01-01,D,S,FEDERATION DE LA CNL DE LA REGION REUNION 97400,FEDERATION DE LA CNL DE LA REGION R...,"Prendre la defense ds interets individuels et collectifs de ses adherentsr mener laction necessaire a la realisation de tout ce qui a trait a la definition dune politique sociale de lhabitat que ce soit les conditions de location, daccession a la propriete familiale et des problemes denergie, dhygiene, de securite, dactivites sociales, culturelles et de loisirsr Agir pour orienter les definitions durbaniseme et denvironnement dans le cadre dune amelioration et dune protecti",032000,019000,Immeuble Europe 1 - Bat Z,9513,T,AV,Raymond Barre,None,97410,97470,Saint-Benoit,None,IMMEUBLE EUROPE 1 - BaT Z,None,9513 AVENUE RAYMOND BARRE,None,97470,SAINT-BENOiT,FRANCE,PM,None,0,None,A,2016-05-19 08:03:43
750274,W9R4008979,None,None,None,9R4S,2023-01-27,2023-01-27,2023-02-07,0001-01-01,D,S,ARC EN CIEL INTER LOCATAIRES,ARCECIL,"entreprendre toutes les demarches necessaires en vue de la defense des interets des locataires accompagner dans les demarches a laccession a la propriete bail a lappui etre le porte parole des quartiers aupres des differents organismes et institutions accompagner les projets necessaires et adapter selon les besoins des quartiers entraider et assister sous toutes ses formes accompagner les personnes agees dans leurs demarches, portage des repas pour les personnes agees mener toutes actions qui semblent utiles tant sur le plan social ou humanitaire soupe populaire, epicerie solidaire contribuer a leducation et a la formation des jeunes et des seniors dans tous les domaines contribuer dans leconomie solidaires et circulaires ainsi que dans la transition ecologique se donner tous les moyens necessaires a la realisation de ses objectifs",032000,019000,None,5,None,CITE1,Augustin Panon,None,97415,97460,Saint-Paul,None,None,None,5 CITE AUGUSTIN PANON,None,97460,ST PAUL,FRANCE,SF,None,0,None,A,2023-02-07 12:45:26
750446,W9R4009151,None,None,None,9R4S,2023-08-10,2023-08-10,2023-09-05,0001-01-01,D,S,LES CHEVALIERS DU COEUR,LES CHEVALIERS DU COEUR,aide a lamelioration de lhabitat hebergement pour personne vulnerable aide a lenfance defavorisee,032000,019000,None,103,None,RTE,Hubert Delisle 2,None,97415,97423,Le Guillaume Saint-Paul,None,None,None,103 route Hubert Delisle 2,None,97423,Le Guillaume Saint-Paul,FRANCE,PM,None,0,None,A,2023-09-06 05:50:13
886924,W341003747,None,None,None,341S,2009-03-05,2009-03-05,2009-03-14,0001-01-01,D,S,DIGNITE POUR TOIT,DIGNITE POUR TOIT,aider les personnes a faible revenu a avoir une activite manuelle et un logement decent,032000,003000,None,10,None,RUE,Massol,None,34032,34500,Beziers,None,None,None,10 rue Massol,None,34500,BEZIERS,FRANCE,PL,None,0,None,A,2009-04-08 15:05:20
891394,W341008222,None,None,None,341S,2017-01-20,2017-01-20,2017-03-11,0001-01-01,D,S,ADLA - ASSOCIATION POUR LE DEVELOPPEMENT DU LOGEMENT EN AFRIQUE,ADLA,"favoriser le developpement du logement et notamment du logement social en Afrique pour ce faire lassociation pourra exercer du lobbying, des activites economiques telles que le montage de projets, la gestion de projets, la gestion de biens ou la location et la vente de biens de maniere a developper en fin doperation un parc locatif destine aux populations locales",032000,020020,None,196,None,AV,Albert Camus,None,34037,34760,Boujan-sur-Libron,None,None,None,1 rue du Levant,None,34470,Perols,FRANCE,PM,None,0,None,A,2017-03-14 16:11:17
927455,W343031381,None,None,None,343P,2023-08-16,2023-08-16,2023-08-22,0001-01-01,D,S,FAMILLES RURALES HABITAT LOGEMENT,AFR HABITAT LOGEMENT,"agence immobiliere a vocation sociale, prendra en charge lensemble des dispositifs, des actions et suivi de logement a titre social tout en accompagnant egalement les locataires durant la totalite de leurs baux",032000,019005,None,133,None,RUE,OLOF PALME,None,34172,34070,Montpellier,None,President,None,133 rue OLOF PALME,None,34070,Montpellier,FRANCE,PM,None,0,None,A,2023-08-22 10:05:07
1101528,W313038933,None,None,None,313P,2024-03-08,2024-03-08,2024-03-19,0001-01-01,D,S,DEMAN MAISON PARTAGEE FRONTON,DEMAN MAISON PARTAGEE FRONTON,"exploiter et gerer une structure dhebergement collectif pour personnes isolees ou en difficulte et notamment les personnes agees de plus 60 ans autonomes, les personnes souffrant de handicap, intervenir dans le champ social et ameliorer les conditions de vie des diverses categories personnes isolees, telles que des personnes agees, des etudiants, de jeunes travailleurs et demandeurs demploi, en offrant tous services tels que les portages de repas a domicile, intervenir pour aider ces personnes a resoudre leur probleme de solitude et de logement, en mettant en relation celles qui disposent dun lieu de vie et qui souhaitent le partager avec celles qui recherchent un hebergement developper tout projet et tout service, et engager toute operation contribuant directement ou indirectement a la realisation de son objet",032000,019000,None,86,None,CHEM1,du Reservoir,None,31220,31560,Gibel,None,None,None,86 CHEMIN DU RESERVOIR,None,31560,GIBEL,FRANCE,AF,http:deman-habitat.com,0,None,A,2024-03-19 10:08:19
1182980,W281004210,None,None,None,281P,2008-07-10,2013-03-29,2008-07-19,2012-09-17,D,S,AGENCE DEPARTEMENTALE DINFORMATION SUR LE LOGEMENT,ADIL,"informer le public sur toute question touchant au logement et a lhabitat cette information, qui repose sur une competence juridique et financiere confirmee, doit etre complete, neutre, personnalisee et gratuite elle peut, lorsque la situation locale le permet, saccompagner dune information sur des offres de terrains et de logements disponibles elle vise a favoriser le bon deroulement des projets daccession a la propriete des menages et permettre aux usagers, en particulier aux personnes defavorisees, de disposer de tous les elements permettant lexercice dun choix veritable et independant, le contact direct avec le public est privilegie dans la mesure du possible laction de lassociation aupres du public exclus tout acte administratif, commercial ou contentieux lassociation a egalement vocation a assurer au benefice de ses membres des actions de conseil et dexpertise juridique ou economique et a entreprendre toutes etudes, recherches ou demarches prospectives liees a son domaine dactivite, elle peut faire des propositions qui lui paraissent de nature a orienter les politiques publiques en matiere de logement et dhabitat, elle transmet ses propositions a lassociation nationale pour linformation sur le logement lassociation contribue a la collecte et a lexploitation des donnees de lensemble du reseau des associations departementales, coordonnees par lassociation nationale pour linformation sur le logement : elle analyse les informations issues de la demande exprimee par le public et assure la diffusion de ses analyses a lensemble de ses membres, a lassociation nationale pour linformation sur le logement et au ministere charge du logement elle enrichit les donnees nationales du reseau des associations departementales de ses experiences, propositions, analyses et etudes",032000,019000,conseil general deure et loir,1,,PL,chatelet,None,28085,28000,Chartres,None,CONSEIL GeNeRAL DEURE ET LOIR,None,1 PLACE CHaTELET,None,28000,CHARTRES,FRANCE,PM,None,0,None,D,2013-09-28 20:00:03
1197900,W811004656,None,None,None,811P,2014-02-28,2019-04-12,2014-03-08,2019-04-06,D,S,INTERGENERATION LOGEMENT ET LIEN I2L,I2L,"ameliorer les conditions de vie et reduire les depenses liees au logement des personnes agees, generer de lactivite economique locale en valorisant la complementarite entre linsertion de publics et lactivite economique liee a la realisation de travaux, agir pour recreer ou maintenir le lien social des personnes agees dans leur zone dhabitation, aider les personnes agees a contacter les structures agissant dans le maintien a domicile",032000,019000,None,155,None,CHEM1,de Sainte Careme,None,81004,81000,Albi,None,None,None,155 chemin de Sainte Careme,None,81000,ALBI,FRANCE,PM,None,0,None,D,2019-04-12 11:13:15

In [45]:
asso_full[asso_full['id'] == 'W442024754']

,id,id_ex,siret,rup_mi,gestion,date_creat,date_decla,date_publi,date_disso,nature,groupement,titre,titre_court,objet,objet_social1,objet_social2,adrs_complement,adrs_numvoie,adrs_repetition,adrs_typevoie,adrs_libvoie,adrs_distrib,adrs_codeinsee,adrs_codepostal,adrs_libcommune,adrg_declarant,adrg_complemid,adrg_complemgeo,adrg_libvoie,adrg_distrib,adrg_codepostal,adrg_achemine,adrg_pays,dir_civilite,siteweb,publiweb,observation,position,maj_time
1497186,W442024754,None,None,None,751P,2020-01-29,2025-07-16,2020-02-08,0001-01-01,D,S,BUREAUX DU COEUR,BUREAUX DU COEUR,"proposer a des personnes seules, en grande precarite, nommees invite.es, suivies par des associations choisies et reconnues, des bureaux daccueil de facon temporaire, la nuit et le week-end, au sein dorganisations hotes, essentiellement des entreprises, adherentes de lassociation",014000,032000,None,204,None,RUE,de Crimee,None,75119,75019,Paris,None,None,None,35 RUE JULES VERNE,None,44700,ORVAULT,FRANCE,PM,None,0,None,A,2025-07-29 07:05:36

In [ ]:
asso_full[asso_full['titre_court'].str.contains('wimoov', case=False, na=False)].assign(objet=lambda x: x['objet'].str[:300])[['id', 'titre_court', 'objet_social1', 'objet', 'adrs_codeinsee']]

,id,titre_court,objet_social1,objet,adrs_codeinsee
1324302,W751186914,WIMOOV,024045,"promouvoir et initier le developpement de nouvelles pratiques de mobilite sensibiliser et accompagner tous les publics vers une mobilite autonome, responsable et respectueuse de lenvironnement",75111

## Filter Asso Réfugies

In [38]:
asso[(asso.objet_social1=='019025') & (asso.adrs_codeinsee=='33063')].titre_court.head(25)

468278    RESEAU UNIVERSITAIRE AIME
469936        LA FORCE DUNE MERE FM
477263              PONT DE LESPOIR
Name: titre_court, dtype: object

In [ ]:
asso_refug = asso[asso.objet_social1.str.startswith(('003', '019', '020', '014'), na=False)].loc[
    asso['objet'].str.contains('asil', regex=False, case=False, na=False)
    |asso['objet'].str.contains('refug', regex=False, case=False, na=False)
    |asso['objet'].str.contains('nouveaux arrivants', regex=False, case=False, na=False)
    |asso['objet'].str.contains('migra', regex=False, case=False, na=False),
    ['id', 'adrs_codeinsee', 'titre','position','objet_social1', 'objet']
]

In [24]:
mapping = odis_referentiels[odis_referentiels['key'] == 'waldec_codes'].set_index('code')['label']
asso_refug['objet_lib'] = asso_refug['objet_social1'].astype(int).astype(str).map(mapping)

In [25]:
asso_refug.groupby(['objet_social1', 'objet_lib']).count().sort_values(by='id', ascending=False)

,,id,adrs_codeinsee,titre,position,objet
objet_social1,objet_lib,,,,,
014035,groupements d'entraide et de solidarité,861,861,861,861,861
020000,"ASSOCIATIONS CARITATIVES, HUMANITAIRES, AIDE AU DÉVELOPPEMENT, DÉVELOPPEMENT DU BÉNÉVOLAT",800,800,800,800,800
014000,"AMICALES, GROUPEMENTS AFFINITAIRES, GROUPEMENTS D'ENTRAIDE (HORS DÉFENSE DE DROITS FONDAMENTAUX)",772,772,772,772,772
014040,"amicale de personnes originaires d'un même pays (hors défense des droits des étrangers), d'une même région du monde",536,536,536,536,536
019025,aide aux réfugiés et aux immigrés (hors défense de droits fondamentaux),357,357,357,357,357
020020,associations caritatives intervenant au plan international,325,325,325,325,325
019000,INTERVENTIONS SOCIALES,313,313,313,313,313
003050,"défense de droits de personnes étrangères ou immigrées, de personnes réfugiées",298,298,298,298,298
020015,associations caritatives à but multiple,262,262,262,262,262
003000,"DÉFENSE DE DROITS FONDAMENTAUX, ACTIVITÉS CIVIQUES",207,207,207,207,207
020005,secours financiers et autres services aux personnes en difficulté,166,166,166,166,166
003015,défense des libertés publiques et des droits de l'Homme,119,119,119,119,119
014045,amicale de personnes originaires d'une même région,113,113,113,113,113
003045,défense de droits de personnes rapatriées,73,73,73,73,73
020010,"secours en nature, distribution de nourriture et de vêtements",64,64,64,64,64
003040,lutte contre les discriminations,45,45,45,45,45
014050,associations féminines pour l'entraide et la solidarité (hors défense de droits fondamentaux),42,42,42,42,42
019004,aide et conseils aux familles,41,41,41,41,41
019016,aide à l'insertion des jeunes,35,35,35,35,35
019005,"associations familiales, services sociaux pour les familles",34,34,34,34,34
019040,"aide aux personnes en danger, solitude, désespoir, soutien psychologique et moral",25,25,25,25,25
003020,"défense des droits des femmes, condition féminine",25,25,25,25,25
003060,"activités civiques, information civique",23,23,23,23,23
014070,associations de personnes en situation de handicap pour l'entraide et la solidarité (hors défense de droits fondamentaux),20,20,20,20,20
014030,association du personnel d'une entreprise (hors caractère syndical),19,19,19,19,19
014025,organisation de professions (hors caractère syndical),15,15,15,15,15
003025,défense de droits de personnes homosexuelles,13,13,13,13,13
003035,association pour la défense de droits de minorités,12,12,12,12,12
019014,lutte contre l'illettrisme,10,10,10,10,10
020025,développement du bénévolat,9,9,9,9,9
014060,associations de personnes homosexuelles pour l'entraide et la solidarité (hors défense de droits fondamentaux),8,8,8,8,8
019047,foyers socio-éducatifs,7,7,7,7,7
019010,"centres sociaux, foyers de jeunes travailleurs, centres d'études et d'action sociale",7,7,7,7,7
003010,défense de la paix,7,7,7,7,7
014080,associations de classe d.âge,6,6,6,6,6
019045,lutte contre diverses formes de violence,5,5,5,5,5
003030,défense des droits des personnes en situation de handicap,5,5,5,5,5
019032,aide aux victimes de violences conjugales,4,4,4,4,4
003012,défense des droits des enfants,4,4,4,4,4
019050,réinsertion des délinquants,3,3,3,3,3
019035,aide aux victimes de violences faites aux enfants,2,2,2,2,2
019055,"soutien aux détenus, reclassement des détenus",2,2,2,2,2
019030,"aide aux victimes de calamités naturelles, de catastrophes naturelles",1,1,1,1,1

In [38]:
asso_refug.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5695 entries, 2462 to 2214945
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              5695 non-null   object
 1   adrs_codeinsee  5695 non-null   object
 2   titre           5695 non-null   object
 3   position        5695 non-null   object
 4   objet_social1   5695 non-null   object
 5   objet           5695 non-null   object
 6   objet_lib       5695 non-null   object
dtypes: object(7)
memory usage: 355.9+ KB

In [40]:
asso_refug[asso_refug.adrs_codeinsee == "33063"][['titre', 'objet_social1']].sort_values(by='objet_social1')

,titre,objet_social1
447276,MEMOIRES ET PARTAGES,003000
450015,LAMICALE DES TUNISIENS DE BORDEAUX,003015
462115,ASSOCIATION DES PARENTS DE FAMILLES ESPAGNOLES EMIGREES EN FRANCE - APFEEF DE,003015
472916,KHAIMA QUEER,003025
457113,ACCOMPAGNEMENT PSYCHOLOGIQUE ET MEDIATION INTERCULTURELLE - AMI,003040
463913,WELCOME BORDEAUX RESEAU DHOSPITALITE POUR DES DEMANDEURS DASILE DANS LA REGION DE BORDEAUX,003050
468339,FEARLESS CULTURE,014035
472166,COLLECTIF DES MIGRANT.E.S. DE BORDEAUX CMB,014035
473387,MEDIATION INTERCULTURELLE EN MILIEUX MEDICAL ET SOCIAL INTERPRETARIAT,014035
473665,AQUITAINE EDUCATION - AQUEDUC,014035
466286,BIENVENUE AUX REFUGIES EN GIRONDE,014035
473810,A.M.E - ARCHITECTES POUR DES MIGRATIONS ETHIQUES,014035
460167,COLLECTIF DES ORGANISATIONS DE SOLIDARITE INTERNATIONALE ISSUES DES MIGRATIONS EN NOUVELLE-AQUITAINE COSIM NOUVELLE-AQUITAINE,014035
475558,BASSAN FEMMES FAMILLES,014035
475701,ACCUEIL CHRETIEN DES MIGRANTS ET EXILES EN GIRONDE - ACME,014035
477210,MAUVES,014035
477320,BREAKING THE CHAINS VUCJAK,014035
478635,ASSOCIATION VIE INTEGRATION ET SOLIDARITE POUR MIGRANTS AFRICAINS- AVISMA,014035
479350,LES MAINS DAMANI,014035
479869,MUSSIDAL BORDEAUX,014035
468358,LES ORCHIDEES ROUGES,014035
471245,COLLECTIF BIENVENUE,014035
474094,MAISON MOLDAVE,014040
468775,ASSOCIATION KURDE ROJAVA GIRONDE,014040
1362634,GREEN FASHION WOMEN - BAMAKO GFW-BKO,014040
466691,LES ROSES DE DAMAS,014040
461574,CENTRE CULTUREL GEORGIEN PHESVEBI,014040
458782,ASSOCIATION DES TUNISIENS EN FRANCE DAQUITAINE,014040
455677,ASSOCIATION POUR LINSERTION SOCIALE ET ECONOMIQUE DES MAHORAIS EN METROPOLE : AISE2M,014040
474124,ASSOCIATION WONTANARA SOLIDARITE - AWSO,014050
452074,COMITE TCHETCHENIE CAUCASE GIRONDE,019000
452165,JURISINTEGRATION,019000
477260,ASSOCIATION SOLIDAIRE MARIE CURRY,019000
466936,ACCUEIL PROTESTANT DE REFUGIES DORIENT EN GUYENNE,019004
451951,PROMO-FEMMES ST MICHEL,019016
477263,PONT DE LESPOIR,019025
468278,RESEAU UNIVERSITAIRE BORDELAIS POUR LACCUEIL ET LINSERTION DES MIGRANT-E-S ET DES EXILE-E-S RESEAU UNIVERSITAIRE AIME,019025
452293,NGAYNAKA,020000
478171,BREF,020000
475225,SINGA BORDEAUX,020000
554949,SOIF DEDUCATION,020000
453665,MOUVEMENT DE REFLEXION SUR LIMMIGRATION M.R.I,020000
457771,AFRIKOTREMENT,020015
827847,DIASPORA INVEST,020015
468227,REFUGEES LIVES MATTER,020020

In [32]:
odis_referentiels[(odis_referentiels.code=='23000')].head(100)

,key,code,label,reg_code
850,waldec_codes,23000,"REPRÉSENTATION, PROMOTION ET DÉFENSE D'INTÉRÊTS ÉCONOMIQUES",None

In [33]:
odis_associations_agg.head()

  codgeo id_waldec  count
0  00000    001000      1
1  00000    002000      1
2  00000    005000      2
3  00000    006000      1
4  00000    006030      3

## Filter RNA Mini ODIS

In [93]:
asso.head()

,id,id_ex,siret,rup_mi,gestion,date_creat,date_decla,date_publi,date_disso,nature,groupement,titre,titre_court,objet,objet_social1,objet_social2,adrs_complement,adrs_numvoie,adrs_repetition,adrs_typevoie,adrs_libvoie,adrs_distrib,adrs_codeinsee,adrs_codepostal,adrs_libcommune,adrg_declarant,adrg_complemid,adrg_complemgeo,adrg_libvoie,adrg_distrib,adrg_codepostal,adrg_achemine,adrg_pays,dir_civilite,siteweb,publiweb,observation,position,maj_time
0,W431000001,None,None,None,431S,2006-03-10,2006-03-10,0001-01-01,0001-01-01,D,S,MENTION TRES BIEN,MENTION TRES BIEN,aide et soutien scolaire,015025,000000,None,12,,RUE,de La Rodde,None,43258,43360,Vergongheon,None,None,None,12 Rue de La Rodde,None,43360,VERGONGHEON,FRANCE,PM,None,0,None,A,2007-10-09 15:23:51
1,W431000002,None,None,None,431S,2006-03-03,2013-02-27,0001-01-01,0001-01-01,D,S,GROUPEMENT DEMPLOYEURS DU LIVRADOIS,GROUPEMENT DEMPLOYEURS DU LIVRADOIS,Mettre un salarie a disposition de ses adherents - Embauche de salaries a plusieurs - Reduire des couts de main doeuvre,030005,000000,None,None,,None,LE BOURG,None,43128,43160,Malvieres,None,None,None,LE BOURG,None,43160,MALVIERES,FRANCE,PM,None,0,None,A,2013-02-27 09:14:40
2,W431000003,None,None,None,431S,2006-02-27,2006-02-27,0001-01-01,0001-01-01,D,S,GROUPEMENT DEMPLOYEURS DU CANTOU,GROUPEMENT DEMPLOYEURS DU CANTOU,La mise a disposition de ses membres dun salarie lie a ce groupement par un contrat de travail,030000,000000,None,None,,None,CHIRAC,None,43056,43300,Chanteuges,None,None,None,CHIRAC,None,43300,CHANTEUGES,FRANCE,PM,None,0,None,A,2008-08-11 20:09:10
3,W431000004,None,None,None,431S,2006-02-22,2020-02-05,0001-01-01,0001-01-01,D,S,ASSOCIATION DES PARENTS DELEVES DES ECOLES PUBLIQUES JULES FERRY DE LANGEAC,ASSOCIATION DES PARENTS DELEVES D...,"Toute activite susceptible dapporter un soutien utile a la vie de lecole, une collaboration efficace a laction des maitres et veiller a la defense des interets materiels et moraux de lecole",015065,000000,Mairie,None,,None,None,None,43112,43300,Langeac,None,Mairie,None,None,None,43300,LANGEAC,FRANCE,PF,None,0,None,A,2020-02-11 11:12:25
4,W431000005,None,None,None,431S,2006-02-16,2006-02-16,0001-01-01,0001-01-01,D,S,LABRIPOM,LABRIPOM,"Cette association a pour but la creation, la production, la representation et lorganisation de spectacle et de toutes manifestations culturelles et de loisirs.",006030,000000,None,18,,RUE,Saint Verny,None,43040,43100,Brioude,None,None,None,18 Rue Saint Verny,None,43100,BRIOUDE,FRANCE,PF,None,0,None,A,2008-03-04 17:31:39

In [ ]:
waldec_prefixes = ["003", "018", "019", "020", "032"] #014040
cols_to_keep = ['id', 'adrs_codeinsee', 'objet_social1','titre_court', 'objet']
asso_mini = asso[(asso['objet_social1'].str[:3].isin(waldec_prefixes)) & (asso.position == 'A')][cols_to_keep]
asso_mini['objet'] = asso_mini['objet'].str[:250].str.lower()
asso_mini.to_parquet('../data/odis_asso_mini.parquet', compression='brotli', index=False)

In [117]:
asso_mini.head(50)

,id,adrs_codeinsee,objet_social1,objet
55,W431000057,43132,020015,"organisation des manifestations caritatives comme le telethon, la marche adot43, adapei"
65,W431000067,43264,019040,"louverture et la gestion dun lieu de vie, sis a villeneuve dallier, accueillant des adolescents et pre-adolescents filles et garcons en difficultes, confies par decision de justice ou par les organismes departementaux."
178,W431000184,43040,020020,"encourager et cultiver lideal de servir, le developpement des relations personnelles damour entre ses membres en vue de leur fournir des occasions de servir linteret general, lobservation des regles de probite et de delicatesse dans lexercice de leur"
208,W431000217,43040,019020,favoriser linsertion sociales et professionnelle des personnes en difficulte par lexercice dune activite professionnelle
231,W431000240,43118,020015,projets humanitaires.
263,W431000277,43067,003040,denoncer les injustices et les mensonges qui causent des victimes innocentes et sans defense - aider ces victimes.
295,W431000313,43112,018050,favoriser linsertion des personnes handicapees par la promotion dactivites a caractere culturel en collaboration avec dautres associations ou en utilisant ses propres moyens
364,W431000388,43040,020015,"laide materielle et morale aux oeuvres privees, charitables, hospitalieres, sanitaires et sociales, et en particulier ladministration et la gestion des residences saint dominique a brioude et la maison de retraite saint-dominique a craponne-sur-arzon"
410,W431000434,43258,018050,"lorientation, la reeducation et la formation professionnelle des personnes en situation de handicap, leur insertion ou reinsertion dans la vie economique et sociale afin de concourir a leur integration dans la societe informer lopinion sur ces sujet"
536,W431000561,43040,018005,"de faire decouvrir et promouvoir le bien-etre des enfants massage bebe, portage, langue des signes... et des adultes pilates..."
561,W431000586,43132,020000,aide humanitaire pour lafrique et entraide locale aux plus demunie
602,W431000627,43040,019016,elaboration et mise en oeuvre dune politique locale concertee dinsertion professionnelle et sociale des jeunes de 16 a 25 ans
756,W431000781,43103,019016,"lorganisation administrative et la gestion du lieu de vie lieu daccueil camina recevant des jeunes en difficultes etou en danger, dans le but de favoriser leur reinsertion sociale etou famille, elle aidera et soutiendra les responsables du lieu de vi"
796,W431000821,43258,019004,reunir les mamans ayant besoin dun soutient a un moment donne
816,W431000841,43040,020015,organisation de projets humanitaires
822,W431000847,43040,020025,"soutenir des projets et des initiatives locales qui concourent a la vie locale, au dynamisme et au developpement de la region, elle a egalment pour objectif de developper localement la solidarite"
904,W431000929,43261,020015,"aider a la reconstruction dun gymnase, achat de materiel pour le gymnase de lecole de quinahue ainsi quune aide a la remise en service de lecole de quinahue"
907,W431000932,43040,032520,"exercer tous droits en matiere, notamment, de defense des investisseurs en valeurs mobilieres ou en produits financiers, des contribuables et des telespectateurs, defense des interets individuells et collectifs dans tous les domaines decides par le c"
909,W431000934,43148,019000,promouvoir lanimation pour les personnes agees de la maison de retraite les pireilles
972,W431000997,43040,019042,sensibiliser les jeunes dans le but deviter quils empruntent la route departementale 588 route de saint-flour a pied la nuit
1019,W431001044,43100,020015,participation a un ou plusieurs raids 4l trophy aventure sportive et activites humanitaires developpement de larchitecture dans les pays sous-developpes
1044,W431001069,43239,019004,"assurer un soutien de proximite a la parentalite, en particulier au niveau de lallaitement maternel en haute-loire, et au-dela sil y a une demande soutenir des meres et des familles, afin quelles reussissent leur projet dallaitement, cest-a-dire que"
1092,W431001117,43112,019047,"de developper la vie collective, communautaire et cooperative de letablissement, tout en favorisant lepanouissement de la personnalite de chacun de promouvoir le sens des responsabilites et lapprentissage de la vie civique et democratique dameliore"
1176,W431001201,43112,019016,"de proposer a des structures de leconomie sociale et solidaire un soutien logistique, technique ou administral permettant une insertion socio professionnelle de qualite le soutien peut prendre notamment la forme de mise a disposition de locaux, de m"
1260,W431001285,43038,020005,favoriser linsertion sociale et professionnelle de toute personne en difficulte
1285,W431001310,43185,019047,promouvoir le sens des responsabilites et de la vie civique participer aux actions collectives dentraide et solidarite favoriser un esprit de tolerance et douverture a lautre valoriser la creativite developper la vie sociale se familiariser au t
1309,W431001337,43112,003015,"faciliter la rencontre, lechange et la reflexion entre citoyens langeadois en experimentant la democratie participative promouvoir le respect des droits de lhomme promouvoir les valeurs citoyennes dans le respect de la laicite promouvoir le debat"
1313,W431001341,43040,032000,"elle agit entre autre : contre toute forme dexclusion sociale, economique, culturelle et raciale pour favoriser leducation populaire et la solidarite pour developper la responsablite et la promotion des individus et collective aux decisions qui les c"
1354,W431001382,43258,003030,defendre la sante et proteger nos enfants en situation de handicap touches par la maladie et dans lincapacite daffronter les mauvais traitements quon veut leur infliger
1365,W431001393,43051,019000,"assistante, aide morale et materielle a tous ceux qui en ont besoin, sans acception dopinion politique, philosophique, religieuse ou encore de nationalite son action est fondee sur les valeurs de fraternite et de solidarite dont levangile porte temo"
1405,W431001434,43148,019004,aider materiellement et moralement a domicile les familles en milieu rural a tous moments de leur existence
1407,W431001436,43118,019000,organiser lanimation de la maison daccueil en veilant a lelaboration et la mise en oeuvre du projet de vie
1413,W431001442,43040,020015,aider les personnes a regagner autonomie et dignite proposer un travail educatif et creer du lien social
1439,W431001468,43040,019010,"promouvoir le sens des responsabilites et de la vie civique.participer aux actions collectives dentraide et de solidarite.developper la vie sociale,valoriser la creativite,linitiative et le gout dentreprendre."
1445,W431001474,43132,020005,"etablir un programme dactions pour venir en aide a jean ratail, enfant myopathe cette aide peut prendre diverses formes comme lachat de materiel orthopedique, de seances ludiques ou de soins non pris en charge par quelques organismes que ce soit"
1469,W431001498,43120,020020,fournir du materiel scolaire et sportif a des enfants demunis du sud marocain en participant au rally-raid humanitaire : le 4l trophy 2018
1582,W431004711,43016,020005,"aider a subvenir aux besoins inherents a letat de sante dhugo, et aux besoins de sa famille, exercer des activites economiques telles que ventes de produits tombola, organisation de soirees avec repas, marche solidaire, liste non exhaustive, utilisat"
1583,W431004712,43185,019014,"alphabetisation des personnes ne maitrisant pas ou peu le francais, et selon les besoins et les possibilites, tisser des liens sociaux, partager des connaissances en partant de lalphabetisation, partager le savoir-faire et le savoir-etre, repondre au"
1605,W431004734,43234,020020,procurer des fournitures scolaires aux enfants defavorises du maroc
1607,W431004736,43170,020020,participation au raid humanitaire du 4l trophy
1622,W431004753,43234,020020,"apporter une aide materielle a des habitants du sud marocain, a travers la participation a differents projets comme le raid humanitaire 205 trophee"
1623,W431004754,43040,020000,"collecter du materiel scolaire, sportif, medical, de construction ainsi que des denrees non perissables afin de les distribuer dans les provinces derrachidia et de ouarzazate au maroc ameliorer les conditions de vie des enfants defavorises du sud-es"
1624,W431004755,43178,020020,contribuer au developpement dans les regions dans lesquelles lentreprise zetwal etablit des liens commerciaux avec des artistes et artisans et plus largement dans les regions dans lesquelles elle a eu des partenaires ou eventuellement ailleurs pour r
1643,W431004774,43070,020020,"apporter un soutien humanitaire aux populations defavorisees des pays dafrique et du mon entier en general organiser et participer a des evenements sportifs, culturels, sociaux et humanitaires afin de creer des liens intergenerationnels, intercultur"
1693,W431004824,43016,020000,production et vente a ses membres de tous les objets utiles a lexistence et le groupement ou la fusion de la presente societe avec toutes autres cooperatives de la region la societe se reserve la faculte douvrir la vente aux consommateurs non socie
1766,W431004897,43040,032520,"defense des interets des lotisseurs du cil, route de saint-flour, a brioude"
1770,W431004901,43040,020005,"aider, secourir, assister et au besoin defendre tous les jeunes en difficulte, ayant eu des problemes avec la justice, qui ont fait de la prison, drogues ou alcooliques leur donner toutes les possibilites de se reclasser dans la societe les aider a"
1781,W431004912,43040,019005,grouper et servir les interets des exploitants de jardins familiaux proprietaires et locataires par des moyens legaux appropries
1815,W431004946,43040,020015,"reunir des fonds par la vente de cartes de membres, dobjets divers, publications, ainsi que lorganisation de manifestations diverses afin deffectuer des operations dassistance et de bienfaisance"
1870,W431005001,43038,003000,"rassembler en son sein tous les jeunes francais et toutes les jeunes francaises devoues a la patrie et de les eduquer dans lamour de la republique, de la democratie et de la laicite"

## BPE

In [9]:
bpe = pd.read_parquet("../pipeline/cache/raw/BPE24.parquet")
bpe.head()

,AN,NOMRS,CNOMRS,NUMVOIE,INDREP,TYPVOIE,LIBVOIE,CADR,CODPOS,DEPCOM,DEP,REG,LIBCOM,DOM,SDOM,TYPEQU,SIRET,STATUT_DIFFUSION,CANTINE,INTERNAT,RPI,EP,CL_PGE,SECT,ACCES_AIRE_PRATIQUE,ACCES_LIBRE,ACCES_SANITAIRE,ACCES_VESTIAIRE,CAPACITE_D_ACCUEIL,PRES_DOUCHE,PRES_SANITAIRE,SAISONNIER,COUVERT,ECLAIRE,CATEGORIE,MULTIPLEXE,STRUCTURE_EXERCICE,SPECIALITE,ACCUEIL,ITINERANCE,MODE_GESTION,SSTYPHEB,TYPE,IMPLANTATION_STATION,CAPACITE,INDIC_CAPA,NBEQUIDENT,INDIC_NBEQUIDENT,NBSALLES,INDIC_NBSALLES,NBLIEUX,INDIC_NBLIEUX,NB_PDC,INDIC_NB_PDC,NB_PDC_PA,INDIC_NB_PDC_PA,NB_PDC_ACCELEREE,INDIC_NB_PDC_ACCELEREE,NB_PDC_LENTE,INDIC_NB_PDC_LENTE,NB_PDC_RAPIDE,INDIC_NB_PDC_RAPIDE,NB_PDC_ULTRARAPIDE,INDIC_NB_PDC_ULTRARAPIDE,NB_JOURS_OUVERT,INDIC_NB_JOURS_OUVERT,LAMBERT_X,LAMBERT_Y,LONGITUDE,LATITUDE,QUALITE_XY,EPSG,QUALITE_GEOLOC,TR_DIST_PRECISION,DCIRIS,QUALI_IRIS,IRISEE,QP2024,QUALI_QP2024,QVA,QUALI_QVA,ZUS,QUALI_ZUS,EPCI,UU2020,BV2022,AAV2020,DENS3,DENS7
0,2024,COMMISSARIAT DE POLICE DE POINTE À PITRE,,,,,QUARTIER LAFOND,,97139,97101,971,01,LES ABYMES,A,A1,A101,,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,657375.042366,1.795994e+06,-61.527460,16.239507,B,5490,11,< 100,971010116,1,1,QN97101M,1,CSZ,_Z,0110110,1,200018653,9A701,97101,9A1,2,2
1,2024,DIR REG FINANCES PUBLIQUES GUADELOUPE,1ERE BDV POINTE-A-PITRE,,,RUE,DES FINANCES,CENTRE DES FINANCES PUBLIQUES,97139,97101,971,01,LES ABYMES,A,A1,A120,13001146300135,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,658450.000000,1.797750e+06,-61.517285,16.255304,M,5490,12,>= 500,971010118,1,1,HZ,2,CSZ,_Z,HZ,1,200018653,9A701,97101,9A1,2,2
2,2024,DIR REG FINANCES PUBLIQUES GUADELOUPE,CFD DE ANTILLES-GUYANE,,,,BOISRIPEAUX,RESIDENCE LES MOUFFIAS,97139,97101,971,01,LES ABYMES,A,A1,A120,13001146300259,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,661950.000000,1.800750e+06,-61.484334,16.282183,M,5490,33,_U,971010113,3,1,HZ,3,CSZ,_Z,HZ,3,200018653,9A701,97101,9A1,2,2
3,2024,APE ABYMES DOTHEMARE,,16,,ZAC,DE DOTHEMARE,ROND POINT DOTHEMARE,97139,97101,971,01,LES ABYMES,A,A1,A122,,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,657850.000000,1.796250e+06,-61.523000,16.241787,M,5490,33,_U,971010116,3,1,QN97101M,3,CSZ,_Z,0110110,3,200018653,9A701,97101,9A1,2,2
4,2024,APE ABYMES CARUEL,,,,AV,PATRICK SAINT ELOI,MORNE CARUEL,97139,97101,971,01,LES ABYMES,A,A1,A122,,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,657050.000000,1.797050e+06,-61.530430,16.249069,M,5490,12,>= 500,971010117,2,1,QN97102I,2,CSZ,_Z,HZ,2,200018653,9A701,97101,9A1,2,2

In [22]:
bpe[bpe.SIRET == '38328116900011']

,AN,NOMRS,CNOMRS,NUMVOIE,INDREP,TYPVOIE,LIBVOIE,CADR,CODPOS,DEPCOM,DEP,REG,LIBCOM,DOM,SDOM,TYPEQU,SIRET,STATUT_DIFFUSION,CANTINE,INTERNAT,RPI,EP,CL_PGE,SECT,ACCES_AIRE_PRATIQUE,ACCES_LIBRE,ACCES_SANITAIRE,ACCES_VESTIAIRE,CAPACITE_D_ACCUEIL,PRES_DOUCHE,PRES_SANITAIRE,SAISONNIER,COUVERT,ECLAIRE,CATEGORIE,MULTIPLEXE,STRUCTURE_EXERCICE,SPECIALITE,ACCUEIL,ITINERANCE,MODE_GESTION,SSTYPHEB,TYPE,IMPLANTATION_STATION,CAPACITE,INDIC_CAPA,NBEQUIDENT,INDIC_NBEQUIDENT,NBSALLES,INDIC_NBSALLES,NBLIEUX,INDIC_NBLIEUX,NB_PDC,INDIC_NB_PDC,NB_PDC_PA,INDIC_NB_PDC_PA,NB_PDC_ACCELEREE,INDIC_NB_PDC_ACCELEREE,NB_PDC_LENTE,INDIC_NB_PDC_LENTE,NB_PDC_RAPIDE,INDIC_NB_PDC_RAPIDE,NB_PDC_ULTRARAPIDE,INDIC_NB_PDC_ULTRARAPIDE,NB_JOURS_OUVERT,INDIC_NB_JOURS_OUVERT,LAMBERT_X,LAMBERT_Y,LONGITUDE,LATITUDE,QUALITE_XY,EPSG,QUALITE_GEOLOC,TR_DIST_PRECISION,DCIRIS,QUALI_IRIS,IRISEE,QP2024,QUALI_QP2024,QVA,QUALI_QVA,ZUS,QUALI_ZUS,EPCI,UU2020,BV2022,AAV2020,DENS3,DENS7
754195,2024,CHRS ET SIAO,,12,,RUE,DES DANVIONS,,70000,70550,70,27,VESOUL,D,D7,D703,38328116900011,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,14.0,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,936539.55,6729674.02,6.150191,47.624978,B,2154,11,< 100,705500103,1,1,HZ,1,HZ,1,HZ,1,247000011,70401,70550,138,2,2
754196,2024,ACCUEIL DE JOUR,,12,,RUE,DES DANVIONS,,70000,70550,70,27,VESOUL,D,D7,D703,38328116900011,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,936539.55,6729674.02,6.150191,47.624978,B,2154,11,< 100,705500103,1,1,HZ,1,HZ,1,HZ,1,247000011,70401,70550,138,2,2
754202,2024,DISPOSITIF ASHRA URGENCE,,12,,RUE,DANVIONS,,70000,70550,70,27,VESOUL,D,D7,D710,38328116900011,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,936539.55,6729674.02,6.150191,47.624978,B,2154,11,< 100,705500103,1,1,HZ,1,HZ,1,HZ,1,247000011,70401,70550,138,2,2

In [41]:
# chrs = bpe[bpe['TYPEQU']=="D703"]
bpe[(bpe['TYPEQU'].str.startswith("D703")) & (bpe.CAPACITE.isna()) & (bpe.SIRET.isin(siret_list_unreco))].head(10)

,AN,NOMRS,CNOMRS,NUMVOIE,INDREP,TYPVOIE,LIBVOIE,CADR,CODPOS,DEPCOM,DEP,REG,LIBCOM,DOM,SDOM,TYPEQU,SIRET,STATUT_DIFFUSION,CANTINE,INTERNAT,RPI,EP,CL_PGE,SECT,ACCES_AIRE_PRATIQUE,ACCES_LIBRE,ACCES_SANITAIRE,ACCES_VESTIAIRE,CAPACITE_D_ACCUEIL,PRES_DOUCHE,PRES_SANITAIRE,SAISONNIER,COUVERT,ECLAIRE,CATEGORIE,MULTIPLEXE,STRUCTURE_EXERCICE,SPECIALITE,ACCUEIL,ITINERANCE,MODE_GESTION,SSTYPHEB,TYPE,IMPLANTATION_STATION,CAPACITE,INDIC_CAPA,NBEQUIDENT,INDIC_NBEQUIDENT,NBSALLES,INDIC_NBSALLES,NBLIEUX,INDIC_NBLIEUX,NB_PDC,INDIC_NB_PDC,NB_PDC_PA,INDIC_NB_PDC_PA,NB_PDC_ACCELEREE,INDIC_NB_PDC_ACCELEREE,NB_PDC_LENTE,INDIC_NB_PDC_LENTE,NB_PDC_RAPIDE,INDIC_NB_PDC_RAPIDE,NB_PDC_ULTRARAPIDE,INDIC_NB_PDC_ULTRARAPIDE,NB_JOURS_OUVERT,INDIC_NB_JOURS_OUVERT,LAMBERT_X,LAMBERT_Y,LONGITUDE,LATITUDE,QUALITE_XY,EPSG,QUALITE_GEOLOC,TR_DIST_PRECISION,DCIRIS,QUALI_IRIS,IRISEE,QP2024,QUALI_QP2024,QVA,QUALI_QVA,ZUS,QUALI_ZUS,EPCI,UU2020,BV2022,AAV2020,DENS3,DENS7
2654,2024,CENTRE D'APPEL 115 GUADELOUPE,,,,PARC,D ACTIVITE DE L AEROPORT,,97139,97101,971,01,LES ABYMES,D,D7,D703,48755582300011,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,657786.93,1799923.79,-61.523342,16.274992,B,5490,11,< 100,971010101,1,1,HZ,1,CSZ,_Z,HZ,1,200018653,9A701,97101,9A1,2,2
16381,2024,ACCOMPAGNEMENT ORIENTATION ET RÉINSERTION SOCIALE,,,,RES,LES LAURIERS,BAT. C N° 103,97110,97120,971,01,POINTE-À-PITRE,D,D7,D703,42267494500098,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,657050.00,1795650.00,-61.530524,16.236417,M,5490,22,[100 - 500[,971200107,2,1,QN97114M,2,CSZ,_Z,0110110,2,200018653,9A701,97101,9A1,2,2
42722,2024,CHRS AKATIJ,,24,,RUE,LULLI,,97310,97304,973,03,KOUROU,D,D7,D703,40152524100147,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,318650.00,570650.00,-52.636115,5.160602,M,2972,33,_U,973040103,3,1,HZ,3,CSZ,_Z,HZ,3,200027548,9C401,97304,9C3,2,2
390897,2024,CHRS NORD ALTAIR,,18,,VLA,CHAMBON,,92400,92026,92,11,COURBEVOIE,D,D7,D703,33367483600072,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,645680.70,6866804.90,2.259077,48.898955,B,2154,11,< 100,920260603,1,1,CSZ,_Z,CSZ,_Z,CSZ,_Z,200054781,00851,75056,001,1,1
406693,2024,CHRS CASH,,403,,AV,DE LA REPUBLIQUE,,92000,92050,92,11,NANTERRE,D,D7,D703,26920138000178,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,643101.23,6868318.67,2.223692,48.912345,B,2154,11,< 100,920500701,1,1,QN09213M,1,CSZ,_Z,1120040,1,200054781,00851,75056,001,1,1
908713,2024,ASSOCIATION JERICHO,,28,,RUE,J RONDEAU,,76100,76540,76,28,ROUEN,D,D7,D703,30046251200025,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,560131.87,6927388.51,1.072328,49.430576,M,2154,21,_U,765401005,2,1,HZ,2,CSZ,_Z,HZ,2,200023414,00755,76540,015,1,1
952610,2024,CAVA AGORA,,12,,RUE,DU PRESBYTERE,,59170,59163,59,32,CROIX,D,D7,D703,31483201599999,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,710628.70,7066270.70,3.150155,50.693143,B,2154,11,< 100,591630201,1,1,HZ,1,CSZ,_Z,HZ,1,200093201,59702,59350,004,1,1
1171122,2024,ASSOCIATION ALISES,,2,,RUE,EMILE GENTIL,POINT ACCEUIL BRIEY,54150,54099,54,44,VAL DE BRIEY,D,D7,D703,34326277000153,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,913870.23,6909623.42,5.937689,49.250468,B,2154,11,< 100,540990000,_Z,0,CSZ,_Z,CSZ,_Z,HZ,1,200070845,54205,54099,250,2,3
1182483,2024,ASSOCIATION ALISES,,48,,BD,DU 8 MAI 1945,,54350,54382,54,44,MONT-SAINT-MARTIN,D,D7,D703,34326277000195,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,901749.66,6941713.90,5.786895,49.542669,B,2154,11,< 100,543820102,1,1,QN05405I,1,CSZ,_Z,4100010,1,245400262,54405,54323,184,2,2
1223339,2024,115 - SIAO,,17,,AV,DE BLIDA,,57000,57463,57,44,METZ,D,D7,D703,79098920600079,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,932708.47,6896873.76,6.189109,49.129361,B,2154,11,< 100,574630303,1,1,HZ,1,CSZ,_Z,HZ,1,200039865,57701,57463,033,1,1

In [40]:
siret_list_unreco = [x for x in siret_list if x not in siret_list_reco]
len(siret_list_unreco)

31

In [55]:
bpe[(bpe['TYPEQU'].str.startswith("D7"))].groupby('TYPEQU').count()

,AN,NOMRS,CNOMRS,NUMVOIE,INDREP,TYPVOIE,LIBVOIE,CADR,CODPOS,DEPCOM,DEP,REG,LIBCOM,DOM,SDOM,SIRET,STATUT_DIFFUSION,CANTINE,INTERNAT,RPI,EP,CL_PGE,SECT,ACCES_AIRE_PRATIQUE,ACCES_LIBRE,ACCES_SANITAIRE,ACCES_VESTIAIRE,CAPACITE_D_ACCUEIL,PRES_DOUCHE,PRES_SANITAIRE,SAISONNIER,COUVERT,ECLAIRE,CATEGORIE,MULTIPLEXE,STRUCTURE_EXERCICE,SPECIALITE,ACCUEIL,ITINERANCE,MODE_GESTION,SSTYPHEB,TYPE,IMPLANTATION_STATION,CAPACITE,INDIC_CAPA,NBEQUIDENT,INDIC_NBEQUIDENT,NBSALLES,INDIC_NBSALLES,NBLIEUX,INDIC_NBLIEUX,NB_PDC,INDIC_NB_PDC,NB_PDC_PA,INDIC_NB_PDC_PA,NB_PDC_ACCELEREE,INDIC_NB_PDC_ACCELEREE,NB_PDC_LENTE,INDIC_NB_PDC_LENTE,NB_PDC_RAPIDE,INDIC_NB_PDC_RAPIDE,NB_PDC_ULTRARAPIDE,INDIC_NB_PDC_ULTRARAPIDE,NB_JOURS_OUVERT,INDIC_NB_JOURS_OUVERT,LAMBERT_X,LAMBERT_Y,LONGITUDE,LATITUDE,QUALITE_XY,EPSG,QUALITE_GEOLOC,TR_DIST_PRECISION,DCIRIS,QUALI_IRIS,IRISEE,QP2024,QUALI_QP2024,QVA,QUALI_QVA,ZUS,QUALI_ZUS,EPCI,UU2020,BV2022,AAV2020,DENS3,DENS7
TYPEQU,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
D701,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2542,2663,0,2663,0,2663,0,2663,0,2663,0,2663,0,2663,0,2663,0,2663,0,2663,0,2663,2657,2657,2657,2657,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663,2663
D702,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,0,988,0,988,0,988,0,988,0,988,0,988,0,988,0,988,0,988,0,988,0,988,986,986,986,986,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988,988
D703,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,840,887,0,887,0,887,0,887,0,887,0,887,0,887,0,887,0,887,0,887,0,887,886,886,886,886,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887,887
D704,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,155,158,0,158,0,158,0,158,0,158,0,158,0,158,0,158,0,158,0,158,0,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158
D705,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,400,406,0,406,0,406,0,406,0,406,0,406,0,406,0,406,0,406,0,406,0,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406,406
D710,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,0,5169,0,5169,0,5169,0,5169,0,5169,0,5169,0,5169,0,5169,0,5169,0,5169,0,5169,5165,5165,5165,5165,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169,5169
D711,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,0,648,0,648,0,648,0,648,0,648,0,648,0,648,0,648,0,648,0,648,0,648,647,647,647,647,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648,648

In [20]:
chrs[chrs.DEPCOM =="87187"].head()

Empty DataFrame
Columns: [AN, NOMRS, CNOMRS, NUMVOIE, INDREP, TYPVOIE, LIBVOIE, CADR, CODPOS, DEPCOM, DEP, REG, LIBCOM, DOM, SDOM, TYPEQU, SIRET, STATUT_DIFFUSION, CANTINE, INTERNAT, RPI, EP, CL_PGE, SECT, ACCES_AIRE_PRATIQUE, ACCES_LIBRE, ACCES_SANITAIRE, ACCES_VESTIAIRE, CAPACITE_D_ACCUEIL, PRES_DOUCHE, PRES_SANITAIRE, SAISONNIER, COUVERT, ECLAIRE, CATEGORIE, MULTIPLEXE, STRUCTURE_EXERCICE, SPECIALITE, ACCUEIL, ITINERANCE, MODE_GESTION, SSTYPHEB, TYPE, IMPLANTATION_STATION, CAPACITE, INDIC_CAPA, NBEQUIDENT, INDIC_NBEQUIDENT, NBSALLES, INDIC_NBSALLES, NBLIEUX, INDIC_NBLIEUX, NB_PDC, INDIC_NB_PDC, NB_PDC_PA, INDIC_NB_PDC_PA, NB_PDC_ACCELEREE, INDIC_NB_PDC_ACCELEREE, NB_PDC_LENTE, INDIC_NB_PDC_LENTE, NB_PDC_RAPIDE, INDIC_NB_PDC_RAPIDE, NB_PDC_ULTRARAPIDE, INDIC_NB_PDC_ULTRARAPIDE, NB_JOURS_OUVERT, INDIC_NB_JOURS_OUVERT, LAMBERT_X, LAMBERT_Y, LONGITUDE, LATITUDE, QUALITE_XY, EPSG, QUALITE_GEOLOC, TR_DIST_PRECISION, DCIRIS, QUALI_IRIS, IRISEE, QP2024, QUALI_QP2024, QVA, QUALI_QVA, ZUS, QUALI_ZUS, EPCI, UU2020, BV2022, AAV2020, DENS3, DENS7]
Index: []

In [56]:
autre_hebergement = bpe[bpe['TYPEQU']=="D710"]

In [ ]:
autre_hebergement.

In [65]:
fjt = bpe[
    (bpe['TYPEQU']=="D710") 
    & ((bpe.NOMRS.str.contains('fjt', regex=False, case=False, na=False)) | (bpe.NOMRS.str.contains('foyer jeunes travailleurs', regex=False, case=False, na=False)))
]

In [81]:
fjt.count()

AN         432
NOMRS      432
CNOMRS     432
NUMVOIE    432
INDREP     432
          ...
UU2020     432
BV2022     432
AAV2020    432
DENS3      432
DENS7      432
Length: 89, dtype: int64

In [ ]:
pensionsf = bpe[
    (bpe['TYPEQU']=="D710") 
    & ((bpe.NOMRS.str.contains('pension', regex=False, case=False, na=False)))# | (bpe.NOMRS.str.contains('foyer jeunes travailleurs', regex=False, case=False, na=False)))
]
pensionsf.head()

,AN,NOMRS,CNOMRS,NUMVOIE,INDREP,TYPVOIE,LIBVOIE,CADR,CODPOS,DEPCOM,DEP,REG,LIBCOM,DOM,SDOM,TYPEQU,SIRET,STATUT_DIFFUSION,CANTINE,INTERNAT,RPI,EP,CL_PGE,SECT,ACCES_AIRE_PRATIQUE,ACCES_LIBRE,ACCES_SANITAIRE,ACCES_VESTIAIRE,CAPACITE_D_ACCUEIL,PRES_DOUCHE,PRES_SANITAIRE,SAISONNIER,COUVERT,ECLAIRE,CATEGORIE,MULTIPLEXE,STRUCTURE_EXERCICE,SPECIALITE,ACCUEIL,ITINERANCE,MODE_GESTION,SSTYPHEB,TYPE,IMPLANTATION_STATION,CAPACITE,INDIC_CAPA,NBEQUIDENT,INDIC_NBEQUIDENT,NBSALLES,INDIC_NBSALLES,NBLIEUX,INDIC_NBLIEUX,NB_PDC,INDIC_NB_PDC,NB_PDC_PA,INDIC_NB_PDC_PA,NB_PDC_ACCELEREE,INDIC_NB_PDC_ACCELEREE,NB_PDC_LENTE,INDIC_NB_PDC_LENTE,NB_PDC_RAPIDE,INDIC_NB_PDC_RAPIDE,NB_PDC_ULTRARAPIDE,INDIC_NB_PDC_ULTRARAPIDE,NB_JOURS_OUVERT,INDIC_NB_JOURS_OUVERT,LAMBERT_X,LAMBERT_Y,LONGITUDE,LATITUDE,QUALITE_XY,EPSG,QUALITE_GEOLOC,TR_DIST_PRECISION,DCIRIS,QUALI_IRIS,IRISEE,QP2024,QUALI_QP2024,QVA,QUALI_QVA,ZUS,QUALI_ZUS,EPCI,UU2020,BV2022,AAV2020,DENS3,DENS7
6702,2024,PENSION DE FAMILLE UDAF,,,,ZAC,DE DESMARAIS,,97100,97105,971,01,BASSE-TERRE,D,D7,D710,,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,636150.0,1769250.0,-61.727565,15.999077,M,5490,33,_U,971050101,3,1,HZ,3,HZ,3,HZ,3,249710070,9A501,97105,9A2,2,2
130152,2024,PENSION DE FAMILLE TAITBOUT,,44,,RUE,TAITBOUT,,75009,75109,75,11,PARIS 9E ARRONDISSEMENT,D,D7,D710,31723624800017,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,651251.5,6863983.7,2.335384,48.874031,B,2154,11,< 100,751093406,1,1,CSZ,_Z,CSZ,_Z,CSZ,_Z,200054781,00851,75056,001,1,1
144919,2024,PENSION DE FAMILLE ALIGRE,,9,,RUE,D ALIGRE,,75011,75111,75,11,PARIS 11E ARRONDISSEMENT,D,D7,D710,,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,655450.0,6861350.0,2.392898,48.850651,M,2154,33,_U,751114409,3,1,HZ,3,CSZ,_Z,HZ,3,200054781,00851,75056,001,1,1
165326,2024,PENSION DE FAMILLE,,95,,BD,BRUNE,,75014,75114,75,11,PARIS 14E ARRONDISSEMENT,D,D7,D710,,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,649666.5,6858644.8,2.314407,48.825897,B,2154,11,< 100,751145606,1,1,HZ,1,CSZ,_Z,CSZ,_Z,200054781,00851,75056,001,1,1
165329,2024,PENSION DE FAMILLE POIRIER DE NARCAY,,17,,RUE,POIRIER DE NARCAY,,75014,75114,75,11,PARIS 14E ARRONDISSEMENT,D,D7,D710,,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,650361.5,6858461.6,2.323895,48.824303,B,2154,11,< 100,751145504,1,1,HZ,1,CSZ,_Z,CSZ,_Z,200054781,00851,75056,001,1,1

In [79]:
pensionsf['NOMRS'].count()

np.int64(285)

In [ ]:
foy_mig = bpe[
    (bpe['TYPEQU']=="D710") 
    & ((bpe.NOMRS.str.contains('migrant', regex=False, case=False, na=False)))# | (bpe.NOMRS.str.contains('foyer jeunes travailleurs', regex=False, case=False, na=False)))
]
foy_mig.head()

,AN,NOMRS,CNOMRS,NUMVOIE,INDREP,TYPVOIE,LIBVOIE,CADR,CODPOS,DEPCOM,DEP,REG,LIBCOM,DOM,SDOM,TYPEQU,SIRET,STATUT_DIFFUSION,CANTINE,INTERNAT,RPI,EP,CL_PGE,SECT,ACCES_AIRE_PRATIQUE,ACCES_LIBRE,ACCES_SANITAIRE,ACCES_VESTIAIRE,CAPACITE_D_ACCUEIL,PRES_DOUCHE,PRES_SANITAIRE,SAISONNIER,COUVERT,ECLAIRE,CATEGORIE,MULTIPLEXE,STRUCTURE_EXERCICE,SPECIALITE,ACCUEIL,ITINERANCE,MODE_GESTION,SSTYPHEB,TYPE,IMPLANTATION_STATION,CAPACITE,INDIC_CAPA,NBEQUIDENT,INDIC_NBEQUIDENT,NBSALLES,INDIC_NBSALLES,NBLIEUX,INDIC_NBLIEUX,NB_PDC,INDIC_NB_PDC,NB_PDC_PA,INDIC_NB_PDC_PA,NB_PDC_ACCELEREE,INDIC_NB_PDC_ACCELEREE,NB_PDC_LENTE,INDIC_NB_PDC_LENTE,NB_PDC_RAPIDE,INDIC_NB_PDC_RAPIDE,NB_PDC_ULTRARAPIDE,INDIC_NB_PDC_ULTRARAPIDE,NB_JOURS_OUVERT,INDIC_NB_JOURS_OUVERT,LAMBERT_X,LAMBERT_Y,LONGITUDE,LATITUDE,QUALITE_XY,EPSG,QUALITE_GEOLOC,TR_DIST_PRECISION,DCIRIS,QUALI_IRIS,IRISEE,QP2024,QUALI_QP2024,QVA,QUALI_QVA,ZUS,QUALI_ZUS,EPCI,UU2020,BV2022,AAV2020,DENS3,DENS7
327431,2024,RÉSIDENCE SOCIALE EX FOYER HÉBERGEMENT TRAVAILLEURS MIGRANTS,,33,,RUE,DE LAUNAY,,91380,91161,91,11,CHILLY-MAZARIN,D,D7,D710,78805803009579,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,650110.97,6845474.73,2.322002,48.707485,B,2154,11,< 100,911610102,1,1,HZ,1,CSZ,_Z,CSZ,_Z,200056232,00851,75056,001,1,1
329377,2024,EX FOYER HEBERGEMENT TRAVAILLEURS MIGRANTS,,14,,RUE,DE SEINE,,91100,91174,91,11,CORBEIL-ESSONNES,D,D7,D710,78805803009579,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,661346.44,6835214.89,2.475614,48.615973,B,2154,11,< 100,911740503,1,1,HZ,1,CSZ,_Z,HZ,1,200059228,00851,75056,001,1,1
545157,2024,FOYER TRAV.MIGRANTS: LES CHÊNES,,35,,AV,DE L EGALITE,FOYER LES CHÊNES,95250,95051,95,11,BEAUCHAMP,D,D7,D710,78805803002202,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,640283.34,6879998.69,2.183601,49.017114,B,2154,11,< 100,950510104,1,1,CSZ,_Z,CSZ,_Z,CSZ,_Z,200058485,00851,75056,001,1,1
547060,2024,FOYER TRAV.MIGRANTS : FOYER DE BEZONS,,36,,RUE,JEAN CARASSO,FOYER DE BEZONS,95870,95063,95,11,BEZONS,D,D7,D710,78805803002681,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,642473.73,6869196.10,2.215012,48.920179,B,2154,11,< 100,950630101,1,1,HZ,1,1195066,1,HZ,1,200058519,00851,75056,001,1,1
556898,2024,FOYER TRAV.MIGRANTS : FOYER D' ERMONT,,109,,RUE,F PLASSON,FOYER D'ERMONT,95120,95219,95,11,ERMONT,D,D7,D710,78805803002590,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,644650.20,6877170.65,2.243667,48.992077,B,2154,11,< 100,952190501,1,1,QN09520I,1,CSZ,_Z,CSZ,_Z,200058485,00851,75056,001,1,1

In [80]:
foy_mig['NOMRS'].count()

np.int64(48)

In [72]:
autre_hebergement['NOMRS_TRUNC'] = autre_hebergement['NOMRS'].apply(lambda x: x[:29])
autre_hebergement.groupby('NOMRS_TRUNC')[['NOMRS_TRUNC','AN']].count().sort_values('AN', ascending=False).head(20)

/var/folders/wb/bg23zgwj389404sv03x64x2m0000gn/T/ipykernel_10051/1550546929.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  autre_hebergement['NOMRS_TRUNC'] = autre_hebergement['NOMRS'].apply(lambda x: x[:29])

                               NOMRS_TRUNC  AN
NOMRS_TRUNC
CENTRE D'HEBERGEMENT D'URGENC           85  85
RESIDENCE SOCIALE                       68  68
FOYER DE JEUNES TRAVAILLEURS            49  49
APPARTEMENT DE COORDINATION T           44  44
PENSION DE FAMILLE                      37  37
APPARTEMENTS DE COORDINATION            32  32
MAISON RELAIS                           28  28
LITS HALTE SOINS SANTE                  25  25
FOYER DE TRAVAILLEURS MIGRANT           20  20
APPARTEMENT COORDINATION THER           17  17
FOYER DE JEUNES TRAVAILLEURS            13  13
MAISON D'ACCUEIL HOSPITALIERE           13  13
FJT - RESIDENCE SOCIALE L'APP           12  12
RESIDENCE ACCUEIL                       10  10
CENTRE D'HÉBERGEMENT D'URGENC           10  10
FJT - RESIDENCE SOCIALE                 10  10
ALEOS                                   10  10
PENSION DE FAMILLE RESIDENCE             9   9
FJT - RESIDENCE SOCIALE ALJT             8   8
RESIDENCE SOCIALE FJT PRIM'TO            8   8

In [7]:
heber_tous[heber_tous.DEPCOM == "33281"]

,AN,NOMRS,CNOMRS,NUMVOIE,INDREP,TYPVOIE,LIBVOIE,CADR,CODPOS,DEPCOM,DEP,REG,LIBCOM,DOM,SDOM,TYPEQU,SIRET,STATUT_DIFFUSION,CANTINE,INTERNAT,RPI,EP,CL_PGE,SECT,ACCES_AIRE_PRATIQUE,ACCES_LIBRE,ACCES_SANITAIRE,ACCES_VESTIAIRE,CAPACITE_D_ACCUEIL,PRES_DOUCHE,PRES_SANITAIRE,SAISONNIER,COUVERT,ECLAIRE,CATEGORIE,MULTIPLEXE,STRUCTURE_EXERCICE,SPECIALITE,ACCUEIL,ITINERANCE,MODE_GESTION,SSTYPHEB,TYPE,IMPLANTATION_STATION,CAPACITE,INDIC_CAPA,NBEQUIDENT,INDIC_NBEQUIDENT,NBSALLES,INDIC_NBSALLES,NBLIEUX,INDIC_NBLIEUX,NB_PDC,INDIC_NB_PDC,NB_PDC_PA,INDIC_NB_PDC_PA,NB_PDC_ACCELEREE,INDIC_NB_PDC_ACCELEREE,NB_PDC_LENTE,INDIC_NB_PDC_LENTE,NB_PDC_RAPIDE,INDIC_NB_PDC_RAPIDE,NB_PDC_ULTRARAPIDE,INDIC_NB_PDC_ULTRARAPIDE,NB_JOURS_OUVERT,INDIC_NB_JOURS_OUVERT,LAMBERT_X,LAMBERT_Y,LONGITUDE,LATITUDE,QUALITE_XY,EPSG,QUALITE_GEOLOC,TR_DIST_PRECISION,DCIRIS,QUALI_IRIS,IRISEE,QP2024,QUALI_QP2024,QVA,QUALI_QVA,ZUS,QUALI_ZUS,EPCI,UU2020,BV2022,AAV2020,DENS3,DENS7
1728937,2024,PF READAPTATION SOCIALE ADOLESCENTS,,77,,AV,DU CHATEAU D EAU,,33700,33281,33,75,MÉRIGNAC,D,D7,D701,77558666200535,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,103.0,1,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,411441.34,6423911.91,-0.653744,44.854283,B,2154,11,< 100,332810203,1,1,HZ,1,HZ,1,HZ,1,243300316,33701,33063,006,1,1
1728938,2024,STEMO GIRONDE OUEST - UEMO MERIGNAC,,3,,AV,DU CHATEAU D EAU,,33700,33281,33,75,MÉRIGNAC,D,D7,D702,17330131800114,O,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,412065.33,6423718.16,-0.645741,44.852800,B,2154,11,< 100,332810203,1,1,HZ,1,HZ,1,HZ,1,243300316,33701,33063,006,1,1
1728939,2024,FOYER SOLEIL,,,,AV,DE LA MARNE,,33700,33281,33,75,MÉRIGNAC,D,D7,D710,,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,412450.00,6421550.00,-0.639613,44.833460,M,2154,12,>= 500,332811002,2,1,HZ,1,HZ,2,HZ,1,243300316,33701,33063,006,1,1
1728940,2024,FOYER SOLEIL,,7,,RUE,LEO LAGRANGE,,33700,33281,33,75,MÉRIGNAC,D,D7,D710,,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,412771.73,6422081.50,-0.635856,44.838374,B,2154,11,< 100,332811002,1,1,HZ,1,HZ,1,HZ,1,243300316,33701,33063,006,1,1
1728941,2024,FJT JOLIOT CURIE,,49,,RUE,JOLIOT CURIE,,33700,33281,33,75,MÉRIGNAC,D,D7,D710,,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,_Z,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0,411550.00,6422550.00,-0.651574,44.842080,A,2154,12,[100 - 500[,332810103,1,1,HZ,2,HZ,2,HZ,1,243300316,33701,33063,006,1,1

## Emploi Inclusion

In [3]:
str_inc = pd.read_parquet("../pipeline/cache/raw/structures-inclusion-2026-02-16.parquet")

In [5]:
str_inc.source.unique()

array(['action-logement', 'carif-oref', 'dora', 'emplois-de-linclusion',
       'mes-aides', 'fredo', 'france-travail', 'ma-boussole-aidants',
       'mediation-numerique', 'reseau-alpha', 'monenfant', 'cd35',
       'mission-locale'], dtype=object)

In [6]:
str_inc = str_inc[str_inc.source == 'emplois-de-linclusion']
str_inc.head()

,id,siret,nom,commune,code_postal,code_insee,adresse,complement_adresse,longitude,latitude,telephone,courriel,site_web,description,source,date_maj,lien_source,horaires_accueil,accessibilite_lieu,reseaux_porteurs
70,emplois-de-linclusion--5d75577e-7bd8-4231-a815...,53054514400061,ACTT EMPLOIS,Chambéry,73000,73065,1 Rue Francois Charvet,None,5.924299,45.567141,None,None,None,None,emplois-de-linclusion,2025-09-20,None,None,None,None
216,emplois-de-linclusion--43ef682c-e8dc-4c40-b87c...,26220391200015,CENTRE COMMUNAL D'ACTION SOCIALE DE PLOUGRESCANT,Plougrescant,22820,22218,4 Place de la Mairie,None,-3.228307,48.842234,+33296925118,ccas@plougrescant.fr,None,None,emplois-de-linclusion,2026-01-09,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,[ccas-cias]
217,emplois-de-linclusion--5d8f7dae-ee45-4a30-bcc7...,21270681600015,COMMUNE DE VERNON,None,None,None,None,None,NaN,NaN,None,None,None,None,emplois-de-linclusion,2022-06-21,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,[ccas-cias]
228,emplois-de-linclusion--441710b4-ca01-4a09-8a0d...,75115816300020,Rod Services,Hésingue,68220,68135,2 Rue de Colmar,None,7.517531,47.584485,+33953930630,None,None,None,emplois-de-linclusion,2020-12-14,https://emplois.inclusion.beta.gouv.fr/company...,None,None,[ea]
229,emplois-de-linclusion--0061e0e4-0425-4247-9642...,44223178300014,Videal 78,None,None,None,None,None,NaN,NaN,+33130985825,rh.v78@groupevideal.net,https://www.videal78-apr2.fr/,"Implantée à Bonnières-sur-Seine, VIDEAL 78 se ...",emplois-de-linclusion,2026-01-07,https://emplois.inclusion.beta.gouv.fr/company...,None,None,[ea]

In [20]:
import numpy as np
np.unique(np.concatenate(str_inc.reseaux_porteurs.dropna().values))

array(['aci', 'afpa', 'ase', 'caarud', 'cada', 'caf',
       'cap-emploi-reseau-cheops', 'cava', 'ccas-cias', 'chrs', 'chu',
       'cidff', 'cph', 'csapa', 'departements', 'ea', 'eatt',
       'ecoles-de-la-deuxieme-chance', 'ei', 'eiti', 'epide', 'etti',
       'france-travail', 'geiq', 'huda', 'mission-locale',
       'mutualite-sociale-agricole', 'pjj', 'plie', 'residences-fjt',
       'spip'], dtype=object)

In [27]:
str_inc.head()

,id,siret,nom,commune,code_postal,code_insee,adresse,complement_adresse,longitude,latitude,telephone,courriel,site_web,description,source,date_maj,lien_source,horaires_accueil,accessibilite_lieu,reseaux_porteurs
70,emplois-de-linclusion--5d75577e-7bd8-4231-a815...,53054514400061,ACTT EMPLOIS,Chambéry,73000,73065,1 Rue Francois Charvet,None,5.924299,45.567141,None,None,None,None,emplois-de-linclusion,2025-09-20,None,None,None,None
216,emplois-de-linclusion--43ef682c-e8dc-4c40-b87c...,26220391200015,CENTRE COMMUNAL D'ACTION SOCIALE DE PLOUGRESCANT,Plougrescant,22820,22218,4 Place de la Mairie,None,-3.228307,48.842234,+33296925118,ccas@plougrescant.fr,None,None,emplois-de-linclusion,2026-01-09,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,[ccas-cias]
217,emplois-de-linclusion--5d8f7dae-ee45-4a30-bcc7...,21270681600015,COMMUNE DE VERNON,None,None,None,None,None,NaN,NaN,None,None,None,None,emplois-de-linclusion,2022-06-21,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,[ccas-cias]
228,emplois-de-linclusion--441710b4-ca01-4a09-8a0d...,75115816300020,Rod Services,Hésingue,68220,68135,2 Rue de Colmar,None,7.517531,47.584485,+33953930630,None,None,None,emplois-de-linclusion,2020-12-14,https://emplois.inclusion.beta.gouv.fr/company...,None,None,[ea]
229,emplois-de-linclusion--0061e0e4-0425-4247-9642...,44223178300014,Videal 78,None,None,None,None,None,NaN,NaN,+33130985825,rh.v78@groupevideal.net,https://www.videal78-apr2.fr/,"Implantée à Bonnières-sur-Seine, VIDEAL 78 se ...",emplois-de-linclusion,2026-01-07,https://emplois.inclusion.beta.gouv.fr/company...,None,None,[ea]

In [40]:
str_inc['reseau'] = str_inc['reseaux_porteurs'].tolist()
str_inc['reseau'].head()

70            None
216    [ccas-cias]
217    [ccas-cias]
228           [ea]
229           [ea]
Name: reseau, dtype: object

In [38]:
str_inc.head(20)

,id,siret,nom,commune,code_postal,code_insee,adresse,complement_adresse,longitude,latitude,...,courriel,site_web,description,source,date_maj,lien_source,horaires_accueil,accessibilite_lieu,reseaux_porteurs,reseau
70,emplois-de-linclusion--5d75577e-7bd8-4231-a815...,53054514400061,ACTT EMPLOIS,Chambéry,73000,73065,1 Rue Francois Charvet,None,5.924299,45.567141,...,None,None,None,emplois-de-linclusion,2025-09-20,None,None,None,None,None
216,emplois-de-linclusion--43ef682c-e8dc-4c40-b87c...,26220391200015,CENTRE COMMUNAL D'ACTION SOCIALE DE PLOUGRESCANT,Plougrescant,22820,22218,4 Place de la Mairie,None,-3.228307,48.842234,...,ccas@plougrescant.fr,None,None,emplois-de-linclusion,2026-01-09,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,[ccas-cias],None
217,emplois-de-linclusion--5d8f7dae-ee45-4a30-bcc7...,21270681600015,COMMUNE DE VERNON,None,None,None,None,None,NaN,NaN,...,None,None,None,emplois-de-linclusion,2022-06-21,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,[ccas-cias],None
228,emplois-de-linclusion--441710b4-ca01-4a09-8a0d...,75115816300020,Rod Services,Hésingue,68220,68135,2 Rue de Colmar,None,7.517531,47.584485,...,None,None,None,emplois-de-linclusion,2020-12-14,https://emplois.inclusion.beta.gouv.fr/company...,None,None,[ea],None
229,emplois-de-linclusion--0061e0e4-0425-4247-9642...,44223178300014,Videal 78,None,None,None,None,None,NaN,NaN,...,rh.v78@groupevideal.net,https://www.videal78-apr2.fr/,"Implantée à Bonnières-sur-Seine, VIDEAL 78 se ...",emplois-de-linclusion,2026-01-07,https://emplois.inclusion.beta.gouv.fr/company...,None,None,[ea],None
230,emplois-de-linclusion--02eacb83-1ad3-42c5-a705...,48487395500021,Envie 2E Lesquin,Lesquin,59810,59343,Boulevard Thomson,None,3.119390,50.589855,...,None,None,None,emplois-de-linclusion,2026-01-10,https://emplois.inclusion.beta.gouv.fr/company...,None,None,[ei],None
231,emplois-de-linclusion--0372d67d-0667-4b63-9fc5...,21590291700016,COMMUNE D HAUTMONT,Hautmont,59330,59291,15 Place du Général de Gaulle,None,3.920303,50.250731,...,None,None,None,emplois-de-linclusion,2021-08-18,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,[ccas-cias],None
232,emplois-de-linclusion--04e4a73d-50d4-4857-9785...,31031106300120,ASSOCIATION PASSERELLES,La Roche-sur-Yon,85000,85191,79 Rue sadi carnot,None,-1.420226,46.670647,...,None,None,None,emplois-de-linclusion,2026-02-06,None,None,None,None,None
233,emplois-de-linclusion--0538134f-3528-4245-9c1c...,34061224100034,Association Le Relais pour l'Emploi AI RETIERS,Retiers,35240,35239,6 Rue Pasteur,None,-1.379727,47.912569,...,contact@lerelaispourlemploi.fr,https://www.lerelaispourlemploi.fr/,Ensemblier d'insertion sur le pays de Vitré,emplois-de-linclusion,2026-02-15,https://emplois.inclusion.beta.gouv.fr/company...,None,None,None,None
234,emplois-de-linclusion--05efeea8-4fdc-4ebd-9225...,39041272400093,TECXELL INTERIM,Paris,75012,75056,37 Rue de Lyon,None,2.370979,48.848492,...,None,None,None,emplois-de-linclusion,2024-01-12,None,None,None,None,None
235,emplois-de-linclusion--06f111a3-8564-4a7f-a6f3...,30542045700114,COMITE D'ACCEUIL CREUSOIS,Guéret,23000,23096,7 Rue de Londres,None,1.869985,46.171607,...,None,None,None,emplois-de-linclusion,2021-08-18,None,None,None,None,None
236,emplois-de-linclusion--07056021-a21e-40bc-bb7a...,77564183000952,ARSEA,Hœnheim,67800,67204,17 Route de la Wantzenau,ARSEA/SESAME,7.764136,48.631765,...,None,None,None,emplois-de-linclusion,2025-12-08,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,[chrs],None
237,emplois-de-linclusion--0727f9a9-e861-4e34-bf75...,26250640500030,CENTRE COMMUNAL D'ACTION SOCIALE,Pontarlier,25300,25462,6 Rue des Capucins,COMPLEXE DES CAPUCINS,6.350273,46.906853,...,None,None,None,emplois-de-linclusion,2021-08-18,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,[ccas-cias],None
238,emplois-de-linclusion--0778c8d9-7dc7-48cf-babb...,26850446100073,CENTRE INTERCOMMUNAL D ACTION SOCIALE DU PAYS ...,Chantonnay,85110,85051,65 Avenue du général de gaulle,None,-1.044430,46.697501,...,None,None,None,emplois-de-linclusion,2023-01-24,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,[ccas-cias],None
239,emplois-de-linclusion--0832f71a-c5d7-456b-b884...,51442092600024,Entreprise OCRE,None,None,None,None,None,NaN,NaN,...,secretariat@ocre56.fr,https://www.ocre56.fr/,OCRE est une association agréée Entreprise d'i...,emplois-de-linclusion,2025-09-11,https://emplois.inclusion.beta.gouv.fr/company...,None,None,[ei],None
240,emplois-de-linclusion--0963c301-a121-4560-9e5a...,13000548124655,France Travail - CAGNES -SUR-MER,Cagnes-sur-Mer,06800,06027,84 Avenue de Grasse,Les Jardins d'Auguste,7.133687,43.659670,...,ape.06370@francetravail.fr,None,None,emplois-de-linclusion,2026-01-11,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,[france-travail],None
241,emplois-de-linclusion--0b4fbdee-2c7b-48e8-9a38...,33868743700024,CENTRE SOCIAL L AGORA,Marseille,13014,13055,Rue de la busserine,None,5.398081,43.331995,...,None,None,None,emplois-de-linclusion,2022-10-21,None,None,None,None,None
242,emplois-de-linclusion--0c30fd18-d965-4a3d-901d...,20001057700019,CENTRE SOCIAL ET CULTUREL DE LA VILLE DE BEGLE...,Bègles,33130,33039,77 Rue Calixte Camelle,MAIRIE,-0.543574,44.808414,...,None,None,None,emplois-de-linclusion,2025-12-21,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,None,None
243,emplois-de-linclusion--0e183111-c702-4191-8eb2...,82422814200579,AGENCE NATIONALE POUR LA FORMATION PROFESSIONN...,Marseille,13011,13055,Chemin de la clue,None,5.503575,43.309486,...,None,None,None,emplois-de-linclusion,2025-09-12,https://emplois.inclusion.beta.gouv.fr/prescri...,None,None,[afpa],None
244,emplois-de-linclusion--1053e634-2082-4b75-bee0...,26190312400202,Epicerie solidaire - CCAS de Brive,Brive-la-Gaillarde,19100,19031,22 Rue Berlioz,None,1.538429,45.167264,...,None,None,None,emplois-de-linclusion,2025-12-23,https://emplois.inclusion.beta.gouv.fr/company...,None,None,[aci],None

In [89]:
str_inc[str_inc.siret == '42427569100055'].code_insee.item()

'33318'

In [95]:
str_inc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16770 entries, 70 to 81735
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  16770 non-null  object
 1   siret               15788 non-null  object
 2   nom                 16770 non-null  object
 3   commune             15167 non-null  object
 4   code_postal         15167 non-null  object
 5   code_insee          15167 non-null  object
 6   adresse             15160 non-null  object
 7   complement_adresse  3770 non-null   object
 8   longitude           15167 non-null  float64
 9   latitude            15167 non-null  float64
 10  telephone           8960 non-null   object
 11  courriel            8216 non-null   object
 12  site_web            4531 non-null   object
 13  description         6426 non-null   object
 14  source              16770 non-null  object
 15  date_maj            16770 non-null  object
 16  lien_source         13570 non-null  object
 17  horaires_accueil    0 non-null      object
 18  accessibilite_lieu  0 non-null      object
 19  reseaux_porteurs    11764 non-null  object
 20  reseau              11764 non-null  object
dtypes: float64(2), object(19)
memory usage: 3.3+ MB

## Emploi Inclusion API

### Pilot

In [54]:
import requests
import json

# Your session ID extracted from browser DevTools
SESSION_ID = "8q1swr6fzqf3vrn4ihnyo5j2wy39vx8i" 
DEPARTEMENT_CODE = '33'

In [71]:


url = "https://emplois.inclusion.beta.gouv.fr/api/v1/oas3/"

# Optional parameters: format (json or yaml), lang
params = {
    "format": "json"
}

headers = {
    "Cookie": f"sessionid={SESSION_ID}",
    "Accept": "application/json"
}

response = requests.get(url, headers=headers, params=params)

if response.status_code == 200:
    # If the response is large, you might want to save it to a file
    schema = response.json()
    print(f"Successfully retrieved schema. Title: {schema.get('info', {}).get('title')}")
    
    # Save to file for examination
    with open("api_schema.json", "w", encoding="utf-8") as f:
        json.dump(schema, f, indent=2, ensure_ascii=False)
else:
    print(f"Error {response.status_code}: {response.text}")

Successfully retrieved schema. Title: API - Les emplois de l'inclusion

In [ ]:
url = "https://emplois.inclusion.beta.gouv.fr/api/v1/siaes/"
params = {
    # "code_insee": "33063",
    # "distance_max_km": 100, # Autiliser avec code insee
    "postes_dans_le_departement": '33' 
}
headers = {
    "Cookie": f"sessionid={SESSION_ID}",
    "Accept": "application/json"
}
response = requests.get(url, headers=headers, params=params)
if response.status_code == 200:
    data = response.json()
    results = data.get('results', [])
    results_df = pd.DataFrame(columns=['codgeo', 'siae_siret', 'siae_type', 'siae_name', 'rome', 'postes'])
    
    # Filter in Python to be 100% sure we only show those with 'postes' list
    hiring_structures = [s for s in results if len(s.get('postes', [])) > 0]
    
    # print(f"Found {len(hiring_structures)} hiring structures near Paris.")
    for siae in hiring_structures:
        # 'enseigne' is the commercial name; 'raison_sociale' is the legal name
        name = siae.get('enseigne') or siae.get('raison_sociale')
        postes = siae.get('postes', [])
        
        # print(f"\nStructure: {name}")
        # print(f"Job openings: {len(postes)}")
        for p in postes:
            # Fallback if the personalized title is empty
            title = p.get('appellation_modifiee') or f"Job position (ROME: {p.get('rome')})"

            lieu = p.get('lieu')
            code_insee = lieu.get('code_insee') if lieu else str_inc[str_inc.siret == siae.get('siret')].code_insee.item()
            results_df.loc[len(results_df)] = [
                code_insee,
                siae.get('siret'),
                siae.get('type'),
                siae.get('raison_sociale'),
                p.get('rome'),
                p.get('nombre_postes_ouverts')
            ]
            # print(f" - {title}")
else:
    print(f"Error {response.status_code}: {response.text}")

In [94]:
results_df.head(20)

,codgeo,siae_siret,siae_type,siae_name,rome,postes
0,33063,42427569100055,ETTI,ALLIANCE RIVE GAUCHE,Conseiller / Conseillère clientèle à distance (D1408),1
1,33555,42427569100055,ETTI,ALLIANCE RIVE GAUCHE,Manœuvre bâtiment (F1704),1
2,33318,42427569100055,ETTI,ALLIANCE RIVE GAUCHE,Electricien / Electricienne de maintenance (I1309),1
3,33063,42887866400039,ETTI,LIEN INTERIM INSERTION L2I,Manœuvre bâtiment (F1704),1
4,33063,42887866400039,ETTI,LIEN INTERIM INSERTION L2I,Ouvrier / Ouvrière en voiries (F1702),1
5,85191,49239950600079,ETTI,SITI INTERIM,Coffreur / Coffreuse (F1701),3
6,85155,49239950600079,ETTI,SITI INTERIM,Menuisier / Menuisière (H2206),2
7,33314,50010961600028,ETTI,RELAIS AVENIR,Manœuvre bâtiment (F1704),1
8,33314,50010961600028,ETTI,RELAIS AVENIR,Manœuvre bâtiment (F1704),1
9,33063,50010961600028,ETTI,RELAIS AVENIR,Manœuvre bâtiment (F1704),1
10,33366,50010961600028,ETTI,RELAIS AVENIR,Manœuvre bâtiment (F1704),1
11,33366,50010961600028,ETTI,RELAIS AVENIR,Poseur / Poseuse de canalisations (F1705),1
12,24037,77556319000402,ETTI,APLB C3I - Sainte Foy la Grande,Conseiller / Conseillère en assurances (C1102),1
13,24037,77556319000402,ETTI,APLB C3I - Sainte Foy la Grande,Conseiller commercial / Conseillère commerciale auprès des particuliers (D1403),1
14,33039,30016423300037,ACI,FIL DE FAIRE AFEPT CJ,Métallier / Métallière (H2911),1
15,33030,31241056600086,ACI,COMITE ETUDE INFORMATION DROGUE,Agent / Agente d'entretien des espaces verts (A1203),1
16,33522,33797565000017,AI,ASSOC REAGIR,Employé familial / Employée familiale (K1304),1
17,33039,33797565000017,AI,ASSOC REAGIR,Agent / Agente d'entretien du bâtiment (I1203),1
18,33122,33797565000017,AI,ASSOC REAGIR,Agent / Agente d'exploitation de la voirie (I1202),1
19,33522,33797565000017,AI,ASSOC REAGIR,Agent / Agente de propreté de locaux (K2205),1

In [92]:
results_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 84 entries, 0 to 83
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   codgeo      84 non-null     object
 1   siae_siret  84 non-null     object
 2   siae_type   84 non-null     object
 3   siae_name   84 non-null     object
 4   rome        84 non-null     object
 5   postes      84 non-null     int64
dtypes: int64(1), object(5)
memory usage: 4.6+ KB

In [67]:
results

[{'id': 'f8d8b6a0-7e2c-4d0b-ad21-2e9083335e98',
  'cree_le': '2019-12-05T15:37:56.609676+01:00',
  'mis_a_jour_le': '2026-02-03T10:00:14.854733+01:00',
  'siret': '40998663500020',
  'type': 'ETTI',
  'raison_sociale': 'ASSOC HAUTS DE GARONNE INTERIM INSERTION',
  'enseigne': 'HAUTS DE GARONNE INTERIM INSERTION',
  'telephone': '05 57 77 31 31',
  'courriel': 'direction@aihg.fr',
  'site_web': 'https://aihg.fr',
  'description': "AGENCE INTERIM D'INSERTION\r\n\r\nPOSTES PROPOSES:\r\n-Manoeuvre Batiment\r\n-Manoeuvre TP\r\n-Ouvrier Polyvalent du Bâtiment",
  'bloque_candidatures': False,
  'addresse_ligne_1': 'Avenue Gay-lussac',
  'addresse_ligne_2': '',
  'code_postal': '33370',
  'ville': 'Artigues-près-Bordeaux',
  'departement': '33',
  'postes': []},
 {'id': '7d61d674-2cef-46e8-8a3b-97ed6d46e97b',
  'cree_le': '2019-12-05T15:37:56.609676+01:00',
  'mis_a_jour_le': '2026-01-31T10:00:08.264137+01:00',
  'siret': '42160742500046',
  'type': 'ETTI',
  'raison_sociale': 'INTERIM 33',
  'enseigne': 'INTERIM 33 COUTRAS',
  'telephone': '0557493087',
  'courriel': 'contact@interim33coutras.fr',
  'site_web': 'http://interim33coutras.fr',
  'description': "Située à Coutras près de Libourne en Gironde, notre agence INTERIM 33, entreprise de travail temporaire d'insertion, vous propose principalement des missions dans les domaines suivants :\r\n-\tLe bâtiment\r\n-\tLes travaux publics\r\n-\tL’industrie\r\n-\tLa viticulture\r\n-       Le tri des déchets\r\n-       Le nettoyage\r\n-       La logistique\r\nNotre équipe permanente de 3 salariés vous accompagne au quotidien depuis plus de  20 ans.\r\n Aujourd'hui en SCOP, nous mettons en avant l'importance des valeurs humaines pour pouvoir avancer : nous privilégions le partage, le contact et la communication.\r\nNotre objectif : dès la première rencontre, tisser des liens solides pour une collaboration pérenne.\r\nProfessionnels du travail temporaire, notre statut d'ETTI (Entreprise de travail temporaire d'insertion) conventionnée par l'État nous démarque d'une agence d'intérim classique car notre objectif est double : vous assurer le meilleur service tout en favorisant l'inclusion.",
  'bloque_candidatures': False,
  'addresse_ligne_1': '26 Rue Jean Zay',
  'addresse_ligne_2': '',
  'code_postal': '33230',
  'ville': 'COUTRAS',
  'departement': '33',
  'postes': []},
 {'id': '6d20ebe5-970c-45f3-b181-13594ac2baf6',
  'cree_le': '2019-12-05T15:37:56.609676+01:00',
  'mis_a_jour_le': '2025-12-18T10:21:17.054045+01:00',
  'siret': '42427569100055',
  'type': 'ETTI',
  'raison_sociale': 'ALLIANCE RIVE GAUCHE',
  'enseigne': 'ALLIANCE RIVE GAUCHE',
  'telephone': '05.56.15.05.90',
  'courriel': 'contact@alliance-rive-gauche.fr',
  'site_web': 'https://www.alliance-rive-gauche.fr/',
  'description': "Entreprise de travail temporaire d'insertion,  nous avons comme activité exclusive l'insertion des personnes sans emploi rencontrant des difficultés sociales et professionnelles particulières (loi du 29/07/1998, article L322-4-16).\r\nNous mettons à disposition des intérimaires auprès d'entreprises diverses ( bâtiment, travaux publics, industrie, logistique, nettoyage,...) et nous les accompagnons dans et vers l'emploi. \r\nLa mise au travail permet de développer la confiance en soi et les compétences ( soft skills et hard skills). L’accompagnement individualisé permet de co-construire un projet et de travailler sur les freins périphériques. Il se fait en partenariat avec les acteurs de l'emploi et sur une durée de 24 mois maximum.\r\nNous intervenons à PESSAC et sur le secteur de Bordeaux Métropole élargi.\r\nNous proposons des contrats de missions variables en fonction de la demande de l'entreprise utilisatrice.\r\nExemple de postes: (liste non exhaustive)\r\nManœuvre bâtiment gros œuvre et second œuvre\r\nManœuvre TP\r\nHomme trafic\r\nManutentionnaire\r\nOuvrier de nettoyage\r\nOuvrier paysagiste\r\nMichel Morin\r\nArchivage et Secrétariat\r\nConseiller(e) client",
  'bloque_candidatures': False,
  'addresse_ligne_1': '12 AVENUE LEONARD DE VINCI',
  'addresse_ligne_2': '',
  'code_postal': '33600',
  'ville': 'PESSAC',
  'departement': '33',
  'postes': [{'id': 11495,
    'rome': 'Conseiller / Conseillère clientèle à distance (D1408)',
    'cree_le': '2020-12-07T16:03:16.170157+01:00',
    'mis_a_jour_le': '2026-02-16T10:57:23.253205+01:00',
    'recrutement_ouvert': 'True',
    'description': "Vous assurez le traitement de bout en bout des demandes des clients dans une démarche permanente de développement de la satisfaction client sur tous types de clients B2B.\r\nVous assurez la mise en place et le respect des conditions contractuelles particulières dans les systèmes et la cohérence des données sur le parc client \r\nVous garantissez le traitement de bout en bout des demandes administratives des clients sur les offres de téléphonie mobile et fixe \r\nVous analysez les demandes et réclamations et en assurez le traitement en conformité avec les procédures, identifiez et formalisez les dysfonctionnements lors des demandes clients \r\nVous respectez les standards qualités afin de contribuer à l'image de marque de la société et contribuez à la fidélisation et à la satisfaction des clients au travers d'une information adaptée à leurs besoins et un conseil individualisé. \r\nVous participez aux différents pilotes et projets de l'activité, assurez la remontée d'information utile et pertinente à l'activité et informez régulièrement et à bon escient son responsable des demandes particulières des clients/distributeurs, des dysfonctionnements constatés, des pistes d'optimisation, etc. \r\nEnfin, vous renseignez les bases de données internes et garantissez l'intégrité et la confidentialité des informations enregistrées concernant les historiques des contacts clients afin de garantir une personnalisation de la relation.",
    'appellation_modifiee': '',
    'type_contrat': 'Contrat de mission intérimaire',
    'nombre_postes_ouverts': 1,
    'lieu': {'nom': 'Bordeaux',
     'departement': '33',
     'code_postaux': ['33000', '33100', '33200', '33300', '33800'],
     'code_insee': '33063'},
    'profil_recherche': "Gérer les appels téléphoniques entrants\r\nIdentifier, traiter une demande client\r\nMaintenir une veille informationnelle continue\r\nProposer des solutions adaptées à la demande du client\r\nPrésenter et valoriser un produit ou un service\r\nRespecter les procédures et les normes de qualité\r\nRépondre aux appels téléphoniques\r\nRépondre aux demandes d'information\r\nSuivre les dossiers clients jusqu'à résolution\r\nAdapter sa communication selon l'interlocuteur\r\nAssurer la confidentialité des informations client\r\n\r\nCapacité d'adaptation\r\nGestion du stress\r\nMaîtrise de l'outil informatique\r\nPrincipes de la relation client\r\n\r\n\r\nBureautique et outils collaboratifs\r\nConnaissance des Nouvelles Technologies de l'information et de la Communication (NTIC)\r\nTechniques de communication orales, écrites et numériques\r\n\r\nCréer une relation de confiance\r\nEffectuer un reporting régulier à la hiérarchie\r\nGestion du temps\r\n\r\n\r\nSavoir-être professionnels\r\n\r\nAvoir l'esprit d'équipe\r\nFaire preuve d'autonomie\r\nFaire preuve de contrôle de soi"},
   {'id': 4265,
    'rome': 'Manœuvre bâtiment (F1704)',
    'cree_le': '2020-08-12T16:41:38.495317+02:00',
    'mis_a_jour_le': '2026-02-16T10:38:16.798198+01:00',
    'recrutement_ouvert': 'True',
    'description': "vous travaillez en équipe et vous aidez le maçon dans ses taches au quotidien et selon l'avancée du chantier\r\napprovisionnement de chantier\r\nmaconnerie\r\nnettoyage de chantier",
    'appellation_modifiee': '',
    'type_contrat': 'Contrat de mission intérimaire',
    'nombre_postes_ouverts': 1,
    'lieu': {'nom': 'Marcheprime',
     'departement': '33',
     'code_postaux': ['33380'],
     'code_insee': '33555'},
    'profil_recherche': 'compétences en maconnerie\r\ntravail en équipe\r\ngestion des risques \r\nrespect des regles et des consignes de sécurité\r\nbonne communication orale\r\n\r\ngestion de ses déplacements: mission non desservie par les transports en commun'},
   {'id': 11296,
    'rome': 'Electricien / Electricienne de maintenance (I1309)',
    'cree_le': '2020-12-03T15:29:10.385261+01:00',
    'mis_a_jour_le': '2026-01-16T10:19:32.196513+01:00',
    'recrutement_ouvert': 'True',
    'description': "Effectuer la maintenance préventive ou corrective d'équipements ou d'installations électriques, selon les règles de sécurité et la réglementation.\r\nEffectuer des opérations d'installation ou de modification de matériels électriques.\r\nPréparer du matériel en prévision d'un travail\r\nRéaliser une intervention nécessitant une habilitation\r\nTravailler en équipe\r\nOrganiser son travail selon les priorités et les objectifs\r\nFaire preuve de rigueur et de précision\r\nRespecter les consignes et les regles de sécurité",
    'appellation_modifiee': 'ELECTRICIEN / AIDE ELECTRICIEN',
    'type_contrat': 'Contrat de mission intérimaire',
    'nombre_postes_ouverts': 1,
    'lieu': None,
    'profil_recherche': "Vous êtes motivé et avez une expérience dans ce domaine. \r\nVous possédez les habilitations en cours de validité.\r\nVous souhaitez continuer d'apprendre et vous former en situation de travail.\r\nVous avez une bonne communication orale.\r\nVous avez besoin d'un accompagnement  pour affiner votre projet professionnel, rejoignez l'équipe d'ARG qui vous accompagnera vers et dans l'emploi"}]},
 {'id': '22d10688-9325-4287-b7ab-102ec4a15121',
  'cree_le': '2019-12-05T15:37:56.609676+01:00',
  'mis_a_jour_le': '2023-11-14T10:52:39.847189+01:00',
  'siret': '42453392500022',
  'type': 'ETTI',
  'raison_sociale': 'ETTI SUD GIRONDE',
  'enseigne': 'ETTI SUD GIRONDE',
  'telephone': '0556612007',
  'courriel': 'etti33190@orange.fr',
  'site_web': 'http://inter-emploi-ettisg.fr',
  'description': "L'ETTI SUD GIRONDE est une entreprise de Travail Temporaire d'Insertion qui intervient sur le territoire de la Gironde mais plus précisément sur l'Entre deux mers et le Sud Gironde. L’entreprise de travail temporaire d’insertion a ceci de particulier que son activité est entièrement centrée sur l’insertion professionnelle des personnes en difficulté. Elle leur propose des missions auprès d’entreprises utilisatrices, mais également un suivi et un accompagnement social et professionnel, pendant et en dehors des missions.\r\nNous sommes disponibles pour étudier avec les entreprises utilisatrices toutes les missions de premier niveau de qualification.",
  'bloque_candidatures': False,
  'addresse_ligne_1': '15 Rue des Frères Faucher',
  'addresse_ligne_2': '',
  'code_postal': '33190',
  'ville': 'La Réole',
  'departement': '33',
  'postes': []},
 {'id': '64073350-a7be-4d0d-9e70-7e0572b40492',
  'cree_le': '2019-12-05T15:37:56.609676+01:00',
  'mis_a_jour_le': '2026-02-01T10:00:09.036085+01:00',
  'siret': '42887866400039',
  'type': 'ETTI',
  'raison_sociale': 'LIEN INTERIM INSERTION L2I',
  'enseigne': 'Lien interim insertion l2i',
  'telephone': '0556065448',
  'courriel': 'contact@lien-interim-insertion.fr',
  'site_web': 'https://www.lien-interim-insertion.fr/',
  'description': "LIEN INTERIM INSERTION : L2i - vous accompagne dans le domaine de la Mise à Disposition de personnel adapté à vos besoins (sur toute la métropole Bordelaise) sur des postes de manoeuvres, manutentionnaires, agents logistique, agent d'entretien, et bien d'autres qualifications. Nous assurons une relation étroite (grâce à un accompagnement personnalisé) avec nos intérimaires pour satisfaire au mieux vos exigences.\r\n\r\nNous vous accompagnons, également dans tout vos chantiers incluant une                               clause sociale.\r\n\r\nNous nous ferons un plaisir de vous renseigner. \r\nContactez-nous au 05 56 06 54 48 \r\nou à l'adresse suivante : contact@lien-interim-insertion.fr",
  'bloque_candidatures': False,
  'addresse_ligne_1': '9 Rue des Garosses',
  'addresse_ligne_2': '',
  'code_postal': '33310',
  'ville': 'Lormont',
  'departement': '33',
  'postes': [{'id': 988,
    'rome': 'Manœuvre bâtiment (F1704)',
    'cree_le': '2020-04-01T11:34:27.907052+02:00',
    'mis_a_jour_le': '2025-12-08T14:38:26.810639+01:00',
    'recrutement_ouvert': 'True',
    'description': "Vous êtes à la recherche d'un emploi dans le domaine du Bâtiment (Gros oeuvre / Second oeuvre).\r\nNous recrutons en permanence des débutants qui souhaitent découvrir et/ou s'investirent dans les métiers du bâtiment. Notre accompagnatrice socio-professionnel pourra vous positionner sur un poste qui vous ressemble.\r\nContactez nous au 05 56 06 54 48, (contact@lien-interim-insertion.fr) ou postulez sur notre site : https://www.lien-interim-insertion.fr/offres-d-emplois/",
    'appellation_modifiee': 'Manoeuvre bâtiment H/F',
    'type_contrat': 'Contrat de mission intérimaire',
    'nombre_postes_ouverts': 1,
    'lieu': {'nom': 'Bordeaux',
     'departement': '33',
     'code_postaux': ['33000', '33100', '33200', '33300', '33800'],
     'code_insee': '33063'},
    'profil_recherche': ''},
   {'id': 994,
    'rome': 'Ouvrier / Ouvrière en voiries (F1702)',
    'cree_le': '2020-04-01T11:57:37.220708+02:00',
    'mis_a_jour_le': '2025-12-08T14:38:24.024459+01:00',
    'recrutement_ouvert': 'True',
    'description': "Vous recherchez un poste dans les métiers des Travaux Publics et/ou, voirie et réseaux divers (VRD).\r\nVenez nous rencontrer directement à l'agence, ou contactez nous au 05 56 06 54 48, (contact@lien-interim-insertion.fr)\r\nN'hésitez à postuler sur notre site : https://www.lien-interim-insertion.fr/offres-d-emplois/",
    'appellation_modifiee': 'Ouvrier VRD-TP  H/F',
    'type_contrat': 'Contrat de mission intérimaire',
    'nombre_postes_ouverts': 1,
    'lieu': {'nom': 'Bordeaux',
     'departement': '33',
     'code_postaux': ['33000', '33100', '33200', '33300', '33800'],
     'code_insee': '33063'},
    'profil_recherche': ''}]},
 {'id': '834ca4c9-36d5-42ad-b85d-052de9739e7b',
  'cree_le': '2019-12-05T15:37:56.609676+01:00',
  'mis_a_jour_le': '2025-12-11T10:00:12.291076+01:00',
  'siret': '49239950600079',
  'type': 'ETTI',
  'raison_sociale': 'SITI INTERIM',
  'enseigne': 'SITI Intérim La Roche sur Yon',
  'telephone': '0251414328',
  'courriel': 'laroche@siti-interim.fr',
  'site_web': 'https://soltiss.fr/services-aux-entreprises/linterim-insertion/',
  'description': 'Siti intérim, entreprise de travail temporaire d’insertion de proximité, au service du territoire fait le lien, grâce à son expertise entre les besoins en recrutement des entreprises et son personnel intérimaire.\r\nNotre plus-value est indéniablement l’accompagnement à la fois des entreprises et des intérimaires pour une mission réussie grâce à une équipe disponible et expérimentée.\r\nNotre mission est de favoriser l’emploi durable via des missions d’intérim, un accompagnement socio professionnel et la formation\r\nSiti Intérim c’est :\r\n- Des conseillers en insertion professionnelle expérimentés, pour accompagner chaque intérimaire pour une insertion sociale et professionnelle durable\r\n- Des agences à taille humaine pour plus de proximité\r\n- Des équipes réactives, à l’écoute et impliquées dans les parcours d’insertion\r\n- Une véritable expertise en ingénierie de Formation\r\nNotre Mission de mise à disposition ne se limite pas qu’aux offres d’emploi que nous pouvons déposer mais nous travaillons également à partir du CV du demandeur d’emploi (de ses particularités, de ses expériences, envies, aptitudes, compétences transférables...)\r\nNotre agence généraliste peut proposer des missions dans divers domaine d’activité comme par exemple :\r\n>> BTP : Maçon traditionnel, Coffreur-bancheur, Etancheur, Bardeur, Maçon finisseur, Maçon, Manœuvre, Menuisier, Ouvrier VRD, Peintre, Plaquiste, Plombier, Solier, Electricien, technicien monteur raccordeur en fibre optique…\r\n>> INDUSTRIE/SERVICES : Agent de collecte, Agent de production, Agent de propreté, Agent de tri, Gardien de déchetterie, chauffeur PL, soudeur…\r\n>> TERTIAIRE : Agent administratif, Agent d’accueil, Secrétaire, Aide comptable, comptable, Assistante commerciale…',
  'bloque_candidatures': False,
  'addresse_ligne_1': '33 Rue du Marechal Juin',
  'addresse_ligne_2': '',
  'code_postal': '85000',
  'ville': 'La Roche-sur-Yon',
  'departement': '85',
  'postes': [{'id': 117650,
    'rome': 'Coffreur / Coffreuse (F1701)',
    'cree_le': '2025-12-05T12:18:07.785555+01:00',
    'mis_a_jour_le': '2025-12-05T12:24:21.859508+01:00',
    'recrutement_ouvert': 'True',
    'description': "Nous recherchons pour un de nos clients des coffreurs bancheurs (H/F) qualifiés pour un chantier à la Roche sur Yon.\r\nVos missions :\r\n\r\n* Mise en place de banches et coffrages\r\n* Pose d'armatures, préparation et coulage de béton\r\n* Décoffrage \r\n* Lecture de plans",
    'appellation_modifiee': 'Coffreur Bancheur',
    'type_contrat': 'Contrat de mission intérimaire',
    'nombre_postes_ouverts': 3,
    'lieu': {'nom': 'La Roche-sur-Yon',
     'departement': '85',
     'code_postaux': ['85000'],
     'code_insee': '85191'},
    'profil_recherche': 'Qualification N3P1  minimum\r\nExpérience confirmée en gros oeuvre/ génie civil'},
   {'id': 97338,
    'rome': 'Menuisier / Menuisière (H2206)',
    'cree_le': '2025-01-16T11:57:33.279610+01:00',
    'mis_a_jour_le': '2025-12-05T11:47:54.108770+01:00',
    'recrutement_ouvert': 'True',
    'description': "SITI INTERIM recherche pour l'un de ses clients spécialisé dans la construction de modulaires 20 menuisiers (h/f)\r\n\r\nDans le cadre de votre mission et sous la responsabilité du chef vous serez amené(e) à effectuer :\r\n-perçage des cloisons pour la pose de l'appareillage électrique\r\n-pose de la menuiserie intérieure : cloisons, plinthes, portes intérieures, équipements, mobilier\r\n-pose de la menuiserie extérieure : ouvertures (possibilité pose d'un barreaudage)\r\n-réalisation de bardages : préparation et fixation de l'ossature du bardage\r\n\r\nVM à jour dans l'idéal\r\n\r\ntravail en équipe 2*8\r\nprime d'équipe\r\nprime de panier repas\r\n\r\n\r\nmission longue",
    'appellation_modifiee': '',
    'type_contrat': 'Contrat de mission intérimaire',
    'nombre_postes_ouverts': 2,
    'lieu': {'nom': 'Mouilleron-le-Captif',
     'departement': '85',
     'code_postaux': ['85000'],
     'code_insee': '85155'},
    'profil_recherche': 'avoir déjà une expérience en menuisserie\r\nêtre mobile de préférence pour se rendre sur site'}]},
 {'id': 'e4de067a-3a24-47d9-898c-f44474afdd8b',
  'cree_le': '2019-12-05T15:37:56.609676+01:00',
  'mis_a_jour_le': '2026-01-29T15:07:51.224064+01:00',
  'siret': '50010961600028',
  'type': 'ETTI',
  'raison_sociale': 'RELAIS AVENIR',
  'enseigne': 'Relais avenir',
  'telephone': '0557435572',
  'courriel': 'asp@relaisemploi33.fr',
  'site_web': 'https://www.relaisemploi33.fr/',
  'description': 'Relais Avenir est une Entreprise de Travail Temporaire d’Insertion (ETTI) implantée à Saint-André-de-Cubzac.\r\nActeur engagé de l’insertion professionnelle sur le territoire, nous accompagnons les demandeurs d’emploi vers un retour durable à l’activité tout en répondant aux besoins en recrutement des entreprises locales.\r\n\r\nNous travaillons en étroite collaboration avec les entreprises afin de leur proposer des profils adaptés, opérationnels et accompagnés, en fonction de leurs besoins ponctuels ou récurrents. Notre démarche s’appuie sur un suivi socioprofessionnel individualisé, favorisant la montée en compétences et l’employabilité des salariés.\r\n\r\nNous intervenons dans les secteurs d’activité suivants :\r\n- Bâtiment et Travaux Publics (BTP)\r\n- Nettoyage\r\n- Espaces verts\r\n- Manutention\r\n- Logistique\r\n- Industrie',
  'bloque_candidatures': False,
  'addresse_ligne_1': '83 Rue Emile Martin Dantagnan',
  'addresse_ligne_2': '',
  'code_postal': '33240',
  'ville': 'Saint-André-de-Cubzac',
  'departement': '33',

### Full results

In [97]:
jobs_inc = pd.read_parquet('../pipeline/cache/output/odis_inclusion_jobs.parquet')
jobs_inc.head()

,codgeo,siae_siret,siae_type,siae_name,rome,postes
0,38315,40231751500037,ETTI,Act interim isere,F1703,1
1,73226,40231751500037,ETTI,Act interim isere,F1701,1
2,38080,40231751500037,ETTI,Act interim isere,H2903,1
3,73226,40231751500037,ETTI,Act interim isere,N1105,1
4,01283,84537825600018,ETTI,Alpy services intérim OYONNAX,I1308,1

In [102]:
jobs_inc[jobs_inc.codgeo == '12089']

,codgeo,siae_siret,siae_type,siae_name,rome,postes
1239,12089,40338118900030,AI,CHORUS,I1203,1
1240,12089,40338118900030,AI,CHORUS,J1301,1
1261,12089,40524380999999,GEIQ,GEIQ BTP 46 - Antenne BRETENOUX,F1605,1
5953,12089,40524380999999,GEIQ,GEIQ BTP 46 - Antenne BRETENOUX,F1605,1

In [101]:
jobs_inc.postes.sum()

np.int64(27278)

## Logements sociaux

In [6]:
rpls = pd.read_parquet('../pipeline/cache/clean/rpls.parquet')
rpls.head()

  codgeo  log_soc_total  log_soc_inoccupes
0  01001             32                1.0
1  01004           2283               96.0
2  01005            113                3.0
3  01007            129                3.0
4  01008             17                1.0

In [10]:
rpls[rpls.log_soc_total > 0].count()

codgeo               16859
log_soc_total        16859
log_soc_inoccupes    16859
dtype: int64

## Top Jobs

In [5]:
odis_ft_jobs_agg.head()

,commune,romeCode,romeLibelle,nb_offres,total_postes,nb_offres_tension
0,01001,H2904,Forgeron industriel / Forgeronne industrielle,1,1,0
1,01002,K1201,Assistant social / Assistante sociale,1,1,0
2,01004,A1203,Agent / Agente d'entretien des espaces verts,1,1,0
3,01004,A1439,Eleveur / Eleveuse d'équidés,1,1,0
4,01004,C1206,Conseiller / Conseillère de clientèle bancaire,1,1,0

In [40]:
odis_ft_jobs_top = odis_ft_jobs_agg.groupby(['romeCode', 'romeLibelle']).agg({'commune': 'count', 'nb_offres': 'sum', 'total_postes': 'sum'})
odis_ft_jobs_top = odis_ft_jobs_top.sort_values(by='total_postes', ascending=False).reset_index()
odis_ft_jobs_top.head(20)

,romeCode,romeLibelle,commune,nb_offres,total_postes
0,K1304,Employé familial / Employée familiale,6178,13123,13354
1,J1501,Aide-soignant / Aide-soignante,3550,10463,10793
2,J1506,Infirmier / Infirmière en soins généraux (IDE),2692,9535,10031
3,M1211,Expert-comptable / Experte-comptable,2193,9255,9265
4,C1504,Conseiller / Conseillère immobilier,2705,9093,9163
5,K1311,Assistant / Assistante de vie aux familles,3684,7888,8156
6,M1203,Comptable,2008,7713,7745
7,D1507,Employé / Employée de rayon libre-service,2362,6543,7041
8,G1609,Cuisinier / Cuisinière,2689,6533,6721
9,H2903,Tourneur-fraiseur / Tourneuse-fraiseuse,1987,6623,6686
10,N1101,Cariste,2245,6348,6502
11,I1304,Technicien / Technicienne de maintenance industrielle,2470,6371,6468
12,N4101,Conducteur / Conductrice de poids lourd,2201,5986,6186
13,I1604,Mécanicien / Mécanicienne automobile,2098,5624,5746
14,G1803,Serveur / Serveuse en restauration,2095,4733,5035
15,F1602,Electricien / Electricienne du bâtiment,1694,4864,4945
16,N1110,Magasinier / Magasinière,2093,4788,4851
17,F1703,Maçon / Maçonne,1996,4611,4681
18,I1203,Agent / Agente d'entretien du bâtiment,2290,4637,4678
19,K1303,Garde d'enfant,2184,3739,4452

In [38]:
odis_ft_jobs_top100 = odis_ft_jobs_top.head(200)

In [39]:
odis_ft_jobs_top100.total_postes.sum() / odis_ft_jobs_top.total_postes.sum()

np.float64(0.7599144337486631)

In [44]:
odis_referentiels[odis_referentiels.key == 'rome_codes'].count()

key         1584
code        1584
label       1584
reg_code       0
dtype: int64

## Services Inclusion

In [47]:
odis_pois.category.unique()

['education', 'sante', 'incl_services', 'hebergement']
Categories (4, object): ['education', 'hebergement', 'incl_services', 'sante']

In [49]:
incl_services = odis_pois[odis_pois.category == 'incl_services']
incl_services.head()

,id,name,type,category,lat,lon,codgeo
67236,f876f250bb119cb7ae22b67e412a93b3,Réparation de voiture,mobilite--entretenir-reparer-son-vehicule,incl_services,48.085732,7.374525,68066
67237,019acc7632f3a02ad0c568047471fbf9,Activités et ateliers,sante--acces-aux-soins,incl_services,-21.362328,55.533840,97416
67238,8d58f421f94e3daac9adf9d8e9492b3e,Accompagnement vers RQTH,sante--constituer-un-dossier-mdph-invalidite,incl_services,43.123566,0.387208,65258
67239,81b602ee62d47a0a840a6a8bb5c251b8,Master 1ère mention français langue étrangère parcours didactique,lecture-ecriture-calcul--maitriser-le-francais,incl_services,47.234482,6.025262,25056
67240,406d3483e2c4698acfc02a2bd7736e13,Accompagnement et formation pour la réacquisition des savoirs de base de la langue française + Alphabétisation,lecture-ecriture-calcul--maitriser-le-francais,incl_services,16.259060,-61.524311,97101

In [ ]:
incl_services_agg = incl_services.groupby('type').agg({'id':'count'}).sort_values(by='id', ascending=False).reset_index()

/var/folders/wb/bg23zgwj389404sv03x64x2m0000gn/T/ipykernel_85936/3336146703.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  incl_services_agg = incl_services.groupby('type').agg({'id':'count'}).sort_values(by='id', ascending=False).reset_index()

,type,id
0,numerique--maitriser-les-fondamentaux-du-numerique,16802
1,numerique--acceder-a-des-services-en-ligne,15908
2,numerique--acquerir-un-equipement,15855
3,numerique--acceder-a-une-connexion-internet,15782
4,difficultes-administratives-ou-juridiques--accompagnement-aux-demarches-administratives,14999

In [51]:
incl_services_agg.head(50)

,type,id
0,numerique--maitriser-les-fondamentaux-du-numerique,16802
1,numerique--acceder-a-des-services-en-ligne,15908
2,numerique--acquerir-un-equipement,15855
3,numerique--acceder-a-une-connexion-internet,15782
4,difficultes-administratives-ou-juridiques--accompagnement-aux-demarches-administratives,14999
5,sante--acces-aux-soins,14228
6,famille--garde-denfants,13081
7,preparer-sa-candidature--organiser-ses-demarches-de-recherche-demploi,12135
8,famille--soutien-a-la-parentalite-et-a-leducation,11162
9,creer-une-entreprise--developper-son-entreprise,11054
10,creer-une-entreprise--definir-son-projet-de-creation-dentreprise,10513
11,lecture-ecriture-calcul--maitriser-le-francais,6014
12,choisir-un-metier--confirmer-son-choix-de-metier,4519
13,logement-hebergement--sinformer-sur-les-demarches-liees-a-lacces-au-logement,3379
14,trouver-un-emploi--repondre-a-des-offres-demploi,3300
15,choisir-un-metier--identifier-ses-points-forts-et-ses-competences,3278
16,logement-hebergement--changer-de-logement,3150
17,preparer-sa-candidature--valoriser-ses-competences,3011
18,mobilite--etre-accompagne-dans-son-parcours-mobilite,3009
19,logement-hebergement--reduire-les-impayes-de-loyer,2835
20,preparer-sa-candidature--realiser-un-cv-et-ou-une-lettre-de-motivation,2803
21,logement-hebergement--rechercher-une-solution-dhebergement-temporaire,2786
22,choisir-un-metier--decouvrir-un-metier-ou-un-secteur-dactivite,2530
23,logement-hebergement--se-maintenir-dans-le-logement,2448
24,trouver-un-emploi--faire-des-candidatures-spontanees,2401
25,logement-hebergement--acheter-un-logement,2383
26,trouver-un-emploi--convaincre-un-recruteur-en-entretien,2380
27,logement-hebergement--louer-un-logement,2376
28,trouver-un-emploi--suivre-ses-candidatures-et-relancer-les-employeurs,2255
29,mobilite--financer-ma-mobilite,1861
30,difficultes-administratives-ou-juridiques--accompagnement-pour-lacces-aux-droits,1720
31,creer-une-entreprise--structurer-son-projet-de-creation-dentreprise,1676
32,trouver-un-emploi--maintien-dans-lemploi,1507
33,mobilite--entretenir-reparer-son-vehicule,1472
34,choisir-un-metier--connaitre-les-opportunites-demploi,1391
35,remobilisation--lien-social,1368
36,mobilite--preparer-un-permis,1339
37,mobilite--acceder-a-un-vehicule,1321
38,remobilisation--bien-etre-confiance-en-soi,1289
39,famille--soutien-aidants,1074
40,difficultes-financieres--acquerir-une-autonomie-budgetaire,1055
41,famille--surmonter-conflits-separation-violence,1006
42,sante--sante-sexuelle,993
43,mobilite--mobilite-douce-partagee-collective,903
44,preparer-sa-candidature--developper-son-reseau,777
45,remobilisation--activites-sportives-et-culturelles,732
46,se-former--trouver-sa-formation,722
47,difficultes-administratives-ou-juridiques--prendre-en-compte-une-problematique-judiciaire,652
48,remobilisation--benevolat-action-citoyenne,650
49,equipement-et-alimentation--alimentation,483