# Notebook to check the ETL data

In [45]:
import pandas as pd
import os

In [46]:
## We load datasets

data_folder_path = os.path.join(os.getcwd(), '..', 'data')
files_in_data_folder = os.listdir(data_folder_path)

for file_name in files_in_data_folder:
    if file_name.endswith('communes.parquet'):
        df_name = file_name.replace('.parquet', '')
        file_path = os.path.join(data_folder_path, file_name)
        globals()[df_name] = pd.read_parquet(file_path)
        print(df_name)

odis_communes

In [31]:
odis_bassins_de_vie.head()

,bassin_de_vie,population_bv,log_soc_total,log_soc_inoccupes,edu_maternelle_ct,edu_elementaire_ct,ecoles_count,lien_social_count,pop_active,pop_employes,...,sante_hopital_scaled,sante_maternite_scaled,sante_psy_scaled,edu_lycee_scaled,edu_college_scaled,edu_maternelle_scaled,edu_elementaire_scaled,youth_decline_scaled,workclass_decline_scaled,inc_population_scaled
0,01004,45222.0,3646.0,137.0,5.0,25.0,31.0,1517.0,23841,21518,...,0.000000,0.317522,0.360422,0.317522,0.431958,0.409248,0.916567,0.447631,0.389139,0.127880
1,01033,23928.0,2898.0,71.0,0.0,24.0,24.0,680.0,15250,13423,...,0.000000,0.000000,0.486627,0.000000,0.486627,0.000000,0.958459,0.732464,0.491562,0.067664
2,01034,23091.0,1529.0,49.0,4.0,19.0,23.0,900.0,11463,10417,...,0.385821,0.385821,0.385821,0.385821,0.436707,0.450002,0.843186,0.713220,0.707782,0.065297
3,01053,81002.0,10143.0,164.0,5.0,43.0,47.0,3820.0,38803,34648,...,0.577122,0.077257,0.577122,0.499864,0.643243,0.261598,0.988963,0.436200,0.459513,0.229060
4,01072,16906.0,818.0,10.0,1.0,13.0,14.0,861.0,8687,8079,...,0.000000,0.000000,0.000000,0.000000,0.179759,0.179759,0.957116,0.689003,0.597176,0.047807

In [49]:
odis_communes.codgeo_voisins.head()

0           [01412, 01093, 01028, 01146, 01351, 01188]
1           [01056, 01277, 01384, 01007, 01363, 01199]
2    [01384, 01421, 01041, 01345, 01089, 01007, 01149]
3    [01382, 01207, 01261, 01362, 01318, 01398, 01446]
4           [01358, 01110, 01117, 01216, 01233, 01190]
Name: codgeo_voisins, dtype: object

In [44]:
odis_referentiels[(odis_referentiels.code=='11075')].head(100)

              key   code                         label
537  waldec_codes  11075  football  (football, futsal)

In [33]:
odis_associations_agg.head()

  codgeo id_waldec  count
0  00000    001000      1
1  00000    002000      1
2  00000    005000      2
3  00000    006000      1
4  00000    006030      3