# Notebook to check the ETL data

In [19]:
import pandas as pd
import os

In [37]:
## We load datasets

data_folder_path = os.path.join(os.getcwd(), '..', 'data')
files_in_data_folder = os.listdir(data_folder_path)

for file_name in files_in_data_folder:
    if file_name.endswith('.parquet'):
        df_name = file_name.replace('.parquet', '')
        file_path = os.path.join(data_folder_path, file_name)
        globals()[df_name] = pd.read_parquet(file_path)
        print(df_name)

odis_ccas
odis_communes
odis_formations_agg
odis_referentiels
odis_metiers_agg
odis_associations_agg
odis_bassins_de_vie
odis_pois

In [31]:
odis_bassins_de_vie.head()

,bassin_de_vie,population_bv,log_soc_total,log_soc_inoccupes,edu_maternelle_ct,edu_elementaire_ct,ecoles_count,lien_social_count,pop_active,pop_employes,...,sante_hopital_scaled,sante_maternite_scaled,sante_psy_scaled,edu_lycee_scaled,edu_college_scaled,edu_maternelle_scaled,edu_elementaire_scaled,youth_decline_scaled,workclass_decline_scaled,inc_population_scaled
0,01004,45222.0,3646.0,137.0,5.0,25.0,31.0,1517.0,23841,21518,...,0.000000,0.317522,0.360422,0.317522,0.431958,0.409248,0.916567,0.447631,0.389139,0.127880
1,01033,23928.0,2898.0,71.0,0.0,24.0,24.0,680.0,15250,13423,...,0.000000,0.000000,0.486627,0.000000,0.486627,0.000000,0.958459,0.732464,0.491562,0.067664
2,01034,23091.0,1529.0,49.0,4.0,19.0,23.0,900.0,11463,10417,...,0.385821,0.385821,0.385821,0.385821,0.436707,0.450002,0.843186,0.713220,0.707782,0.065297
3,01053,81002.0,10143.0,164.0,5.0,43.0,47.0,3820.0,38803,34648,...,0.577122,0.077257,0.577122,0.499864,0.643243,0.261598,0.988963,0.436200,0.459513,0.229060
4,01072,16906.0,818.0,10.0,1.0,13.0,14.0,861.0,8687,8079,...,0.000000,0.000000,0.000000,0.000000,0.179759,0.179759,0.957116,0.689003,0.597176,0.047807

In [10]:
odis_communes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35014 entries, 0 to 35013
Data columns (total 49 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   codgeo                     35014 non-null  object
 1   libgeo                     35014 non-null  object
 2   dep_code                   35014 non-null  object
 3   reg_code                   35014 non-null  object
 4   commune                    45 non-null     object
 5   plm                        3 non-null      float64
 6   epci_code                  34871 non-null  object
 7   metiers_offres_diff        35014 non-null  float64
 8   bassin_emploi              34924 non-null  object
 9   population                 35014 non-null  float64
 10  pop_active                 35014 non-null  int64
 11  pop_employes               35014 non-null  int64
 12  pop_chomeurs               35014 non-null  int64
 13  pop_jeune_2016             35014 non-null  float64
 14  pop_jeune_2022             35014 non-null  float64
 15  pop_active_2016            35014 non-null  float64
 16  pop_active_2022            35014 non-null  float64
 17  log_priv_vacant_plus_2ans  35014 non-null  float64
 18  log_priv_total             35014 non-null  float64
 19  log_soc_total              35014 non-null  float64
 20  log_soc_inoccupes          35014 non-null  float64
 21  edu_pe_tx_couverture       35014 non-null  float64
 22  edu_maternelle_ct          35014 non-null  float64
 23  edu_elementaire_ct         35014 non-null  float64
 24  edu_college_ct             35014 non-null  float64
 25  edu_lycee_ct               35014 non-null  float64
 26  pol_num                    34772 non-null  float64
 27  MOD_OVER_OCC               34854 non-null  float64
 28  MOD_UNDER_OCC              34854 non-null  float64
 29  SEV_OVER_OCC               34854 non-null  float64
 30  SEV_UNDER_OCC              34854 non-null  float64
 31  STD_OCC                    34854 non-null  float64
 32  VSEV_UNDER_OCC             34854 non-null  float64
 33  total_eleves               21148 non-null  float64
 34  ecoles_count               21148 non-null  float64
 35  risky_schools_count        21148 non-null  float64
 36  codgeo_voisins             34898 non-null  object
 37  bpe_creches_count          35014 non-null  float64
 38  gare_count                 2412 non-null   float64
 39  has_gare                   2412 non-null   float64
 40  loyer_app_m2               34889 non-null  float64
 41  lien_social_count          35014 non-null  float64
 42  count_hopital              10815 non-null  float64
 43  count_psy                  10815 non-null  float64
 44  count_maternite            35014 non-null  float64
 45  epci_nom                   34871 non-null  object
 46  bassin_de_vie              34920 non-null  object
 47  libelle_bassin_de_vie      34920 non-null  object
 48  polygon                    35014 non-null  object
dtypes: float64(34), int64(3), object(12)
memory usage: 13.1+ MB

In [44]:
odis_referentiels[(odis_referentiels.code=='11075')].head(100)

              key   code                         label
537  waldec_codes  11075  football  (football, futsal)

In [33]:
odis_associations_agg.head()

  codgeo id_waldec  count
0  00000    001000      1
1  00000    002000      1
2  00000    005000      2
3  00000    006000      1
4  00000    006030      3