# Notebook to check the ETL data

In [1]:
import pandas as pd
import os

In [2]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [81]:
## We load datasets

data_folder_path = os.path.join(os.getcwd(), '..', 'data')
files_in_data_folder = os.listdir(data_folder_path)

for file_name in files_in_data_folder:
    if file_name.endswith('associations.parquet'):
        df_name = file_name.replace('.parquet', '')
        file_path = os.path.join(data_folder_path, file_name)
        globals()[df_name] = pd.read_parquet(file_path)
        print(df_name)

odis_refugee_associations

In [50]:
files_in_data_folder

['odis_ccas.parquet',
 '.DS_Store',
 'odis_communes.parquet',
 'odis_formations_agg.parquet',
 'odis_referentiels.parquet',
 'odis_metiers_agg.parquet',
 'odis_communes_pre.parquet',
 'odis_associations_agg.parquet',
 'odis_bassins_de_vie.parquet',
 'odis_pois.parquet']

In [52]:
odis_pois.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275393 entries, 0 to 275392
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        275393 non-null  object
 1   name      275393 non-null  object
 2   type      275393 non-null  category
 3   category  275393 non-null  category
 4   lat       275097 non-null  float32
 5   lon       275097 non-null  float32
 6   codgeo    275393 non-null  category
dtypes: category(3), float32(2), object(2)
memory usage: 7.7+ MB

In [57]:
odis_pois[odis_pois.name.str.contains("wimoov", na=False, case=False)].drop_duplicates(subset=["lat", "lon"]).head(20)

,id,name,type,category,lat,lon,codgeo
43720,1fca05b5a69733029116ead3a0530abd,RSA - Plateforme mobilité WIMOOV - Aix / Gardanne,mobilite--acceder-a-un-vehicule,incl_services,43.493237,5.369391,13001
140363,bccb1bd8a137bebb0fc0fccf0c44fbab,RSA - Plateforme mobilité WIMOOV - Salon-Berre / Arles / Istres-Marignane-Vitrolles-Martigues,mobilite--acceder-a-un-vehicule,incl_services,43.652000,5.099365,13103

In [32]:
old_odis = pd.read_parquet('../data/odis_june_2025_jacques.parquet')

In [79]:
odis_referentiels[odis_referentiels.code == "11069"]

                  key   code        label reg_code
4500         communes  11069  Carcassonne     None
36076  bassins_de_vie  11069  Carcassonne     None

In [82]:
odis_refugee_associations[odis_refugee_associations.codgeo.str.contains("11069", na=False)].head()

,id,codgeo,bassin_de_vie,name,description,waldec_code
2660,W111008950,11069,11069,UKRAINE ESPOIR AUDE,"aider de tout ordre, de toutes maniere et lassistance aux refugies du conflit ukrainien par tout moyen daction autorise. Lassociation pourra etre amenee occasionnellement a organiser des evenements commerciaux, ou des activites economiques code du commerce article L442-7",020020

In [ ]:
odis_finess[(odis_finess['Departement'] == '13') & (odis_finess['Commune'] == '103')][['LibelleCategorie','nofinesset']].groupby('LibelleCategorie').count().sort_values(by='nofinesset', ascending=False)

                                                              nofinesset
LibelleCategorie
Pharmacie d'Officine                                                  14
Service autonomie aide (SAA)                                          10
Laboratoire de Biologie Médicale                                       6
Etablissement d'hébergement pour personnes âgées dépendantes           5
Institut Médico-Educatif (I.M.E.)                                      4
Service de Soins Infirmiers A Domicile (S.S.I.A.D)                     3
Centre Hospitalier Spécialisé lutte Maladies Mentales                  3
Centre Hébergement & Réinsertion Sociale (C.H.R.S.)                    3
Autre Résidence Sociale (hors Maison Relais, Pension de Fami           3
Service d'Éducation Spéciale et de Soins à Domicile                    2
Etablissement Consultation Protection Infantile                        2
Etab.Accueil Non Médicalisé pour personnes handicapées                 2
Ecoles Formant aux Professions Sanitaires                              2
Etablissement et Service d'Aide par le Travail (E.S.A.T.)              2
Centre de Santé                                                        2
Structure Dispensatrice à domicile d'Oxygène à usage médical           2
Maison de santé (L.6223-3)                                             1
Maison d'Enfants à Caractère Social                                    1
Résidences autonomie                                                   1
Service d'accompagnement médico-social adultes handicapés              1
Foyer de l'Enfance                                                     1
Foyer de Jeunes Travailleurs (résidence sociale ou non)                1
Foyer d'Action Educative (F.A.E.)                                      1
Foyer Hébergement Enfants et Adolescents Handicapés                    1
Autre Centre d'Accueil                                                 1
Etablissement de santé privé autorisé en SSR                           1
Etablissement de Soins Longue Durée                                    1
Etablissement de Soins Chirurgicaux                                    1
Autre Etablissement Loi Hospitalière                                   1
Etab.Acc.Médicalisé en tout ou partie personnes handicapées            1
Entreprise adaptée                                                     1
Ecoles Formant aux Professions Sociales                                1
Communautés professionnelles territoriales de santé (CPTS)             1
Centre de vaccination internationale                                   1
Centre de dialyse                                                      1
Centre d'Accueil Thérapeutique à temps partiel (C.A.T.T.P.)            1
Centre Médico-Psychologique (C.M.P.)                                   1
Centre Hospitalier (C.H.)                                              1
Centre Action Médico-Sociale Précoce (C.A.M.S.P.)                      1
Centre Accueil Demandeurs Asile (C.A.D.A.)                             1
Structure d'Alternative à la dialyse en centre                         1

# Filter Asso Réfugies

In [3]:
asso =pd.read_parquet('../pipeline/cache/raw/associations.parquet')

In [20]:
asso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2215247 entries, 0 to 2215246
Data columns (total 39 columns):
 #   Column           Dtype
---  ------           -----
 0   id               object
 1   id_ex            object
 2   siret            object
 3   rup_mi           object
 4   gestion          object
 5   date_creat       object
 6   date_decla       object
 7   date_publi       object
 8   date_disso       object
 9   nature           object
 10  groupement       object
 11  titre            object
 12  titre_court      object
 13  objet            object
 14  objet_social1    object
 15  objet_social2    object
 16  adrs_complement  object
 17  adrs_numvoie     object
 18  adrs_repetition  object
 19  adrs_typevoie    object
 20  adrs_libvoie     object
 21  adrs_distrib     object
 22  adrs_codeinsee   object
 23  adrs_codepostal  object
 24  adrs_libcommune  object
 25  adrg_declarant   object
 26  adrg_complemid   object
 27  adrg_complemgeo  object
 28  adrg_libvoie     object
 29  adrg_distrib     object
 30  adrg_codepostal  object
 31  adrg_achemine    object
 32  adrg_pays        object
 33  dir_civilite     object
 34  siteweb          object
 35  publiweb         object
 36  observation      object
 37  position         object
 38  maj_time         object
dtypes: object(39)
memory usage: 659.1+ MB

In [61]:
asso[asso['titre_court'].str.contains('wimoov', case=False, na=False)].assign(objet=lambda x: x['objet'].str[:300])[['id', 'titre_court', 'objet_social1', 'objet', 'adrs_codeinsee']]

,id,titre_court,objet_social1,objet,adrs_codeinsee
1324302,W751186914,WIMOOV,024045,"promouvoir et initier le developpement de nouvelles pratiques de mobilite sensibiliser et accompagner tous les publics vers une mobilite autonome, responsable et respectueuse de lenvironnement",75111

In [38]:
asso[(asso.objet_social1=='019025') & (asso.adrs_codeinsee=='33063')].titre_court.head(25)

468278    RESEAU UNIVERSITAIRE AIME
469936        LA FORCE DUNE MERE FM
477263              PONT DE LESPOIR
Name: titre_court, dtype: object

In [ ]:
asso_refug = asso[asso.objet_social1.str.startswith(('003', '019', '020', '014'), na=False)].loc[
    asso['objet'].str.contains('asil', regex=False, case=False, na=False)
    |asso['objet'].str.contains('refug', regex=False, case=False, na=False)
    |asso['objet'].str.contains('nouveaux arrivants', regex=False, case=False, na=False)
    |asso['objet'].str.contains('migra', regex=False, case=False, na=False),
    ['id', 'adrs_codeinsee', 'titre','position','objet_social1', 'objet']
]

In [24]:
mapping = odis_referentiels[odis_referentiels['key'] == 'waldec_codes'].set_index('code')['label']
asso_refug['objet_lib'] = asso_refug['objet_social1'].astype(int).astype(str).map(mapping)

In [25]:
asso_refug.groupby(['objet_social1', 'objet_lib']).count().sort_values(by='id', ascending=False)

,,id,adrs_codeinsee,titre,position,objet
objet_social1,objet_lib,,,,,
014035,groupements d'entraide et de solidarité,861,861,861,861,861
020000,"ASSOCIATIONS CARITATIVES, HUMANITAIRES, AIDE AU DÉVELOPPEMENT, DÉVELOPPEMENT DU BÉNÉVOLAT",800,800,800,800,800
014000,"AMICALES, GROUPEMENTS AFFINITAIRES, GROUPEMENTS D'ENTRAIDE (HORS DÉFENSE DE DROITS FONDAMENTAUX)",772,772,772,772,772
014040,"amicale de personnes originaires d'un même pays (hors défense des droits des étrangers), d'une même région du monde",536,536,536,536,536
019025,aide aux réfugiés et aux immigrés (hors défense de droits fondamentaux),357,357,357,357,357
020020,associations caritatives intervenant au plan international,325,325,325,325,325
019000,INTERVENTIONS SOCIALES,313,313,313,313,313
003050,"défense de droits de personnes étrangères ou immigrées, de personnes réfugiées",298,298,298,298,298
020015,associations caritatives à but multiple,262,262,262,262,262
003000,"DÉFENSE DE DROITS FONDAMENTAUX, ACTIVITÉS CIVIQUES",207,207,207,207,207
020005,secours financiers et autres services aux personnes en difficulté,166,166,166,166,166
003015,défense des libertés publiques et des droits de l'Homme,119,119,119,119,119
014045,amicale de personnes originaires d'une même région,113,113,113,113,113
003045,défense de droits de personnes rapatriées,73,73,73,73,73
020010,"secours en nature, distribution de nourriture et de vêtements",64,64,64,64,64
003040,lutte contre les discriminations,45,45,45,45,45
014050,associations féminines pour l'entraide et la solidarité (hors défense de droits fondamentaux),42,42,42,42,42
019004,aide et conseils aux familles,41,41,41,41,41
019016,aide à l'insertion des jeunes,35,35,35,35,35
019005,"associations familiales, services sociaux pour les familles",34,34,34,34,34
019040,"aide aux personnes en danger, solitude, désespoir, soutien psychologique et moral",25,25,25,25,25
003020,"défense des droits des femmes, condition féminine",25,25,25,25,25
003060,"activités civiques, information civique",23,23,23,23,23
014070,associations de personnes en situation de handicap pour l'entraide et la solidarité (hors défense de droits fondamentaux),20,20,20,20,20
014030,association du personnel d'une entreprise (hors caractère syndical),19,19,19,19,19
014025,organisation de professions (hors caractère syndical),15,15,15,15,15
003025,défense de droits de personnes homosexuelles,13,13,13,13,13
003035,association pour la défense de droits de minorités,12,12,12,12,12
019014,lutte contre l'illettrisme,10,10,10,10,10
020025,développement du bénévolat,9,9,9,9,9
014060,associations de personnes homosexuelles pour l'entraide et la solidarité (hors défense de droits fondamentaux),8,8,8,8,8
019047,foyers socio-éducatifs,7,7,7,7,7
019010,"centres sociaux, foyers de jeunes travailleurs, centres d'études et d'action sociale",7,7,7,7,7
003010,défense de la paix,7,7,7,7,7
014080,associations de classe d.âge,6,6,6,6,6
019045,lutte contre diverses formes de violence,5,5,5,5,5
003030,défense des droits des personnes en situation de handicap,5,5,5,5,5
019032,aide aux victimes de violences conjugales,4,4,4,4,4
003012,défense des droits des enfants,4,4,4,4,4
019050,réinsertion des délinquants,3,3,3,3,3
019035,aide aux victimes de violences faites aux enfants,2,2,2,2,2
019055,"soutien aux détenus, reclassement des détenus",2,2,2,2,2
019030,"aide aux victimes de calamités naturelles, de catastrophes naturelles",1,1,1,1,1

In [38]:
asso_refug.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5695 entries, 2462 to 2214945
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              5695 non-null   object
 1   adrs_codeinsee  5695 non-null   object
 2   titre           5695 non-null   object
 3   position        5695 non-null   object
 4   objet_social1   5695 non-null   object
 5   objet           5695 non-null   object
 6   objet_lib       5695 non-null   object
dtypes: object(7)
memory usage: 355.9+ KB

In [40]:
asso_refug[asso_refug.adrs_codeinsee == "33063"][['titre', 'objet_social1']].sort_values(by='objet_social1')

,titre,objet_social1
447276,MEMOIRES ET PARTAGES,003000
450015,LAMICALE DES TUNISIENS DE BORDEAUX,003015
462115,ASSOCIATION DES PARENTS DE FAMILLES ESPAGNOLES EMIGREES EN FRANCE - APFEEF DE,003015
472916,KHAIMA QUEER,003025
457113,ACCOMPAGNEMENT PSYCHOLOGIQUE ET MEDIATION INTERCULTURELLE - AMI,003040
463913,WELCOME BORDEAUX RESEAU DHOSPITALITE POUR DES DEMANDEURS DASILE DANS LA REGION DE BORDEAUX,003050
468339,FEARLESS CULTURE,014035
472166,COLLECTIF DES MIGRANT.E.S. DE BORDEAUX CMB,014035
473387,MEDIATION INTERCULTURELLE EN MILIEUX MEDICAL ET SOCIAL INTERPRETARIAT,014035
473665,AQUITAINE EDUCATION - AQUEDUC,014035
466286,BIENVENUE AUX REFUGIES EN GIRONDE,014035
473810,A.M.E - ARCHITECTES POUR DES MIGRATIONS ETHIQUES,014035
460167,COLLECTIF DES ORGANISATIONS DE SOLIDARITE INTERNATIONALE ISSUES DES MIGRATIONS EN NOUVELLE-AQUITAINE COSIM NOUVELLE-AQUITAINE,014035
475558,BASSAN FEMMES FAMILLES,014035
475701,ACCUEIL CHRETIEN DES MIGRANTS ET EXILES EN GIRONDE - ACME,014035
477210,MAUVES,014035
477320,BREAKING THE CHAINS VUCJAK,014035
478635,ASSOCIATION VIE INTEGRATION ET SOLIDARITE POUR MIGRANTS AFRICAINS- AVISMA,014035
479350,LES MAINS DAMANI,014035
479869,MUSSIDAL BORDEAUX,014035
468358,LES ORCHIDEES ROUGES,014035
471245,COLLECTIF BIENVENUE,014035
474094,MAISON MOLDAVE,014040
468775,ASSOCIATION KURDE ROJAVA GIRONDE,014040
1362634,GREEN FASHION WOMEN - BAMAKO GFW-BKO,014040
466691,LES ROSES DE DAMAS,014040
461574,CENTRE CULTUREL GEORGIEN PHESVEBI,014040
458782,ASSOCIATION DES TUNISIENS EN FRANCE DAQUITAINE,014040
455677,ASSOCIATION POUR LINSERTION SOCIALE ET ECONOMIQUE DES MAHORAIS EN METROPOLE : AISE2M,014040
474124,ASSOCIATION WONTANARA SOLIDARITE - AWSO,014050
452074,COMITE TCHETCHENIE CAUCASE GIRONDE,019000
452165,JURISINTEGRATION,019000
477260,ASSOCIATION SOLIDAIRE MARIE CURRY,019000
466936,ACCUEIL PROTESTANT DE REFUGIES DORIENT EN GUYENNE,019004
451951,PROMO-FEMMES ST MICHEL,019016
477263,PONT DE LESPOIR,019025
468278,RESEAU UNIVERSITAIRE BORDELAIS POUR LACCUEIL ET LINSERTION DES MIGRANT-E-S ET DES EXILE-E-S RESEAU UNIVERSITAIRE AIME,019025
452293,NGAYNAKA,020000
478171,BREF,020000
475225,SINGA BORDEAUX,020000
554949,SOIF DEDUCATION,020000
453665,MOUVEMENT DE REFLEXION SUR LIMMIGRATION M.R.I,020000
457771,AFRIKOTREMENT,020015
827847,DIASPORA INVEST,020015
468227,REFUGEES LIVES MATTER,020020

In [32]:
odis_referentiels[(odis_referentiels.code=='23000')].head(100)

,key,code,label,reg_code
850,waldec_codes,23000,"REPRÉSENTATION, PROMOTION ET DÉFENSE D'INTÉRÊTS ÉCONOMIQUES",None

In [33]:
odis_associations_agg.head()

  codgeo id_waldec  count
0  00000    001000      1
1  00000    002000      1
2  00000    005000      2
3  00000    006000      1
4  00000    006030      3

## Filter RNA Mini ODIS

In [93]:
asso.head()

,id,id_ex,siret,rup_mi,gestion,date_creat,date_decla,date_publi,date_disso,nature,groupement,titre,titre_court,objet,objet_social1,objet_social2,adrs_complement,adrs_numvoie,adrs_repetition,adrs_typevoie,adrs_libvoie,adrs_distrib,adrs_codeinsee,adrs_codepostal,adrs_libcommune,adrg_declarant,adrg_complemid,adrg_complemgeo,adrg_libvoie,adrg_distrib,adrg_codepostal,adrg_achemine,adrg_pays,dir_civilite,siteweb,publiweb,observation,position,maj_time
0,W431000001,None,None,None,431S,2006-03-10,2006-03-10,0001-01-01,0001-01-01,D,S,MENTION TRES BIEN,MENTION TRES BIEN,aide et soutien scolaire,015025,000000,None,12,,RUE,de La Rodde,None,43258,43360,Vergongheon,None,None,None,12 Rue de La Rodde,None,43360,VERGONGHEON,FRANCE,PM,None,0,None,A,2007-10-09 15:23:51
1,W431000002,None,None,None,431S,2006-03-03,2013-02-27,0001-01-01,0001-01-01,D,S,GROUPEMENT DEMPLOYEURS DU LIVRADOIS,GROUPEMENT DEMPLOYEURS DU LIVRADOIS,Mettre un salarie a disposition de ses adherents - Embauche de salaries a plusieurs - Reduire des couts de main doeuvre,030005,000000,None,None,,None,LE BOURG,None,43128,43160,Malvieres,None,None,None,LE BOURG,None,43160,MALVIERES,FRANCE,PM,None,0,None,A,2013-02-27 09:14:40
2,W431000003,None,None,None,431S,2006-02-27,2006-02-27,0001-01-01,0001-01-01,D,S,GROUPEMENT DEMPLOYEURS DU CANTOU,GROUPEMENT DEMPLOYEURS DU CANTOU,La mise a disposition de ses membres dun salarie lie a ce groupement par un contrat de travail,030000,000000,None,None,,None,CHIRAC,None,43056,43300,Chanteuges,None,None,None,CHIRAC,None,43300,CHANTEUGES,FRANCE,PM,None,0,None,A,2008-08-11 20:09:10
3,W431000004,None,None,None,431S,2006-02-22,2020-02-05,0001-01-01,0001-01-01,D,S,ASSOCIATION DES PARENTS DELEVES DES ECOLES PUBLIQUES JULES FERRY DE LANGEAC,ASSOCIATION DES PARENTS DELEVES D...,"Toute activite susceptible dapporter un soutien utile a la vie de lecole, une collaboration efficace a laction des maitres et veiller a la defense des interets materiels et moraux de lecole",015065,000000,Mairie,None,,None,None,None,43112,43300,Langeac,None,Mairie,None,None,None,43300,LANGEAC,FRANCE,PF,None,0,None,A,2020-02-11 11:12:25
4,W431000005,None,None,None,431S,2006-02-16,2006-02-16,0001-01-01,0001-01-01,D,S,LABRIPOM,LABRIPOM,"Cette association a pour but la creation, la production, la representation et lorganisation de spectacle et de toutes manifestations culturelles et de loisirs.",006030,000000,None,18,,RUE,Saint Verny,None,43040,43100,Brioude,None,None,None,18 Rue Saint Verny,None,43100,BRIOUDE,FRANCE,PF,None,0,None,A,2008-03-04 17:31:39

In [ ]:
waldec_prefixes = ["003", "018", "019", "020", "032"] #014040
cols_to_keep = ['id', 'adrs_codeinsee', 'objet_social1','titre_court', 'objet']
asso_mini = asso[(asso['objet_social1'].str[:3].isin(waldec_prefixes)) & (asso.position == 'A')][cols_to_keep]
asso_mini['objet'] = asso_mini['objet'].str[:250].str.lower()
asso_mini.to_parquet('../data/odis_asso_mini.parquet', compression='brotli', index=False)

In [117]:
asso_mini.head(50)

,id,adrs_codeinsee,objet_social1,objet
55,W431000057,43132,020015,"organisation des manifestations caritatives comme le telethon, la marche adot43, adapei"
65,W431000067,43264,019040,"louverture et la gestion dun lieu de vie, sis a villeneuve dallier, accueillant des adolescents et pre-adolescents filles et garcons en difficultes, confies par decision de justice ou par les organismes departementaux."
178,W431000184,43040,020020,"encourager et cultiver lideal de servir, le developpement des relations personnelles damour entre ses membres en vue de leur fournir des occasions de servir linteret general, lobservation des regles de probite et de delicatesse dans lexercice de leur"
208,W431000217,43040,019020,favoriser linsertion sociales et professionnelle des personnes en difficulte par lexercice dune activite professionnelle
231,W431000240,43118,020015,projets humanitaires.
263,W431000277,43067,003040,denoncer les injustices et les mensonges qui causent des victimes innocentes et sans defense - aider ces victimes.
295,W431000313,43112,018050,favoriser linsertion des personnes handicapees par la promotion dactivites a caractere culturel en collaboration avec dautres associations ou en utilisant ses propres moyens
364,W431000388,43040,020015,"laide materielle et morale aux oeuvres privees, charitables, hospitalieres, sanitaires et sociales, et en particulier ladministration et la gestion des residences saint dominique a brioude et la maison de retraite saint-dominique a craponne-sur-arzon"
410,W431000434,43258,018050,"lorientation, la reeducation et la formation professionnelle des personnes en situation de handicap, leur insertion ou reinsertion dans la vie economique et sociale afin de concourir a leur integration dans la societe informer lopinion sur ces sujet"
536,W431000561,43040,018005,"de faire decouvrir et promouvoir le bien-etre des enfants massage bebe, portage, langue des signes... et des adultes pilates..."
561,W431000586,43132,020000,aide humanitaire pour lafrique et entraide locale aux plus demunie
602,W431000627,43040,019016,elaboration et mise en oeuvre dune politique locale concertee dinsertion professionnelle et sociale des jeunes de 16 a 25 ans
756,W431000781,43103,019016,"lorganisation administrative et la gestion du lieu de vie lieu daccueil camina recevant des jeunes en difficultes etou en danger, dans le but de favoriser leur reinsertion sociale etou famille, elle aidera et soutiendra les responsables du lieu de vi"
796,W431000821,43258,019004,reunir les mamans ayant besoin dun soutient a un moment donne
816,W431000841,43040,020015,organisation de projets humanitaires
822,W431000847,43040,020025,"soutenir des projets et des initiatives locales qui concourent a la vie locale, au dynamisme et au developpement de la region, elle a egalment pour objectif de developper localement la solidarite"
904,W431000929,43261,020015,"aider a la reconstruction dun gymnase, achat de materiel pour le gymnase de lecole de quinahue ainsi quune aide a la remise en service de lecole de quinahue"
907,W431000932,43040,032520,"exercer tous droits en matiere, notamment, de defense des investisseurs en valeurs mobilieres ou en produits financiers, des contribuables et des telespectateurs, defense des interets individuells et collectifs dans tous les domaines decides par le c"
909,W431000934,43148,019000,promouvoir lanimation pour les personnes agees de la maison de retraite les pireilles
972,W431000997,43040,019042,sensibiliser les jeunes dans le but deviter quils empruntent la route departementale 588 route de saint-flour a pied la nuit
1019,W431001044,43100,020015,participation a un ou plusieurs raids 4l trophy aventure sportive et activites humanitaires developpement de larchitecture dans les pays sous-developpes
1044,W431001069,43239,019004,"assurer un soutien de proximite a la parentalite, en particulier au niveau de lallaitement maternel en haute-loire, et au-dela sil y a une demande soutenir des meres et des familles, afin quelles reussissent leur projet dallaitement, cest-a-dire que"
1092,W431001117,43112,019047,"de developper la vie collective, communautaire et cooperative de letablissement, tout en favorisant lepanouissement de la personnalite de chacun de promouvoir le sens des responsabilites et lapprentissage de la vie civique et democratique dameliore"
1176,W431001201,43112,019016,"de proposer a des structures de leconomie sociale et solidaire un soutien logistique, technique ou administral permettant une insertion socio professionnelle de qualite le soutien peut prendre notamment la forme de mise a disposition de locaux, de m"
1260,W431001285,43038,020005,favoriser linsertion sociale et professionnelle de toute personne en difficulte
1285,W431001310,43185,019047,promouvoir le sens des responsabilites et de la vie civique participer aux actions collectives dentraide et solidarite favoriser un esprit de tolerance et douverture a lautre valoriser la creativite developper la vie sociale se familiariser au t
1309,W431001337,43112,003015,"faciliter la rencontre, lechange et la reflexion entre citoyens langeadois en experimentant la democratie participative promouvoir le respect des droits de lhomme promouvoir les valeurs citoyennes dans le respect de la laicite promouvoir le debat"
1313,W431001341,43040,032000,"elle agit entre autre : contre toute forme dexclusion sociale, economique, culturelle et raciale pour favoriser leducation populaire et la solidarite pour developper la responsablite et la promotion des individus et collective aux decisions qui les c"
1354,W431001382,43258,003030,defendre la sante et proteger nos enfants en situation de handicap touches par la maladie et dans lincapacite daffronter les mauvais traitements quon veut leur infliger
1365,W431001393,43051,019000,"assistante, aide morale et materielle a tous ceux qui en ont besoin, sans acception dopinion politique, philosophique, religieuse ou encore de nationalite son action est fondee sur les valeurs de fraternite et de solidarite dont levangile porte temo"
1405,W431001434,43148,019004,aider materiellement et moralement a domicile les familles en milieu rural a tous moments de leur existence
1407,W431001436,43118,019000,organiser lanimation de la maison daccueil en veilant a lelaboration et la mise en oeuvre du projet de vie
1413,W431001442,43040,020015,aider les personnes a regagner autonomie et dignite proposer un travail educatif et creer du lien social
1439,W431001468,43040,019010,"promouvoir le sens des responsabilites et de la vie civique.participer aux actions collectives dentraide et de solidarite.developper la vie sociale,valoriser la creativite,linitiative et le gout dentreprendre."
1445,W431001474,43132,020005,"etablir un programme dactions pour venir en aide a jean ratail, enfant myopathe cette aide peut prendre diverses formes comme lachat de materiel orthopedique, de seances ludiques ou de soins non pris en charge par quelques organismes que ce soit"
1469,W431001498,43120,020020,fournir du materiel scolaire et sportif a des enfants demunis du sud marocain en participant au rally-raid humanitaire : le 4l trophy 2018
1582,W431004711,43016,020005,"aider a subvenir aux besoins inherents a letat de sante dhugo, et aux besoins de sa famille, exercer des activites economiques telles que ventes de produits tombola, organisation de soirees avec repas, marche solidaire, liste non exhaustive, utilisat"
1583,W431004712,43185,019014,"alphabetisation des personnes ne maitrisant pas ou peu le francais, et selon les besoins et les possibilites, tisser des liens sociaux, partager des connaissances en partant de lalphabetisation, partager le savoir-faire et le savoir-etre, repondre au"
1605,W431004734,43234,020020,procurer des fournitures scolaires aux enfants defavorises du maroc
1607,W431004736,43170,020020,participation au raid humanitaire du 4l trophy
1622,W431004753,43234,020020,"apporter une aide materielle a des habitants du sud marocain, a travers la participation a differents projets comme le raid humanitaire 205 trophee"
1623,W431004754,43040,020000,"collecter du materiel scolaire, sportif, medical, de construction ainsi que des denrees non perissables afin de les distribuer dans les provinces derrachidia et de ouarzazate au maroc ameliorer les conditions de vie des enfants defavorises du sud-es"
1624,W431004755,43178,020020,contribuer au developpement dans les regions dans lesquelles lentreprise zetwal etablit des liens commerciaux avec des artistes et artisans et plus largement dans les regions dans lesquelles elle a eu des partenaires ou eventuellement ailleurs pour r
1643,W431004774,43070,020020,"apporter un soutien humanitaire aux populations defavorisees des pays dafrique et du mon entier en general organiser et participer a des evenements sportifs, culturels, sociaux et humanitaires afin de creer des liens intergenerationnels, intercultur"
1693,W431004824,43016,020000,production et vente a ses membres de tous les objets utiles a lexistence et le groupement ou la fusion de la presente societe avec toutes autres cooperatives de la region la societe se reserve la faculte douvrir la vente aux consommateurs non socie
1766,W431004897,43040,032520,"defense des interets des lotisseurs du cil, route de saint-flour, a brioude"
1770,W431004901,43040,020005,"aider, secourir, assister et au besoin defendre tous les jeunes en difficulte, ayant eu des problemes avec la justice, qui ont fait de la prison, drogues ou alcooliques leur donner toutes les possibilites de se reclasser dans la societe les aider a"
1781,W431004912,43040,019005,grouper et servir les interets des exploitants de jardins familiaux proprietaires et locataires par des moyens legaux appropries
1815,W431004946,43040,020015,"reunir des fonds par la vente de cartes de membres, dobjets divers, publications, ainsi que lorganisation de manifestations diverses afin deffectuer des operations dassistance et de bienfaisance"
1870,W431005001,43038,003000,"rassembler en son sein tous les jeunes francais et toutes les jeunes francaises devoues a la patrie et de les eduquer dans lamour de la republique, de la democratie et de la laicite"