# Notebook to check the ETL data

In [44]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [1]:
import pandas as pd
import os

In [2]:
## We load datasets

data_folder_path = os.path.join(os.getcwd(), '..', 'data')
files_in_data_folder = os.listdir(data_folder_path)

for file_name in files_in_data_folder:
    if file_name.endswith('communes.parquet'):
        df_name = file_name.replace('.parquet', '')
        file_path = os.path.join(data_folder_path, file_name)
        globals()[df_name] = pd.read_parquet(file_path)
        print(df_name)

odis_communes

In [3]:
odis_communes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35014 entries, 0 to 35013
Data columns (total 66 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   codgeo                     35014 non-null  object
 1   dep_code                   35014 non-null  object
 2   reg_code                   35014 non-null  object
 3   commune                    45 non-null     object
 4   plm                        3 non-null      float32
 5   epci_code                  34871 non-null  object
 6   bassin_emploi              34924 non-null  object
 7   population                 35014 non-null  float32
 8   pop_active                 35014 non-null  int64
 9   pop_employes               35014 non-null  int64
 10  pop_chomeurs               35014 non-null  int64
 11  log_priv_vacant_plus_2ans  35014 non-null  float32
 12  edu_pe_tx_couverture       35014 non-null  float32
 13  edu_maternelle_ct          35014 non-null  float32
 14  edu_elementaire_ct         35014 non-null  float32
 15  edu_college_ct             35014 non-null  float32
 16  edu_lycee_ct               35014 non-null  float32
 17  pol_num                    35014 non-null  float32
 18  total_eleves               21151 non-null  float32
 19  ecoles_count               21151 non-null  float32
 20  risky_schools_count        35014 non-null  float32
 21  codgeo_voisins             34898 non-null  object
 22  bpe_creches_count          35014 non-null  float32
 23  gare_count                 2412 non-null   float32
 24  lien_social_count          35014 non-null  float32
 25  count_hopital              35014 non-null  float32
 26  count_psy                  35014 non-null  float32
 27  count_maternite            35014 non-null  float32
 28  epci_nom                   34871 non-null  object
 29  bassin_de_vie              34920 non-null  object
 30  polygon                    35014 non-null  object
 31  log_soc_inoc_ratio         35014 non-null  float32
 32  log_pp_occup               35014 non-null  float32
 33  metiers_tension_ratio      35014 non-null  float32
 34  metiers_offres_ratio       35014 non-null  float32
 35  pop_chomage_ratio          35014 non-null  float32
 36  met_ratio                  35014 non-null  float32
 37  log_vac_struct_ratio       35014 non-null  float32
 38  lien_social_density        35014 non-null  float32
 39  risque_fermeture_ratio     35014 non-null  float32
 40  bpe_creches_density        35014 non-null  float32
 41  met_scaled                 35014 non-null  float32
 42  loyer_abordable_scaled     34889 non-null  float32
 43  log_vac_scaled             35014 non-null  float32
 44  inc_asso_core_scaled       35014 non-null  float32
 45  inc_population_scaled      35014 non-null  float32
 46  inc_pol_scaled             35014 non-null  float32
 47  log_occup_scaled           35014 non-null  float32
 48  youth_growth_rate          35014 non-null  float32
 49  workclass_growth_rate      35014 non-null  float32
 50  youth_decline_scaled       35014 non-null  float32
 51  workclass_decline_scaled   35014 non-null  float32
 52  log_soc_inoc_scaled        35014 non-null  float32
 53  edu_classes_ferm_scaled    35014 non-null  float32
 54  edu_creches_scaled         35014 non-null  float32
 55  edu_petite_enfance_scaled  35014 non-null  float32
 56  mob_gare_scaled            35014 non-null  float32
 57  edu_maternelle_scaled      35014 non-null  float32
 58  edu_elementaire_scaled     35014 non-null  float32
 59  edu_college_scaled         35014 non-null  float32
 60  edu_lycee_scaled           35014 non-null  float32
 61  sante_hopital_scaled       35014 non-null  float32
 62  sante_maternite_scaled     35014 non-null  float32
 63  sante_psy_scaled           35014 non-null  float32
 64  inc_services_core_scaled   35014 non-null  float32
 65  socle_match_count          35014 non-null  int64
dtypes: float32(52), int64(4), object(10)
memory usage: 10.7+ MB

In [9]:
odis_pois[odis_pois['name'].str.contains('WEMOOV', case=False, na=False)]

Empty DataFrame
Columns: [id, name, type, category, lat, lon, codgeo]
Index: []

In [16]:
odis_pois.category.unique()

['education', 'sante', 'incl_services']
Categories (3, object): ['education', 'incl_services', 'sante']

In [17]:
asso =pd.read_parquet('../pipeline/cache/raw/associations.parquet')

In [20]:
asso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2215247 entries, 0 to 2215246
Data columns (total 39 columns):
 #   Column           Dtype
---  ------           -----
 0   id               object
 1   id_ex            object
 2   siret            object
 3   rup_mi           object
 4   gestion          object
 5   date_creat       object
 6   date_decla       object
 7   date_publi       object
 8   date_disso       object
 9   nature           object
 10  groupement       object
 11  titre            object
 12  titre_court      object
 13  objet            object
 14  objet_social1    object
 15  objet_social2    object
 16  adrs_complement  object
 17  adrs_numvoie     object
 18  adrs_repetition  object
 19  adrs_typevoie    object
 20  adrs_libvoie     object
 21  adrs_distrib     object
 22  adrs_codeinsee   object
 23  adrs_codepostal  object
 24  adrs_libcommune  object
 25  adrg_declarant   object
 26  adrg_complemid   object
 27  adrg_complemgeo  object
 28  adrg_libvoie     object
 29  adrg_distrib     object
 30  adrg_codepostal  object
 31  adrg_achemine    object
 32  adrg_pays        object
 33  dir_civilite     object
 34  siteweb          object
 35  publiweb         object
 36  observation      object
 37  position         object
 38  maj_time         object
dtypes: object(39)
memory usage: 659.1+ MB

In [87]:
asso[asso['titre'].str.contains('SINGA', case=False, na=False)].transpose()

,97986,111542,241875,282977,288527,348815,420161,475225,540288,687855,741453,954195,963063,972578,1052592,1059306,1094122,1169469,1259718,1303641,1331643,1340123,1342629,1358728,1372187,1381349,1387780,1441763,1481888,1498997,1533551,1552464,1622380,1745949,1803371,1807791,1819223,1843894,1936214,1975786,2010307,2031076,2089915,2089917,2109564,2139626,2182645,2199720,2203117
id,W911001502,W912014857,W595036943,W212000016,W212005585,W263008781,W291010549,W332031571,W952001922,W561003373,W9R3000496,W691076060,W691084936,W691094560,W423009544,W311003359,W313028481,W784009539,W832000099,W751111733,W751205208,W751213691,W751216200,W751232364,W751245946,W751258129,W751264589,W622009560,W442006339,W442026574,W381020064,W383003202,W931001438,W303001643,W941006845,W941011269,W942005243,W061014589,W9T1000486,W923010065,W133008782,W133032666,W543010340,W543010342,W723007809,W352002588,W852013975,W641013564,W642001872
id_ex,None,None,None,9512384,None,None,None,None,None,0561010148,None,0691018155,None,None,None,None,None,None,0833004189,111733,None,None,None,None,None,None,None,None,0442033893,None,None,None,2004-00851,None,None,None,None,None,9851000762,None,0133015154,None,None,None,0723009245,None,None,None,None
siret,None,None,None,None,None,None,None,None,None,None,None,None,None,83866142900061,None,None,None,None,None,None,None,79326794900014,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
rup_mi,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
gestion,911S,912P,595P,212P,422S,263P,291S,332P,9G2S,562S,9R3S,691P,691P,691P,423P,311S,313P,921S,832P,751P,751P,751P,751P,751P,751P,751P,751P,622S,442P,442P,381P,383S,931P,303S,941P,941P,942S,061S,9T1P,923S,133P,133P,543P,543P,723P,852P,852P,641S,642S
date_creat,2013-05-06,2021-07-11,2020-05-25,1995-01-22,2010-10-14,2018-05-08,2017-09-11,2022-02-11,2010-06-04,1996-02-13,2006-09-18,1983-09-23,2014-01-20,2018-02-09,2017-12-21,2014-04-11,2018-10-05,2019-09-17,1960-12-06,1993-10-06,2010-05-28,2012-02-20,2012-09-02,2016-01-11,2018-09-05,2020-09-24,2022-04-01,2021-12-14,2008-08-29,2021-11-22,2018-05-17,2013-10-17,1998-02-09,2014-02-17,2011-07-11,2017-04-14,2014-09-04,2020-06-13,2004-08-12,2019-04-03,1985-06-18,2019-07-10,2018-02-21,2018-02-25,1997-11-17,2018-06-05,2025-08-11,2022-07-18,2014-08-14
date_decla,2016-04-07,2021-07-11,2022-01-14,2021-12-01,2017-06-28,2023-12-17,2020-01-27,2023-10-17,2013-03-14,2018-04-16,2006-09-18,2010-03-26,2018-11-21,2024-07-05,2023-07-05,2014-04-11,2023-03-23,2022-12-22,2014-04-02,2023-01-11,2010-05-28,2023-05-26,2012-09-02,2016-01-11,2018-09-05,2020-09-24,2022-04-01,2021-12-14,2008-08-29,2025-03-02,2018-05-17,2023-11-23,2020-01-31,2024-06-03,2011-07-11,2017-04-14,2014-09-04,2020-06-13,2009-02-24,2019-04-03,2021-12-23,2024-03-16,2022-03-05,2018-02-25,1997-11-17,2021-08-29,2025-08-11,2022-07-18,2019-03-29
date_publi,2013-05-25,2021-07-20,2020-06-06,1995-02-22,2010-10-30,2018-05-19,2017-09-16,2022-02-22,2010-06-26,1996-03-06,0001-01-01,0001-01-01,2014-02-01,2018-02-17,2017-12-30,2014-04-26,2018-10-13,2019-09-21,0001-01-01,1993-10-27,2010-06-19,2012-03-03,2012-09-15,2016-01-23,2018-09-15,2020-10-03,2022-04-12,2022-02-08,2008-09-20,2021-11-30,2018-05-26,2013-10-26,1998-03-07,2014-03-01,2011-08-06,2017-04-29,2014-09-20,2020-06-20,0001-01-01,2019-04-13,1985-07-10,2019-07-20,2018-03-03,2018-03-17,1997-12-13,2018-06-16,2025-08-19,2022-07-26,2014-08-23
date_disso,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,2019-11-22,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,2022-02-21,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,2018-12-20
nature,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D
groupement,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S
titre,AVENIR SINGAPURA,AEAERSF ASSOCIATION DENTRAIDE POUR LENTERREMENT OU LE RAPATRIEMENT DES SINGANIENS DE FRANCE,SINGA LILLE,SINGALLMUSIC,DANSINGANG,SINGA VALENCE,BRETONS DE SINGAPOUR BRETONS OF SINGAPORE,SINGA BORDEAUX,ASSOCIATION COUP DE MAIN TSINGANI - ACT,SINGAPURAS PARTNERS ALLIANCE SINGAPURAS OU SPAS,SAKTI PEETAM SHRI SINGAMAKALI AMMAN,ASSOCIATION LYON SINGAPOUR,AMICALE FRANCO-SINGANIEN DE RHONE-ALPES AFSR,SINGA LYON,SINGA SAINT-ETIENNE,SINGA SOS,SINGA TOULOUSE,ESSINGANG,FOYER DES JEUNES ET DEDUCATION PERMANENTE PIERRE SINGAL,SINGAPORE CLUB FRANCE,ASSOCIATION DES ETUDIANTS SINGAPOURIENS EN FRANCE,SINGA PARIS,ASSOCIATION DU LL.M INTERNATIONAL BUSINESS LAW PARIS - SINGAPOUR,SINGA SCIENCES PO,ALUMNI DU LYCEE FRANCAIS DE SINGAPOUR,SINGA GLOBAL,SINGA YA FAMILLE,SINGAM,ESSINGAN,SINGA NANTES,SINGA GRENOBLE,ASSOCIATION SINGALI,ASSOCIATION POUR LE DEVELOPPEMENT DE LA SINGANI EN FRANCE,BASINGA,ESSINGANG,BANA SINGA MOPEPE B.S.M,ASSOCIATION DES ENFANTS DE TSINGA POLYCLINIQUE ADTP,ASSOCIATION POUR LE DEVELOPPEMENT DES RELATIONS FRANCO SINGAPOURIENNE,TAMIME NA SINGA,LES TOUAREGS SINGAPOURIENS,ASSOCIATION CULTURELLE ET SOCIALE DE SINGANI,SINGA MARSEILLE,PINT OF SCIENCE SINGAPORE POS SG,PINT OF SCIENCE SINGAPORE,ASSOCIATION DU PONEY-CLUB SINGAPOUR EQUITATION APCSE,CAP SUR RUSINGA,SINGA YETU,SOUTIEN SPORTIF POUR ENFANTS DE RUSINGA KENYA,SINGA SINGA
titre_court,AVENIR SINGAPURA,AEAERSF,SINGA LILLE,SINGALLMUSIC,DANSINGANG,SINGA VALENCE,BRETONS DE SINGAPOUR,SINGA BORDEAUX,ASSOCIATION COUP DE MAIN TSINGANI -...,SPAS,SAKTI PEETAM SHRI,ASSOCIATION LYON SINGAPOUR,AFSR,SINGA LYON,SINGA SAINT-ETIENNE,SINGA SOS,SINGA TOULOUSE,ESSINGANG,FOYER DES JEUNES ET DEDUCATION PERMA,SINGAPORE CLUB FRANCE,ASSOCIATION DES ETUDIANTS SINGAPOUR...,SINGA PARIS,ASSOCIATION DU LL.M IBL,SINGA SCIENCES PO,ALUMNI DU LYCEE FRANCAIS DE SINGAPOUR,SINGA,SINGA YA FAMILLE,SINGAM,ESSINGAN,SINGA NANTES,SINGA GRENOBLE,ASSOCIATION SINGALI,ADSF,BASINGA,ESSINGANG,B.S.M,ASSOCIATION DES ENFANTS DE TSINGA P...,RELATIONS FRANCO SINGAPOURIENNNE,TAMIME NA SINGA,LES TOUAREGS SINGAPOURIENS,ASSOCIATION CULTURELLE ET SOCIALE D...,SINGA MARSEILLE,PINT OF SCIENCE SG,PINT OF SCIENCE SG,ASSOCIATION DU PONEY-CLUB SINGAPOUR...,CAP SUR RUSINGA,S.Y.,SOUTIEN SPORTIF POUR ENFANTS DE RUSING,SINGA SINGA

In [38]:
asso[(asso.objet_social1=='019025') & (asso.adrs_codeinsee=='33063')].titre_court.head(25)

468278    RESEAU UNIVERSITAIRE AIME
469936        LA FORCE DUNE MERE FM
477263              PONT DE LESPOIR
Name: titre_court, dtype: object

In [82]:
asso_refug = asso[asso.objet_social1.str.startswith(('003', '019', '020'), na=False)].loc[
    asso['objet'].str.contains('asile', regex=False, case=False, na=False)|asso['objet'].str.contains('réfugié', regex=False, case=False, na=False),
    ['id', 'adrs_codeinsee', 'titre','position','objet_social1', 'objet']
]

In [83]:
mapping = odis_referentiels[odis_referentiels['key'] == 'waldec_codes'].set_index('code')['label']
asso_refug['objet_lib'] = asso_refug['objet_social1'].astype(int).astype(str).map(mapping)

In [85]:
asso_refug.groupby(['objet_social1', 'objet_lib']).count().sort_values(by='id', ascending=False)

,,id,adrs_codeinsee,titre,position,objet
objet_social1,objet_lib,,,,,
019025,aide aux réfugiés et aux immigrés (hors défense de droits fondamentaux),102,102,102,102,102
003050,"défense de droits de personnes étrangères ou immigrées, de personnes réfugiées",89,89,89,89,89
020000,"ASSOCIATIONS CARITATIVES, HUMANITAIRES, AIDE AU DÉVELOPPEMENT, DÉVELOPPEMENT DU BÉNÉVOLAT",89,89,89,89,89
019000,INTERVENTIONS SOCIALES,55,55,55,55,55
020005,secours financiers et autres services aux personnes en difficulté,36,36,36,36,36
020015,associations caritatives à but multiple,31,31,31,31,31
003015,défense des libertés publiques et des droits de l'Homme,31,31,31,31,31
003000,"DÉFENSE DE DROITS FONDAMENTAUX, ACTIVITÉS CIVIQUES",23,23,23,23,23
020020,associations caritatives intervenant au plan international,18,18,18,18,18
003045,défense de droits de personnes rapatriées,16,16,16,16,16
020010,"secours en nature, distribution de nourriture et de vêtements",10,10,10,10,10
003040,lutte contre les discriminations,6,6,6,6,6
003025,défense de droits de personnes homosexuelles,5,5,5,5,5
019040,"aide aux personnes en danger, solitude, désespoir, soutien psychologique et moral",5,5,5,5,5
019004,aide et conseils aux familles,3,3,3,3,3
019005,"associations familiales, services sociaux pour les familles",3,3,3,3,3
003010,défense de la paix,2,2,2,2,2
019010,"centres sociaux, foyers de jeunes travailleurs, centres d'études et d'action sociale",1,1,1,1,1
019014,lutte contre l'illettrisme,1,1,1,1,1
019016,aide à l'insertion des jeunes,1,1,1,1,1
019032,aide aux victimes de violences conjugales,1,1,1,1,1
019047,foyers socio-éducatifs,1,1,1,1,1
003035,association pour la défense de droits de minorités,1,1,1,1,1
003020,"défense des droits des femmes, condition féminine",1,1,1,1,1
003060,"activités civiques, information civique",1,1,1,1,1
003012,défense des droits des enfants,1,1,1,1,1
003030,défense des droits des personnes en situation de handicap,1,1,1,1,1

In [88]:
asso_refug[asso_refug['titre'].str.contains('SINGA')]

,id,adrs_codeinsee,titre,position,objet_social1,objet,objet_lib
475225,W332031571,33063,SINGA BORDEAUX,A,020000,"favoriser lemergence despaces et doutils de rencontre, dechange et de cooperation, entre les personnes demandeuses dasile et beneficiaires de la protection internationale dune part, et leur societe daccueil dautre part, afin de permettre le vivre-ensemble, lenrichissement culturel, linclusion socio-professionnelle et la creation demploi pour tous a cet effet, lassociation accompagne les projets des personnes demandeuses dasile et des refugies statutaires ainsi que les projets de toute personne souhaitant contribuer a lintegration de ces derniers ou a lobjet de lassociation ce travail est renforce par une demarche de recherche, de sensibilisation et de plaidoyer promouvant des solutions","ASSOCIATIONS CARITATIVES, HUMANITAIRES, AIDE AU DÉVELOPPEMENT, DÉVELOPPEMENT DU BÉNÉVOLAT"
1533551,W381020064,38185,SINGA GRENOBLE,A,020000,"favoriser lemergence despaces et doutils de rencontre, dechange et de cooperation entre les personnes migrantes et leur societe daccueil afin de favoriser le vivre ensemble, lenrichissement culturel et linclusion socioprofessionnelle r Changer le regard envers les personnes migrantes, pour les considerer avant tout comme des individus, chacun avec son potentiel, ses experiences, ses aspirations r Accelerer linclusion des personnes migrantes, et accompagner a la creation dun reseau socioprofessionnel, en recherchant limplication de tous les acteurs de la societe daccueil : societe civile, collectivites, institutions, associations, entreprises r A cet effet, lassociation developpe trois missions principales : r -tInformer : sensibiliser et changer le regard sur lasile r -tConnecter : creer des outils et des espaces de rencontre entre personnes migrantes et membres issus de la societe daccueil r -tInnover : trouver des solutions innovantes aux problematiques dinclusion r Lassociation est a rayonnement local elle est laique, a-partisane et fonde lensemble de son fonctionnement et de ses actions sur une charte de valeurs","ASSOCIATIONS CARITATIVES, HUMANITAIRES, AIDE AU DÉVELOPPEMENT, DÉVELOPPEMENT DU BÉNÉVOLAT"

In [37]:
odis_referentiels[(odis_referentiels.code=='19025')].head(100)

               key   code                                              label
610   waldec_codes  19025  aide aux réfugiés et aux immigrés (hors défens...
7125      communes  19025                                          Beyssenac

In [33]:
odis_associations_agg.head()

  codgeo id_waldec  count
0  00000    001000      1
1  00000    002000      1
2  00000    005000      2
3  00000    006000      1
4  00000    006030      3