# Notebook to check the ETL data

In [1]:
import pandas as pd
import os

In [4]:
## We load datasets

data_folder_path = os.path.join(os.getcwd(), '..', 'data')
files_in_data_folder = os.listdir(data_folder_path)

for file_name in files_in_data_folder:
    if file_name.endswith('communes.parquet'):
        df_name = file_name.replace('.parquet', '')
        file_path = os.path.join(data_folder_path, file_name)
        globals()[df_name] = pd.read_parquet(file_path)
        print(df_name)

odis_communes

In [3]:
odis_bassins_de_vie.info()

NameError: name 'odis_bassins_de_vie' is not defined

In [5]:
odis_communes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35014 entries, 0 to 35013
Data columns (total 36 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   codgeo                     35014 non-null  object
 1   dep_code                   35014 non-null  object
 2   reg_code                   35014 non-null  object
 3   commune                    45 non-null     object
 4   plm                        3 non-null      float32
 5   epci_code                  34871 non-null  object
 6   bassin_emploi              34924 non-null  object
 7   population                 35014 non-null  float32
 8   codgeo_voisins             34898 non-null  object
 9   epci_nom                   34871 non-null  object
 10  bassin_de_vie              34920 non-null  object
 11  polygon                    35014 non-null  object
 12  met_scaled                 35014 non-null  float32
 13  loyer_abordable_scaled     34889 non-null  float32
 14  log_vac_scaled             35014 non-null  float32
 15  inc_asso_core_scaled       35014 non-null  float32
 16  inc_population_scaled      35014 non-null  float32
 17  inc_pol_scaled             34772 non-null  float32
 18  log_occup_scaled           35014 non-null  float32
 19  youth_growth_rate          35014 non-null  float32
 20  workclass_growth_rate      35014 non-null  float32
 21  youth_decline_scaled       35014 non-null  float32
 22  workclass_decline_scaled   35014 non-null  float32
 23  log_soc_inoc_scaled        35014 non-null  float32
 24  edu_classes_ferm_scaled    35014 non-null  float32
 25  edu_creches_scaled         35014 non-null  float32
 26  edu_petite_enfance_scaled  35014 non-null  float32
 27  mob_gare_scaled            35014 non-null  float32
 28  edu_maternelle_scaled      35014 non-null  float32
 29  edu_elementaire_scaled     35014 non-null  float32
 30  edu_college_scaled         35014 non-null  float32
 31  edu_lycee_scaled           35014 non-null  float32
 32  sante_hopital_scaled       35014 non-null  float32
 33  sante_maternite_scaled     35014 non-null  float32
 34  sante_psy_scaled           35014 non-null  float32
 35  inc_services_core_scaled   35014 non-null  float32
dtypes: float32(26), object(10)
memory usage: 6.1+ MB

In [44]:
odis_referentiels[(odis_referentiels.code=='11075')].head(100)

              key   code                         label
537  waldec_codes  11075  football  (football, futsal)

In [33]:
odis_associations_agg.head()

  codgeo id_waldec  count
0  00000    001000      1
1  00000    002000      1
2  00000    005000      2
3  00000    006000      1
4  00000    006030      3