# Notebook to check the ETL data

In [2]:
import pandas as pd
import os

In [3]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

In [51]:
## We load datasets

data_folder_path = os.path.join(os.getcwd(), '..', 'data')
files_in_data_folder = os.listdir(data_folder_path)

for file_name in files_in_data_folder:
    if file_name.endswith('referentiels.parquet'):
        df_name = file_name.replace('.parquet', '')
        file_path = os.path.join(data_folder_path, file_name)
        globals()[df_name] = pd.read_parquet(file_path)
        print(df_name)

odis_referentiels

In [6]:
odis_pois.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311541 entries, 0 to 311540
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        311541 non-null  object
 1   name      311540 non-null  object
 2   type      311541 non-null  category
 3   category  311541 non-null  category
 4   lat       310840 non-null  float32
 5   lon       310840 non-null  float32
 6   codgeo    311541 non-null  category
dtypes: category(3), float32(2), object(2)
memory usage: 9.0+ MB

In [10]:
odis_pois[(odis_pois['codgeo'] == '13103') & (odis_pois['category'] == 'sante')].head(20)

,id,name,type,category,lat,lon,codgeo
60054,130001225,HOPITAL DU PAYS SALONAIS,Maternité,sante,43.639366,5.102532,13103
60082,130043375,HJ ADO PARADOX HJ ENF TALLAGARD SALON,Soutien Psychologique & Addictologie,sante,43.651737,5.102485,13103
60123,130796824,CMP VILLA BLANCHE SALON,Soutien Psychologique & Addictologie,sante,43.641365,5.102738,13103
60154,130806953,CMP CATTP LE TALLAGARD SALON,Soutien Psychologique & Addictologie,sante,43.648014,5.102120,13103
60167,130807720,CATTP VILLA BLANCHE SALON,Soutien Psychologique & Addictologie,sante,43.641365,5.102738,13103
60168,130807738,HJ VILLA BLANCHE SALON,Soutien Psychologique & Addictologie,sante,43.641365,5.102738,13103
64939,130001225_mat,HOPITAL DU PAYS SALONAIS,Maternité,sante,43.639366,5.102532,13103

In [32]:
old_odis = pd.read_parquet('../data/odis_june_2025_jacques.parquet')

In [34]:
old_odis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34935 entries, 0 to 34934
Data columns (total 47 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   codgeo                       34935 non-null  object
 1   libgeo                       34935 non-null  object
 2   typecom                      34935 non-null  object
 3   reg_code                     34935 non-null  object
 4   reg_nom                      34935 non-null  object
 5   dep_code                     34935 non-null  object
 6   dep_nom                      34935 non-null  object
 7   epci_code                    34932 non-null  object
 8   epci_nom                     34932 non-null  object
 9   niveau_equipements_services  34803 non-null  float64
 10  academie_code                34935 non-null  object
 11  code_postal                  34932 non-null  object
 12  codes_postaux                34933 non-null  object
 13  type_commune_unite_urbaine   34932 non-null  object
 14  population                   34935 non-null  int64
 15  codze                        34803 non-null  object
 16  zone_emploi                  34932 non-null  object
 17  latitude_mairie              34935 non-null  float64
 18  longitude_mairie             34935 non-null  float64
 19  url_wikipedia                34935 non-null  object
 20  polygon                      34767 non-null  object
 21  codbe                        34935 non-null  string
 22  libbe                        34935 non-null  object
 23  met                          34806 non-null  Int64
 24  met_tension                  34806 non-null  float64
 25  codfap                       34806 non-null  float64
 26  be_codfap_top                34806 non-null  object
 27  be_libfap_top                34806 non-null  object
 28  pop_be                       34806 non-null  float64
 29  codes_formations             27208 non-null  object
 30  noms_formations              27208 non-null  object
 31  svc_incl_count               9055 non-null   float64
 32  log_total                    34912 non-null  float64
 33  log_rp                       34912 non-null  float64
 34  log_vac                      34912 non-null  float64
 35  rp_5+pieces                  34912 non-null  float64
 36  log_soc_vacants              16814 non-null  float64
 37  log_soc_vides                16814 non-null  float64
 38  log_soc_total                16814 non-null  float64
 39  log_soc_inoccupes            16814 non-null  float64
 40  risque_fermeture             21756 non-null  float64
 41  ecoles_ct                    21756 non-null  float64
 42  nuance_politique             33122 non-null  object
 43  famille_nuance               33122 non-null  object
 44  pol_num                      34757 non-null  float64
 45  codgeo_voisins               34916 non-null  object
 46  nb_voisins                   34916 non-null  float64
dtypes: Int64(1), float64(19), int64(1), object(25), string(1)
memory usage: 12.6+ MB

In [15]:
odis_finess = pd.read_parquet('../pipeline/cache/raw/finess_national.parquet')

In [46]:
odis_finess[(odis_finess['Departement'] == '13') & (odis_finess['Commune'] == '103')][['LibelleCategorie','nofinesset']].groupby('LibelleCategorie').count().sort_values(by='nofinesset', ascending=False)

                                                              nofinesset
LibelleCategorie
Pharmacie d'Officine                                                  14
Service autonomie aide (SAA)                                          10
Laboratoire de Biologie Médicale                                       6
Etablissement d'hébergement pour personnes âgées dépendantes           5
Institut Médico-Educatif (I.M.E.)                                      4
Service de Soins Infirmiers A Domicile (S.S.I.A.D)                     3
Centre Hospitalier Spécialisé lutte Maladies Mentales                  3
Centre Hébergement & Réinsertion Sociale (C.H.R.S.)                    3
Autre Résidence Sociale (hors Maison Relais, Pension de Fami           3
Service d'Éducation Spéciale et de Soins à Domicile                    2
Etablissement Consultation Protection Infantile                        2
Etab.Accueil Non Médicalisé pour personnes handicapées                 2
Ecoles Formant aux Professions Sanitaires                              2
Etablissement et Service d'Aide par le Travail (E.S.A.T.)              2
Centre de Santé                                                        2
Structure Dispensatrice à domicile d'Oxygène à usage médical           2
Maison de santé (L.6223-3)                                             1
Maison d'Enfants à Caractère Social                                    1
Résidences autonomie                                                   1
Service d'accompagnement médico-social adultes handicapés              1
Foyer de l'Enfance                                                     1
Foyer de Jeunes Travailleurs (résidence sociale ou non)                1
Foyer d'Action Educative (F.A.E.)                                      1
Foyer Hébergement Enfants et Adolescents Handicapés                    1
Autre Centre d'Accueil                                                 1
Etablissement de santé privé autorisé en SSR                           1
Etablissement de Soins Longue Durée                                    1
Etablissement de Soins Chirurgicaux                                    1
Autre Etablissement Loi Hospitalière                                   1
Etab.Acc.Médicalisé en tout ou partie personnes handicapées            1
Entreprise adaptée                                                     1
Ecoles Formant aux Professions Sociales                                1
Communautés professionnelles territoriales de santé (CPTS)             1
Centre de vaccination internationale                                   1
Centre de dialyse                                                      1
Centre d'Accueil Thérapeutique à temps partiel (C.A.T.T.P.)            1
Centre Médico-Psychologique (C.M.P.)                                   1
Centre Hospitalier (C.H.)                                              1
Centre Action Médico-Sociale Précoce (C.A.M.S.P.)                      1
Centre Accueil Demandeurs Asile (C.A.D.A.)                             1
Structure d'Alternative à la dialyse en centre                         1

# Filter Asso Réfugies

In [47]:
asso =pd.read_parquet('../pipeline/cache/raw/associations.parquet')

In [20]:
asso.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2215247 entries, 0 to 2215246
Data columns (total 39 columns):
 #   Column           Dtype
---  ------           -----
 0   id               object
 1   id_ex            object
 2   siret            object
 3   rup_mi           object
 4   gestion          object
 5   date_creat       object
 6   date_decla       object
 7   date_publi       object
 8   date_disso       object
 9   nature           object
 10  groupement       object
 11  titre            object
 12  titre_court      object
 13  objet            object
 14  objet_social1    object
 15  objet_social2    object
 16  adrs_complement  object
 17  adrs_numvoie     object
 18  adrs_repetition  object
 19  adrs_typevoie    object
 20  adrs_libvoie     object
 21  adrs_distrib     object
 22  adrs_codeinsee   object
 23  adrs_codepostal  object
 24  adrs_libcommune  object
 25  adrg_declarant   object
 26  adrg_complemid   object
 27  adrg_complemgeo  object
 28  adrg_libvoie     object
 29  adrg_distrib     object
 30  adrg_codepostal  object
 31  adrg_achemine    object
 32  adrg_pays        object
 33  dir_civilite     object
 34  siteweb          object
 35  publiweb         object
 36  observation      object
 37  position         object
 38  maj_time         object
dtypes: object(39)
memory usage: 659.1+ MB

In [48]:
asso[asso['titre'].str.contains('SINGA ', case=False, na=False)].transpose()

,241875,348815,475225,972578,1052592,1059306,1094122,1340123,1358728,1381349,1387780,1498997,1533551,1807791,1819223,2031076,2182645,2199720,2203117
id,W595036943,W263008781,W332031571,W691094560,W423009544,W311003359,W313028481,W751213691,W751232364,W751258129,W751264589,W442026574,W381020064,W941011269,W942005243,W133032666,W852013975,W641013564,W642001872
id_ex,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
siret,None,None,None,83866142900061,None,None,None,79326794900014,None,None,None,None,None,None,None,None,None,None,None
rup_mi,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
gestion,595P,263P,332P,691P,423P,311S,313P,751P,751P,751P,751P,442P,381P,941P,942S,133P,852P,641S,642S
date_creat,2020-05-25,2018-05-08,2022-02-11,2018-02-09,2017-12-21,2014-04-11,2018-10-05,2012-02-20,2016-01-11,2020-09-24,2022-04-01,2021-11-22,2018-05-17,2017-04-14,2014-09-04,2019-07-10,2025-08-11,2022-07-18,2014-08-14
date_decla,2022-01-14,2023-12-17,2023-10-17,2024-07-05,2023-07-05,2014-04-11,2023-03-23,2023-05-26,2016-01-11,2020-09-24,2022-04-01,2025-03-02,2018-05-17,2017-04-14,2014-09-04,2024-03-16,2025-08-11,2022-07-18,2019-03-29
date_publi,2020-06-06,2018-05-19,2022-02-22,2018-02-17,2017-12-30,2014-04-26,2018-10-13,2012-03-03,2016-01-23,2020-10-03,2022-04-12,2021-11-30,2018-05-26,2017-04-29,2014-09-20,2019-07-20,2025-08-19,2022-07-26,2014-08-23
date_disso,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,0001-01-01,2018-12-20
nature,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D,D
groupement,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S,S
titre,SINGA LILLE,SINGA VALENCE,SINGA BORDEAUX,SINGA LYON,SINGA SAINT-ETIENNE,SINGA SOS,SINGA TOULOUSE,SINGA PARIS,SINGA SCIENCES PO,SINGA GLOBAL,SINGA YA FAMILLE,SINGA NANTES,SINGA GRENOBLE,BANA SINGA MOPEPE B.S.M,ASSOCIATION DES ENFANTS DE TSINGA POLYCLINIQUE ADTP,SINGA MARSEILLE,SINGA YETU,SOUTIEN SPORTIF POUR ENFANTS DE RUSINGA KENYA,SINGA SINGA
titre_court,SINGA LILLE,SINGA VALENCE,SINGA BORDEAUX,SINGA LYON,SINGA SAINT-ETIENNE,SINGA SOS,SINGA TOULOUSE,SINGA PARIS,SINGA SCIENCES PO,SINGA,SINGA YA FAMILLE,SINGA NANTES,SINGA GRENOBLE,B.S.M,ASSOCIATION DES ENFANTS DE TSINGA P...,SINGA MARSEILLE,S.Y.,SOUTIEN SPORTIF POUR ENFANTS DE RUSING,SINGA SINGA
objet,creer du lien social entre des citoyens nouveaux arrivants r deconstruire les cliches sur les migrations,"favoriser lemergence despaces et doutils de rencontre, dechange et de cooperation entre les personnes refugiees et les membres de la societe daccueil afin de favoriser le vivre ensemble, lenrichissement culturel et linclusion socioprofessionnelle favoriser le lien social et les interactions entre les personnes refugiees en France et les membres issus de la societe daccueil","favoriser lemergence despaces et doutils de rencontre, dechange et de cooperation, entre les personnes demandeuses dasile et beneficiaires de la protection internationale dune part, et leur societe daccueil dautre part, afin de permettre le vivre-ensemble, lenrichissement culturel, linclusion socio-professionnelle et la creation demploi pour tous a cet effet, lassociation accompagne les projets des personnes demandeuses dasile et des refugies statutaires ainsi que les projets de toute personne souhaitant contribuer a lintegration de ces derniers ou a lobjet de lassociation ce travail est renforce par une demarche de recherche, de sensibilisation et de plaidoyer promouvant des solutions","accueillir renforce la societe nous voulons agir pour la societe avec les nouveaux arrivants notre objet commun est de favoriser lemergence despaces et doutils de rencontre, dechange et de cooperation entre les personnes refugiees et leur societe daccueil afin de favoriser le vivre ensemble nous sommes laique, a-partisan et a rayonnement local SINGA Lyon est membre du reseau national et international SINGA, dont elle fait sienne les valeurs et les principes daction","favoriser le lien social et les interactions entre les personnes refugiees en France et les membres issus de la societe daccueil changer le regard que lon porte sur les personnes refugiees, pour renforcer le vivre-ensemble, lenrichissement culturel et linclusion socioprofessionnelle","promouvoir des evenements culturels et des groupes de musique, et faire valoir la musique du groupe SingA",creer des opportunites dengagement et de collaboration entre les personnes refugiees et leur societe daccueil,"favoriser lemergence despaces et doutils de rencontre, dechange et de cooperation entre les nouveaux arrivants et les citoyens locaux, afin daccelerer linnovation, de favoriser le vivre ensemble et lenrichissement culturel accompagner les projets personnels, professionnels et entrepreneuriaux des personnes refugiees et les nouveaux arrivants ainsi que les projets de toute personne souhaitant contribuer a linclusion des nouveaux arrivants, et par la valorisation de ces resultats, changer le narratif sur les migrations etre hospitalier a la serendipite, imaginer et mettre en oeuvre toutes nouvelles solutions innovantes pour parvenir aux objectifs susvises mobiliser sa communaute autour des projets professionnels, artistiques, culturels, sociaux et entrepreneuriaux des beneficiaires dune protection internationale proposer son expertise aux entreprises et organismes publics mener toute action ou gerer tout actif conformement aux valeurs du reseau singa afin de realiser son objet, lassociation peut intervenir directement ou en soutien dautres structures du reseau singa, collecter des fonds et les reverser a ces structures ou en recevoir de leur part, et en devenir membre","promouvoir les activites de SINGA France aupres des etudiants de Sciences Po en organisant des projets et des activites dordre culturel, sportif, social en relation avec lobjet social de SINGA France favoriser lemergence despaces et doutils de rencontre, dechange et de cooperation entre les beneficiaires de la protection internationale et leur societe daccueil pour contribuer au vivre ensemble, a lenrichissement culturel et a la creation demplois","defendre les valeurs du reseau singa, telles quexposees en preambule proteger la marque singa, den accorder ou retirer des licences dusage definir les criteres dappartenance au reseau singa ou dutilisation de la marque singa mesurer et evaluer les actions menees par les membres organiser la reflexion sur levolution des methodes du reseau singa, de mettre en place des formations et des outils pour permettre lappropriation de ces methodes soutenir lemergence de nouveaux membres, danimer le reseau singa et dassurer la circulation de linformation entre les membres, de definir les principes de communication des membres r communiquer sur les actions et les resultats obtenus par le reseau singa et de promouvoir les valeurs du reseau singa mener des actions de collecte de fonds et de recherche de financement dans le but de financer ses actions ou celles dorganisation respectant les valeurs du reseau singa, en ce compris les membres de lassociation vers lesquels certains financements leves par lassociation pourront etre orientes et mener toute action ou gerer tout actif conformement aux valeurs du reseau singa","aider les orphelins victimes de violences et de guerre, ainsi que les enfants vulnerables ou abandonnes en republique democratique du congo kinshasa dans le cadre dun projet darts therapeutique sous toutes les formes dart peinture, sculpture, dessin, danse, art multimedia, arts plastiques, arts martial, art musical, etc et proposer un pole de soutien pour les jeunes, avec laide a la reinsertion, recherche de formations et emplois, un pole pour les femmes qui ont perdu un ou des enfants, les aider grace a des groupes de paroles et de soutien psychologique vendre des produits artistiques, toiles, dessins, sculptures, etc au profit de lassociation fabriquer des produits artistiques fait a partir delements ecologiques et artisanaux recycles comme des crayons a papier ecologique, encre et peinture naturelle, marque page en bois recycle","favoriser lemergence despaces et doutils de rencontre, dechange et de cooperation entre les personnes refugiees, et plus largement les personnes nouvellement arrivees en France, et les membres issus de la societe daccueil, afin de favoriser le vivre ensemble, lenrichissement culturel et linclusion socio-professionnelle et de changer leur regard reciproque, en les considerant avant tout comme des personnes, chacun avec sa propre histoire, ses experiences, ses competences et ses aspirations","favoriser lemergence despaces et doutils de rencontre, dechange et de cooperation entre les personnes migrantes et leur societe daccueil afin de favoriser le vivre ensemble, lenrichissement culturel et linclusion socioprofessionnelle r Changer le regard envers les personnes migrantes, pour les considerer avant tout comme des individus, chacun avec son potentiel, ses experiences, ses aspirations r Accelerer linclusion des personnes migrantes, et accompagner a la creation dun reseau socioprofessionnel, en recherchant limplication de tous les acteurs de la societe daccueil : societe civile, collectivites, institutions, associations, entreprises r A cet effet, lassociation developpe trois missions principales : r -tInformer : sensibiliser et changer le regard sur lasile r -tConnecter : creer des outils et des espaces de rencontre entre personnes migrantes et membres issus de la societe daccueil r -tInnover : trouver des solutions innovantes aux problematiques dinclusion r Lassociation est a rayonnement local elle est laique, a-partisane et fonde lensemble de son fonctionnement et de ses actions sur une charte de valeurs","promouvoir la solidarite sous toutes ses formes notamment lentraide entre les membres, des activites de prevention, de formation et danimation a caractere culturel, sportif et social en direction des jeunes et de la famille en ecoutant, conseillant et soutenant les familles proposer aux enfants, des animations visant a lapprentissage de valeurs morales et civiques","nourrir et entretenir des relations chaleureuses damitie susciter et entretenir entre tous les membres un esprit de solidarite, dunite et dentraide mutuelle partager un meme ideal et debattre des problemes concernant lavenir de lassociation sensibiliser les membres sur les valeurs humaines, morales et amicales pouvoir sassister et sentraider a tout moment","lassociation est a vocation regionale sur la metropole marseillaise, elle est laique et apartisane elle a pour objet : favoriser lemergence despaces et doutils de rencontre, dechange et de cooperation entre les nouveaux arrivants et les citoyens locaux, afin daccelerer linnovation, de favoriser le vivre ensemble et lenrichissement culturel - daccompagner les projets personnels, professionnels et entrepreneuriaux des nouveaux arrivants ainsi que les projets de toute personne souhaitant contribuer a linclusion des nouveaux arrivants, et par la valorisation de ces resultats, changer ler narratif sur les migrations mobiliser sa communaute autour des projets professionnels, artistiques, culturels, sociaux et entrepreneuriaux des nouveaux arrivants proposer son expertise aux entreprises et organismes publics plus largement, de mener toute action ou gerer tout actif conformement aux valeurs du reseau singa lassociation fonctionne de maniere collaborative et prend ses decisions de maniere participative lassociation sinscrit comme participant a une economie sociale et solidaire","faciliter lintegration sociale et professionnelle des plus demunis, realiser des actions sociales aupres de populations vulnerables en Republique Democratique du CONGO et tous les autres moyens susceptibles de concourir a la realisation de ses objectifs",recolter des dons en euros et en materiel sportif dans le but dacheter et damener ce type de materiel dans la communaute de Rusinga au Kenya pour ameliorer lacces aux differents sports pour les enfants et adolescents de cette communaute,organisation et animation de festivites dans le cadre de lorganisation et interpretation de loeuvre ethno-mass for peace
objet_social1,020000,019025,020000,014070,014035,006100,020000,019025,015065,023000,019000,003000,020000,014000,014000,003000,014000,014035,006030
objet_social2,000000,000000,000000,000000,000000,000000,000000,000000,000000,000000,000000,020000,000000,000000,000000,000000,000000,020015,000000
adrs_complement,Bazaar St So,None,Appt 304 Bat 8,None,None,Appartement B5,None,None,None,None,None,None,Cap Berriat,None,None,None,Apprt 63 Batiment A,None,None
adrs_numvoie,292,29,8,103,38,1 bis,39,50,22,50,60,8,5-7,2,2,93,33,725,10
adrs_repetition,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
adrs_typevoie,RUE,RUE,RUE,RUE,RUE,IMP,ALL,RUE,RUE,RUE,RUE,RUE,RUE,PL,SQ,RUE,RUE,RTE,RUE
adrs_libvoie,Camille Guerin,Max Dormoy,Leon Jouhaux,Pierre Corneille,de la Ville,des Rosiers,de Brienne,de Montreuil,de Stael,de Montreuil,Francois 1er,Maurice Sibille,Georges Jacquet,de la Sabliere,des Catalpas,la Canebiere,Gutenberg,de Larramendia,Guitte
adrs_distrib,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
adrs_codeinsee,59350,26362,33063,69383,42218,31187,31555,75111,75115,75111,75108,44109,38185,94004,94067,13201,85191,64010,64409
adrs_codepostal,59800,26000,33800,69003,42000,31470,31000,75011,75015,75011,75008,44000,38000,94470,94160,13001,85000,64120,64400
adrs_libcommune,Lille,Valence,Bordeaux,Lyon 3,Saint-Etienne,Fonsorbes,Toulouse,Paris,Paris 15e,Paris,Paris,Nantes,Grenoble,Boissy-Saint-Leger,Saint-Mande,Marseille 1,Roche-sur-Yon,Aicirits-Camou-Suhast,Moumour
adrg_declarant,None,None,None,None,None,None,None,None,None,None,None,Leclercq Jenna,None,None,None,None,None,None,None
adrg_complemid,None,None,None,None,None,Appartement B5,CHEZ MME CELINE LAURIERE,None,None,None,None,None,None,None,None,None,APPRT 63,None,None
adrg_complemgeo,None,None,None,AU FAITOUT,None,None,None,None,None,None,None,None,None,None,None,None,BATIMENT A,None,None
adrg_libvoie,116 RUE NATIONALE,29 RUE MAX DORMOY,211 TER RUE EMILE COMBES,12 RUE GABRIEL PERI,40 RUE DE LA RESISTANCE,1 bis impasse des Rosiers,39 ALLEE DE BRIENNE,50 RUE DE MONTREUIL,22 rue de Stael,110 rue des Grands Champs,60 RUE FRANCOIS 1ER,8 RUE MAURICE SIBILLE,58 rue General Ferrie,2 place de la Sabliere,2 square des catalpas,"6, RUE VERLAINE",33 RUE GUTENBERG,725 ROUTE DE LARRAMENDIA,10 rue Guitte
adrg_distrib,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
adrg_codepostal,59800,26000,33700,69350,42000,31470,31000,75011,75015,75020,75008,44000,38100,94470,94160,13004,85000,64120,64400
adrg_achemine,LILLE,VALENCE,MERIGNAC,LA MULATIERE,SAINT-ETIENNE,Fonsorbes,TOULOUSE,PARIS,PARIS 15,PARIS 20,PARIS 08,NANTES,GRENOBLE,Boissy-Saint-Leger,Saint-Mande,MARSEILLE 04,LA ROCHE SUR YON,AICIRITS CAMOU SUHAST,Moumour
adrg_pays,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE,FRANCE
dir_civilite,PF,PG,PM,PF,PM,PM,CF,PF,PF,RE,PF,PF,PG,PM,PM,PF,MA,MR,PM
siteweb,None,None,None,https:singalyon.fr,None,None,None,https:www.singafrance.com,None,None,None,None,None,None,None,https:singafrance.commarseille,None,None,None
publiweb,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
observation,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
position,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,D
maj_time,2022-02-01 12:45:37,2024-06-17 18:06:40,2024-04-17 18:05:44,2024-11-12 10:08:36,2024-01-04 19:02:55,2014-05-02 10:55:17,2023-09-22 18:00:01,2023-06-14 05:53:55,2016-01-25 12:46:44,2020-10-03 12:45:21,2022-04-12 12:45:15,2025-03-03 15:54:22,2018-05-26 12:45:21,2017-04-29 12:45:14,2014-09-30 10:58:07,2024-09-15 18:07:59,2025-08-19 07:05:12,2022-07-26 12:45:19,2019-04-02 16:19:18

In [38]:
asso[(asso.objet_social1=='019025') & (asso.adrs_codeinsee=='33063')].titre_court.head(25)

468278    RESEAU UNIVERSITAIRE AIME
469936        LA FORCE DUNE MERE FM
477263              PONT DE LESPOIR
Name: titre_court, dtype: object

In [53]:
asso_refug = asso[asso.objet_social1.str.startswith(('003', '019', '020', '014'), na=False)].loc[
    asso['objet'].str.contains('asile', regex=False, case=False, na=False)|asso['objet'].str.contains('réfugié', regex=False, case=False, na=False),
    ['id', 'adrs_codeinsee', 'titre','position','objet_social1', 'objet']
]

In [54]:
mapping = odis_referentiels[odis_referentiels['key'] == 'waldec_codes'].set_index('code')['label']
asso_refug['objet_lib'] = asso_refug['objet_social1'].astype(int).astype(str).map(mapping)

In [55]:
asso_refug.groupby(['objet_social1', 'objet_lib']).count().sort_values(by='id', ascending=False)

,,id,adrs_codeinsee,titre,position,objet
objet_social1,objet_lib,,,,,
014035,groupements d'entraide et de solidarité,107,107,107,107,107
019025,aide aux réfugiés et aux immigrés (hors défense de droits fondamentaux),102,102,102,102,102
020000,"ASSOCIATIONS CARITATIVES, HUMANITAIRES, AIDE AU DÉVELOPPEMENT, DÉVELOPPEMENT DU BÉNÉVOLAT",89,89,89,89,89
003050,"défense de droits de personnes étrangères ou immigrées, de personnes réfugiées",89,89,89,89,89
014000,"AMICALES, GROUPEMENTS AFFINITAIRES, GROUPEMENTS D'ENTRAIDE (HORS DÉFENSE DE DROITS FONDAMENTAUX)",72,72,72,72,72
019000,INTERVENTIONS SOCIALES,55,55,55,55,55
020005,secours financiers et autres services aux personnes en difficulté,36,36,36,36,36
020015,associations caritatives à but multiple,31,31,31,31,31
003015,défense des libertés publiques et des droits de l'Homme,31,31,31,31,31
003000,"DÉFENSE DE DROITS FONDAMENTAUX, ACTIVITÉS CIVIQUES",23,23,23,23,23
014040,"amicale de personnes originaires d'un même pays (hors défense des droits des étrangers), d'une même région du monde",21,21,21,21,21
020020,associations caritatives intervenant au plan international,18,18,18,18,18
003045,défense de droits de personnes rapatriées,16,16,16,16,16
020010,"secours en nature, distribution de nourriture et de vêtements",10,10,10,10,10
003040,lutte contre les discriminations,6,6,6,6,6
003025,défense de droits de personnes homosexuelles,5,5,5,5,5
019040,"aide aux personnes en danger, solitude, désespoir, soutien psychologique et moral",5,5,5,5,5
014070,associations de personnes en situation de handicap pour l'entraide et la solidarité (hors défense de droits fondamentaux),4,4,4,4,4
019004,aide et conseils aux familles,3,3,3,3,3
019005,"associations familiales, services sociaux pour les familles",3,3,3,3,3
014050,associations féminines pour l'entraide et la solidarité (hors défense de droits fondamentaux),2,2,2,2,2
003010,défense de la paix,2,2,2,2,2
014060,associations de personnes homosexuelles pour l'entraide et la solidarité (hors défense de droits fondamentaux),2,2,2,2,2
019032,aide aux victimes de violences conjugales,1,1,1,1,1
003012,défense des droits des enfants,1,1,1,1,1
003020,"défense des droits des femmes, condition féminine",1,1,1,1,1
019047,foyers socio-éducatifs,1,1,1,1,1
003060,"activités civiques, information civique",1,1,1,1,1
003030,défense des droits des personnes en situation de handicap,1,1,1,1,1
019016,aide à l'insertion des jeunes,1,1,1,1,1
019014,lutte contre l'illettrisme,1,1,1,1,1
014025,organisation de professions (hors caractère syndical),1,1,1,1,1
003035,association pour la défense de droits de minorités,1,1,1,1,1
014045,amicale de personnes originaires d'une même région,1,1,1,1,1
014030,association du personnel d'une entreprise (hors caractère syndical),1,1,1,1,1
019010,"centres sociaux, foyers de jeunes travailleurs, centres d'études et d'action sociale",1,1,1,1,1

In [88]:
asso_refug[asso_refug['titre'].str.contains('SINGA')]

,id,adrs_codeinsee,titre,position,objet_social1,objet,objet_lib
475225,W332031571,33063,SINGA BORDEAUX,A,020000,"favoriser lemergence despaces et doutils de rencontre, dechange et de cooperation, entre les personnes demandeuses dasile et beneficiaires de la protection internationale dune part, et leur societe daccueil dautre part, afin de permettre le vivre-ensemble, lenrichissement culturel, linclusion socio-professionnelle et la creation demploi pour tous a cet effet, lassociation accompagne les projets des personnes demandeuses dasile et des refugies statutaires ainsi que les projets de toute personne souhaitant contribuer a lintegration de ces derniers ou a lobjet de lassociation ce travail est renforce par une demarche de recherche, de sensibilisation et de plaidoyer promouvant des solutions","ASSOCIATIONS CARITATIVES, HUMANITAIRES, AIDE AU DÉVELOPPEMENT, DÉVELOPPEMENT DU BÉNÉVOLAT"
1533551,W381020064,38185,SINGA GRENOBLE,A,020000,"favoriser lemergence despaces et doutils de rencontre, dechange et de cooperation entre les personnes migrantes et leur societe daccueil afin de favoriser le vivre ensemble, lenrichissement culturel et linclusion socioprofessionnelle r Changer le regard envers les personnes migrantes, pour les considerer avant tout comme des individus, chacun avec son potentiel, ses experiences, ses aspirations r Accelerer linclusion des personnes migrantes, et accompagner a la creation dun reseau socioprofessionnel, en recherchant limplication de tous les acteurs de la societe daccueil : societe civile, collectivites, institutions, associations, entreprises r A cet effet, lassociation developpe trois missions principales : r -tInformer : sensibiliser et changer le regard sur lasile r -tConnecter : creer des outils et des espaces de rencontre entre personnes migrantes et membres issus de la societe daccueil r -tInnover : trouver des solutions innovantes aux problematiques dinclusion r Lassociation est a rayonnement local elle est laique, a-partisane et fonde lensemble de son fonctionnement et de ses actions sur une charte de valeurs","ASSOCIATIONS CARITATIVES, HUMANITAIRES, AIDE AU DÉVELOPPEMENT, DÉVELOPPEMENT DU BÉNÉVOLAT"

In [52]:
odis_referentiels[(odis_referentiels.code=='23000')].head(100)

,key,code,label,reg_code
782,waldec_codes,23000,"REPRÉSENTATION, PROMOTION ET DÉFENSE D'INTÉRÊTS ÉCONOMIQUES",None

In [33]:
odis_associations_agg.head()

  codgeo id_waldec  count
0  00000    001000      1
1  00000    002000      1
2  00000    005000      2
3  00000    006000      1
4  00000    006030      3